### PR TITLE
[azp] Add parameter for running ST pipelines with specific Kafka version

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Type of change

- Enhancement

### Description

This PR adds possibility to specify Kafka version in all AZP pipelines, which are running STs. This `kafkaVersion` parameter will then set `ST_KAFKA_VERSION` (in case it will be different than `latest`, in that case the latest Kafka version will be used).

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by im-konge** [comment]
/azp run regression
kafkaVersion="3.2.0"

**Review by scholzj — APPROVED** [review]
LGTM assuming it works ;-)

**Comment by im-konge** [comment]
Examples:

Running with `latest` Kafka version - https://dev.azure.com/cncf/strimzi/_build/results?buildId=125317&view=logs&j=75c0b556-cc0f-5473-24e6-4d2a4a96ab8e&t=b94b1e6c-0ee8-5199-ec4b-06d99041425f

Running with `3.2.1.` Kafka version - https://dev.azure.com/cncf/strimzi/_build/results?buildId=125315&view=logs&j=75c0b556-cc0f-5473-24e6-4d2a4a96ab8e&t=b94b1e6c-0ee8-5199-ec4b-06d99041425f

**Comment by im-konge** [comment]
@Frawless for the investigation, I created https://github.com/strimzi/strimzi-kafka-operator/issues/7915

**Pull request merged**
