### PR TITLE
Move rebalance state enum into api module and CC enums into operator-common module

### PR DESCRIPTION
**Pull request by tomncooper**
### Type of change

Refactoring

### Description

This PR moves the rebalance state enum and annotation into the API module (so that users could utilise them for automation etc) and moves the various Cruise Control enum classes into the operator-common module, so that they can be used by the system test classes. This reduces the overhead of maintaining two sets of enums for CC. 

All CC system/unit tests have been updated and run.

### Checklist

- [X] Make sure all tests pass
- [X] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=cruisecontrol

**Comment by tombentley** [comment]
Forgive me for asking a possibly stupid question, but why do these things have to be in operator-common for the ST to be able to import them?

**Comment by scholzj** [comment]
@ppatierno I mentioned `api` in the past, but I seemed to be the only one. The problem here is that the STs had to create their own version of the Enum and the same will be needed by all users trying to build some Java automation around it. So I think this just confirms that it should be in `api` available for everyone. That said, this does not make it any worse than before and if it helps to clean the duplicate code from our STs it is better than nothing. So I do not have any problems with it.

**Comment by tomncooper** [comment]
> Forgive me for asking a possibly stupid question, but why do these things have to be in operator-common for the ST to be able to import them?

AFAIUI The systems tests do not import the cluster-operator module only the operator-common.

**Comment by tomncooper** [comment]
So would this make more sense in the api module?

**Comment by tomncooper** [comment]
Thinking about it more, it makes sense to have the Rebalance State available for others to use in automation (and probably the annotation too) but the CC enums are better in operator common as they are internal implementation details.

**Comment by scholzj** [comment]
I think the user could make use of the annotation names and of the Enum with the states.

**Comment by tomncooper** [comment]
@strimzi-ci run tests test_only profile=cruisecontrol

**Comment by scholzj** [comment]
> I think packaging the cluster-operator to allow it to be pulled in as a dependency would be more ideal for future tests though...

IIRC it was more question of philosophy to not make the STs dependent on the CO module. I do not think there is technically anything preventing it. The `operator-common` is supposed to share code between operators and not to system tests. So I do not think there is a big difference between having the STs depend on that versus depend on `cluster-operator`.

**Comment by scholzj** [comment]
So ... @samuel-hawker approved it, but commented about it being in `operator-common`. @tombentley didn't approved but commented on it as well ... so is this still something we should look at?

**Comment by tomncooper** [comment]
The azure build failed on the `apt update` which (AFAIK) has nothing to do with my code. How can I restart the azure pipeline?

**Comment by scholzj** [comment]
If you click on details next to the failed build, it has a `Re-run` link there. But TBH similarly to Travis, I'm not completely sure who does have it there and who doesn't.

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=cruisecontrol

**Comment by tomncooper** [comment]
That system test is passing locally. How can I see the logs from Jenkins?

**Comment by tomncooper** [comment]
@strimzi-ci run tests profile=cruisecontrol

**Pull request merged**
