### PR TITLE
Add Skillsoft to `ADOPTERS.md`

### PR DESCRIPTION
**Pull request by brandon-powers**
### Type of change

_Select the type of your PR_

- ~Bugfix~
- ~Enhancement / new feature~
- ~Refactoring~
- **Documentation**

### Description

_Please describe your pull request_

👋 

This PR adds **[Skillsoft](https://www.skillsoft.com/)** to `ADOPTERS.md` with a brief usage description. We've recently deployed the Strimzi Kafka operator along with a core service using it to run Kafka Connect on Kubernetes in our production environments.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [X] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
Great, thanks a lot.

**Review by im-konge — APPROVED** [review]
Great, thanks! :)

**Review by Frawless — APPROVED** [review]

**Review by see-quick — APPROVED** [review]
Thanks 💯

**Comment by brandon-powers** [comment]
Thanks all, I appreciate the quick turnaround!

**Comment by scholzj** [comment]
@brandon-powers If you would want, you could also add a logo to the website. There are some instructions here: https://github.com/orgs/strimzi/discussions/8183

**Pull request merged**
