### PR TITLE
Updated bridge version to latest 0.19.0 release

### PR DESCRIPTION
**Pull request by ppatierno**
This PR updates the bridge version to the 0.19.0.

### CODE REVIEW

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=bridge

**Comment by im-konge** [comment]
So the test failures on Azure are not connected to this PR, some of the failures was fixed in #3735, the others will be fixed by #3737

**Comment by im-konge** [comment]
Failures are not related to the upgrade/new version

**Comment by scholzj** [comment]
@strimzi-ci run tests test_only profile=bridge

**Comment by scholzj** [comment]
The Azure tests contain the usual host alias failures (#3737). Not sure about the Jenkins tests.

**Comment by im-konge** [comment]
@scholzj I'll take a look at it let you know

**Comment by ppatierno** [comment]
Updated to the latest 0.19.0 bridge release

**Comment by ppatierno** [comment]
@strimzi-ci run tests test_only profile=bridge

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
@ppatierno @im-konge Can this be merged? Or do we need some more investigation on the Jenkins failures?

**Comment by im-konge** [comment]
@scholzj how I mentioned offline, the issue is in tests itself. From MPOV this can be merged

**Pull request merged**
