### PR TITLE
Fix build process failing on source archives

### PR DESCRIPTION
**Pull request by fvaleri**
### Type of change

- Bugfix

### Description

This patch fixes the build process failing on source archives.

The build process fails when running on a source archive that does not contain the `.git` folder.

```sh
./.azure/scripts/check_docs.sh
make[1]: Entering directory '/home/fvaleri/Downloads/strimzi-kafka-operator-0.44.0-rc1'
documentation/snip-kafka-versions.sh > documentation/modules/snip-kafka-versions.adoc
documentation/version-dependent-attrs.sh > documentation/shared/version-dependent-attrs.adoc
documentation/snip-images.sh > documentation/modules/snip-images.adoc
make[1]: Leaving directory '/home/fvaleri/Downloads/strimzi-kafka-operator-0.44.0-rc1'
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
usage: git diff --no-index [<options>] <path> <path>
```

Reproducer:

```sh
wget https://github.com/strimzi/strimzi-kafka-operator/archive/refs/tags/0.44.0-rc1.tar.gz
tar xzf strimzi-kafka-operator-0.44.0-rc1.tar.gz
cd strimzi-kafka-operator-0.44.0-rc1
make MVN_ARGS="-DskipTests" all
```

### CODE REVIEW

**Comment by scholzj** [comment]
There is no intention for this to be used this way. It is part of the Strimzi CI and should be used as part of the Strimzi CI.

**Comment by fvaleri** [comment]
> It is part of the Strimzi CI and should be used as part of the Strimzi CI.

During releases, we provide source packages, and one should be able to build the project from there following the DEV_GUIDE.

**Comment by scholzj** [comment]
I don't think there is any such expectation. You are expected to build the project from the Github repository. If you wanna build some release, use the build tag.

**Comment by fvaleri** [comment]
> You are expected to build the project from the Github repository. 

But you can download the project as ZIP file from the GitHub repository, and that would also fail.

**Comment by ppatierno** [comment]
> During releases, we provide source packages, and one should be able to build the project from there following the DEV_GUIDE.

@fvaleri did we state to build the project from the source zip somewhere there? I can't find it.

Saying that, I think we should make a decision about stating in the DEV_GUIDE you can't build project from sources from zip but just cloning from GitHub or fixing the issue as this PR does.

@scholzj any drawbacks you see in this PR? I can't see anything which could hurt, or?

**Comment by scholzj** [comment]
> @scholzj any drawbacks you see in this PR? I can't see anything which could hurt, or?

Yes. It adds yet another complication to the tooling that someone needs to maintain, which has a risk of breaking down etc. It also does not seem to have any real use-case.

**Comment by ppatierno** [comment]
> It adds yet another complication to the tooling that someone needs to maintain

In reality the fix is just checking the we are inside a Git repo or not. My only doubt if it is a real fix or just a workaround.
If we don't want it, I think we should at least update the DEV_GUIDE clearly stating that the sources from the zip are not meant to be used to build the project but you should do from the GitHub repo instead.

**Comment by im-konge** [comment]
@strimzi/maintainers we discussed this on last week's community call, where I and Jakub added -1 for merging it. Could others please have a look, so we can decide how we will proceed with this? Thanks! :)

**Comment by see-quick** [comment]
> @strimzi/maintainers we discussed this on last week's community call, where I and Jakub added -1 for merging it. Could others please have a look, so we can decide how we will proceed with this? Thanks! :)

I don't have any strong opinion but looking at this it's just check for `.git` dir, which is fine by me. So +1 for this change 👍

**Comment by Frawless** [comment]
-1 from me. TBH I am not sure why it should be used outside CI. I never used `make all` to build project and images.

**Comment by fvaleri** [comment]
> I am not sure why it should be used outside CI

When testing a new RC, I simply go to the announced release page and get two files:

- the sources package
- `strimzi-cluster-operator-<version>.yaml` 

I use sources to build the project using the documented procedure (images are just a byproduct of that). I also use sources to run all tests locally, which allowed me to catch some flaky tests that were not identified by the CI pipeline.

Then, I use the YAML file to install Strimzi and manually run a bunch of real world use cases that I collected while supporting users. This allowed me to catch some bugs before the release.

I know you can simply check out the release tag, but I don't see any problem in adopting this patch and relaxing the hard dependency on git. If you know any reason why this would be bad, please let me know.

**Comment by ppatierno** [comment]
As mentioned in the community call I don't see how this fix can hurt the CI pipeline in general. I am +1 for it.

**Review by ppatierno — DISMISSED** [review]

**Review by see-quick — APPROVED** [review]

**Comment by PaulRMellor** [comment]
I'm for ease of use and flexibility as long as maintenance burdens aren't introduced.
It's +1 from me.  
The DEV_GUIDE should be updated to be clearer about what approaches are possible and what are recommended.

**Review by PaulRMellor — APPROVED** [review]

**Comment by ppatierno** [comment]
> The DEV_GUIDE should be updated to be clearer about what approaches are possible and what are recommended.

@PaulRMellor just to be sure about the above. Are you going to do it with a different PR or @fvaleri can do that on this one?

**Comment by fvaleri** [comment]
Closing because I don't have time to deal with it anymore. Thanks to people who approved the change.

**Pull request closed without merging**
