### PR TITLE
Added support Kafka 2.6.1 and removed 2.5.0 and 2.5.1

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Enhancement / new feature

### Description

This PR addresses #4224 , adding support for Kafka 2.6.1 and removing 2.5.0 and 2.5.1.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Make sure all tests pass
- [x] Update documentation
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by scholzj — APPROVED** [review]

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=upgrade

**Comment by ppatierno** [comment]
Closing this because replaced by #4440 and #4491

**Pull request closed without merging**
