### PR TITLE
[DOC] Fix secret names in security documentation

### PR DESCRIPTION
**Pull request by fvaleri**
This is required after PR #6006.

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
The changes to `documentation/modules/security/ref-certificates-and-secrets.adoc` are good. 

But the changes to `documentation/modules/deploying/proc-deploy-user-operator-standalone.adoc` suggest that we broker the backwards compatibility. So we probably need to look into it if it is really needed. Also, if we keep it, similar changes would need to be done to the TO documentation I guess. We would also need to add it to the CHANGELOG.md.

Maybe the easiest way to do right now would be to just remove the changes to `documentation/modules/deploying/proc-deploy-user-operator-standalone.adoc` until we investigate it.

**Comment by fvaleri** [comment]
> But the changes to documentation/modules/deploying/proc-deploy-user-operator-standalone.adoc suggest that we broker the backwards compatibility.

Well, I don't think we broke anything here. The value of `STRIMZI_EO_KEY_SECRET_NAME` is just an example, which happens to be equal to the old secret's name. Instead, in `proc-deploy-topic-operator-standalone.adoc` we use general examples like the following:

```
env:
  - name: STRIMZI_TRUSTSTORE_LOCATION (1)
    value: "/path/to/truststore.p12"
```

So maybe we can use something like `user-operator-certs-secret-name`, or leave it as it is. I'm fine with both.

**Comment by scholzj** [comment]
> I don't think we broke anything here.

The secret name is not the problem. But the keys inside the secret break the compatibility.

**Comment by fvaleri** [comment]
> The secret name is not the problem. But the keys inside the secret break
the compatibility.

You are right, we broke it here (changing from `entity-operator` to
`entity-user-operator`):

https://github.com/strimzi/strimzi-kafka-operator/blob/main/user-operator/src/main/java/io/strimzi/operator/user/Main.java#L128

CHANGELOG note added. We also need an update in
`ref-list-of-kafka-cluster-resources.adoc`. Should be all, but if you can
double check at your convenience it would be better.

**Comment by scholzj** [comment]
Yeah, but the right thing to do is to fix it so that it is not breaking change. Adding something to CHANGELOG is an option only if it can be fixed which I doubt.

**Review by scholzj — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR!

**Pull request merged**
