### PR TITLE
[ST] use namespace as first parameter in methods

### PR DESCRIPTION
**Pull request by henryZrncik**
### Type of change

- Refactoring

### Description

namespace is now used as first argument in methods. 

PR also contains 4 or 5 renaming from namespace to namespaceName for consistency in given file but apart from that there are no further renamings to keep review as simple as possible due to size of PR (all should be in first files in resources).

### CODE REVIEW

**Review by see-quick — APPROVED** [review]
LGTM, Thanks for the work! 👍

**Review by im-konge — APPROVED** [review]
LGTM, assuming it works. Thanks for the PR :)

**Pull request merged**
