### PR TITLE
Fixed tracing enabled on Kafka Connect and Mirror Maker

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Bugfix

### Description

This PR fixes a trivial bug where if tracing is enabled with something which is not "jaeger", it doesn't set the interceptors classes anyway.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ppatierno** [comment]
@scholzj good points ...

> What heppens if I set tracing to `tracing: {}`

So in general `{ }` for us means "use the default configuration" (i.e. `topicOperator`, `userOperator`, `listeners.tls`, ...) but in this case, it wouldn't make sense because the only property is `type` ... so "default" what? I don't like the idea of defaulting to Jaeger with `tracing: { }`.

> Will it be enabled? Disabled? Also, given the user has no other option to orchestrate the tracing than Jaeger, does it really make sense to do it without the type? (this technically probably applies for the Bridge as well thinking)

If we decide to support only Jaeger than the current `type` implementation doesn't really make sense but a `tracing` field with false/true is enough. The Jaeger tracing does every kind of configuration via env vars (using template in CR) so no more fields are needed under the `tracing` section.

Anyway, 0.14.0 is out we cannot change the "story" for compatibility reasons.
Staying with current CRD, cannot we validate that the `type` field is required? We can add it at CRD level but for compatibility even in the cluster operator.

**Comment by scholzj** [comment]
> So in general { } for us means "use the default configuration" (i.e. topicOperator, userOperator, listeners.tls, ...) but in this case, it wouldn't make sense because the only property is type ... so "default" what? I don't like the idea of defaulting to Jaeger with tracing: { }.

We do not expect anyone to use it ... but I wonder what it does with the codition you suggest. Maybe instead of `tracing != null` it should be `tracing != null && tracing.getType() != null`?

I'm not sure how the CRD validates the type here. Maybe it actually does. But regardless of that you can probably use the ^^^ to check the type is not null.

> If we decide to support only Jaeger than the current type implementation doesn't really make sense but a tracing field with false/true is enough. The Jaeger tracing does every kind of configuration via env vars (using template in CR) so no more fields are needed under the tracing section.

The idea was that in the future we might support more. Hence the type. I think that was reasonable

**Comment by ppatierno** [comment]
yeah I think that adding `tracing.getType() != null` make sense, it's a sort of validation that type is required somehow but we should at least print a warning in the CO log instead of just ignoring the tracing and not setting it. Wdyt?

**Comment by scholzj** [comment]
Yeah, sounds good to me.

**Pull request merged**
