### PR TITLE
 [ST] Fix for MetricsIsolatedST

### PR DESCRIPTION
**Pull request by jankalinic**
### Type of change

- Refactoring

### Description

This PR should fix problem with not ready ZooKeeper connection in MetricsIsolatedSTs.

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by henryZrncik — APPROVED** [review]

**Review by im-konge — APPROVED** [review]

**Comment by jankalinic** [comment]
Advanced testing showed that the actual number of zk should not matter and the whole failing situation should be handeled differently.

**Pull request closed without merging**
