### PR TITLE
Fix reconciliation when configuration changes

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

The fix from #2516 doesn't really work, because config map does not have `generation` field in metadata. It also triggers rolling update for changes to metrics configuration which is not needed. And it doesn't set the annotation to ZK pods, so if there actually was an `generation`, it would roll forever.

This PR reworks it by using SHA hashes of the broker configuration, of the broker logging and of the Zoo logging. The broker configuration one can be easily removed once we have proper diffing of the config against brokers.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.KafkaST#testNodePortTls,io.strimzi.systemtest.KafkaST#testLoadBalancerTls,io.strimzi.systemtest.ConnectST#testKafkaConnectWithFileSinkPlugin

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.KafkaST#testNodePortTls,io.strimzi.systemtest.KafkaST#testLoadBalancerTls,io.strimzi.systemtest.ConnectST#testKafkaConnectWithFileSinkPlugin

**Comment by Frawless** [comment]
@scholzj I think these tests was on our "broken" list today. @see-quick  or @lkral13  can you confirm that? I can see from nightly, that these failures are here for whole weekend so something bad happen before weekend with them.

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.KafkaST#testNodePortTls,io.strimzi.systemtest.KafkaST#testLoadBalancerTls,io.strimzi.systemtest.ConnectST#testKafkaConnectWithFileSinkPlugin

**Comment by scholzj** [comment]
@Frawless Some of them passed in #2557 ... but I'm getting quite a lot of these _Systemtests Failed (no tests results are present) _ messages.

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.KafkaST#testNodePortTls,io.strimzi.systemtest.KafkaST#testLoadBalancerTls,io.strimzi.systemtest.ConnectST#testKafkaConnectWithFileSinkPlugin

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.KafkaST#testNodePortTls,io.strimzi.systemtest.KafkaST#testLoadBalancerTls,io.strimzi.systemtest.ConnectST#testKafkaConnectWithFileSinkPlugin

**Comment by lkral13** [comment]
@scholzj @Frawless yes, I saw these tests on our list, but I think @see-quick done some fix (or I did in my PR) - that will be issue about wrong timeout set - we had it for 120ms

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.KafkaST#testNodePortTls,io.strimzi.systemtest.KafkaST#testLoadBalancerTls,io.strimzi.systemtest.ConnectST#testKafkaConnectWithFileSinkPlugin

**Pull request merged**
