### PR TITLE
Add log-dump script ST and refactoring

### PR DESCRIPTION
**Pull request by fvaleri**
This ST is much lighter than the other one (cold-backup). 

I also did some refactoring to make the two script styles consistent with each other, and improved a couple of functions (`wait_for()` in cold-backup and `get_kafka_setup()` in log-dump). Anyway, there is no interface or behavior change.

The small change to VerifiableClient is required by find-bugs.

### CODE REVIEW

**Review by Frawless — APPROVED** [review]

**Comment by scholzj** [comment]
The ST failure is only some failed cache. I will merge this after the CI finishes for the previous merge.

**Comment by fvaleri** [comment]
Thanks guys.

**Comment by scholzj** [comment]
Thanks for the PR!

**Pull request merged**
