### PR TITLE
ST: Add sanity profile for system tests

### PR DESCRIPTION
**Pull request by Frawless**
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

### Type of change

- Enhancement / new feature

### Description

This PR adds new profile `sanity` to system tests. It includes tests, which verify the core functionality of Strimzi + some additional features under 1h of execution time.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by see-quick — APPROVED** [review]

**Review by scholzj — COMMENTED** [review]
Not sure `sanity` is the best name ... but I guess I can live with it. Can you provide a list of tests which it will run?

**Comment by Frawless** [comment]
`MetricsIsolatedST` - whole class, basically it spinup all components and the tests are just simple checks mostly.
`SecurityST#testAutoRenewAllCaCertsTriggeredByAnno` - mainly for performing RU and certs renewal
`ConnectIsolatedST#testKafkaConnectAndPausedConnectorWithFileSinkPlugin` - for KafkaConnetor validation
`CruiseControlST#testCruiseControlWithRebalanceResourceAndRefreshAnnotation` - for KafkaRebalance validation
`ListenersST#testLoadBalancerTls` - for LoadBalancer
`ListenersST#testCustomSoloCertificatesForRoute` - for Route

Execution time is around 1h

**Comment by scholzj** [comment]
Why exactly these tests? Was the target to cover as many components as possible? Should it rather follow some key functionality?

**Comment by Frawless** [comment]
I wanted to cover the deployment of all components and some core functionality like messaging and RU and also finish it under 1h

**Review by scholzj — APPROVED** [review]

**Pull request merged**
