### PR TITLE
[systemtest] Change ST default kafka version to 3.0.0

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Type of change

- Bugfix

### Description

This PR fixes issue with hard-coded default version of Kafka used in STs and disables tests containing issues, which will be fixed in future PRs.

### Checklist

- [ ] Make sure all tests pass

### CODE REVIEW

**Comment by scholzj** [comment]
Does this mean that all the system tests till now were using Kafka 2.8.0?

**Comment by scholzj** [comment]
Or what exactly does this flag do?

**Comment by im-konge** [comment]
Yes, unfortunately. If the `ST_KAFKA_VERSION` env is not set, the default is used - until now `2.8.0`. Maybe it would be better to always get latest version instead of hardcoding it here.

**Comment by scholzj** [comment]
That is fucked up. Why does it not use the Kafka version from the example files? It takes almost everything from there. I think this needs to be rewritten to either take the version from examples or use the default Kafka version as default.

**Comment by im-konge** [comment]
Yes, that was what I was thinking about. Let me rewrite it a bit.

**Review by Frawless — APPROVED** [review]
LGTM

**Pull request merged**
