### PR TITLE
[systemtest][prometheus] Fix PrometheusST

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lkral@redhat.com>

### Type of change

- Bugfix

### Description

This PR gonna fix actual problem with Prometheus and `PrometheusST` tests -> problem is in master branch of project from which we are taking `bundle.yaml` -> some error appear after latest commit about CRDs rules deletion etc.

So I switched to latest functional release branch and we wait for fix from Prometheus team.

### Checklist

- [x] Write tests
- [ ] Make sure all tests pass

### CODE REVIEW

**Comment by im-konge** [comment]
@strimzi-ci run tests profile=regression testcase=PrometheusST

**Comment by im-konge** [comment]
@strimzi-ci run tests profile=regression testcase=PrometheusST

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=regression testcase=PrometheusST

**Comment by ppatierno** [comment]
I approved this but my general feeling is that we should move to install Prometheus via the operator. A few times ago they said me that the bundle was going to be not supported anymore. Maybe we should switch our doc to explain how to install Prometheus via the operator and abandoning the bundle way.

**Comment by im-konge** [comment]
@ppatierno I agree with that. I'll take a look at it on Monday. Thanks for the quick review and comment!

**Pull request merged**
