### PR TITLE
Updated to latest bridge to test OpenTracing removal

### PR DESCRIPTION
**Pull request by ppatierno**
This PR is just for running STs on the `latest` bridge to test the OpenTracing removal.

### CODE REVIEW

**Comment by ppatierno** [comment]
@strimzi-ci run tests --install-type=bundle --ocp-version=4.13 --testcase=OpenTelemetryST#testKafkaBridgeService,OpenTelemetryST#testKafkaBridgeServiceWithHttpTracing --build-images

**Comment by im-konge** [comment]
@strimzi-ci run tests --install-type=bundle --testcase=OpenTelemetryST#testKafkaBridgeService,OpenTelemetryST#testKafkaBridgeServiceWithHttpTracing --build-images --cluster-type=minikube --cluster-version=stable

**Comment by ppatierno** [comment]
I tried running the two above tests locally against minikube and it worked. This time I just used `latest` images because they are the right one from operator, Kafka and bridge side as well. They all include latest OpenTracing removal.
@im-konge can you check why they failed on Jenkins while waiting for regression on Azure please?

**Comment by ppatierno** [comment]
Thanks @im-konge ! It's also interesting that the regressions went fine.

**Comment by scholzj** [comment]
Can we close this again @ppatierno given the regression passed?

**Comment by ppatierno** [comment]
I was waiting for @im-konge confirming that the failures on Jenkins were unrelated to this.

**Comment by im-konge** [comment]
@ppatierno do you think that there is anything required from the test-clients side because of this
```
2023-08-15 13:16:11.567.3090232251473 [1;31mERROR[m HttpProducerClient:157 - Caught exception during message send
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error_code" (class io.strimzi.common.records.http.producer.OffsetRecordSent), not marked as ignorable (2 known properties: "partition", "offset"])
 at [Source: (String)"[{"error_code":500,"message":"Expiring 1 record(s) for my-topic-2066247287-591893002-0:229448 ms has passed since batch creation"}]"; line: 1, column: 19] (through reference chain: java.lang.Object[][0]->io.strimzi.common.records.http.producer.OffsetRecordSent["error_code"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:214)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:24)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
2023-08-15 13:16:11.576.3090240607815 [1;31mERROR[m HttpProducerClient:98 - Caught exception: Failed to send message due to: Unrecognized field "error_code" (class io.strimzi.common.records.http.producer.OffsetRecordSent), not marked as ignorable (2 known properties: "partition", "offset"])
 at [Source: (String)"[{"error_code":500,"message":"Expiring 1 record(s) for my-topic-2066247287-591893002-0:229448 ms has passed since batch creation"}]"; line: 1, column: 19] (through reference chain: java.lang.Object[][0]->io.strimzi.common.records.http.producer.OffsetRecordSent["error_code"])

```
?

Sorry, I didn't have time to look at it. I will for sure look at it tomorrow.

**Comment by ppatierno** [comment]
I don't know how test client works but it seems it's inspecting the JSON so you have got an "unrecognized" because this change in the OpenAPI spec:

https://github.com/strimzi/strimzi-kafka-bridge/commit/33907eed5e6ecffa61b895adcaa2f4ca6f2ca764

That's not related to OpenTelemtry and/or OpenTracing removal though.

**Comment by im-konge** [comment]
Okay then, I guess you are good. I will have a look on the clients to fix that issue. Thanks

**Comment by ppatierno** [comment]
Thanks @im-konge!
So @scholzj I am going to close this PR, it seems we are good with the latest bridge from an OpenTracing removal perspective.

**Pull request closed without merging**
