### PR TITLE
Run AZP in KRaft mode and create ZK regression pipeline

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Enhancement

### Description

This PR changes the default mode in which we are running AZP. 
It:
- changes the default mode to KRaft
- creates the `zookeeper-regression` pipeline, which runs without KRaft and NodePools
- changes the default of the `STRIMZI_USE_KRAFT_IN_TESTS` environment variable to `true`

From now on, when we run STs, they will be run in KRaft mode. In order to test ZK mode in AZP, we will need to run the `zookeeper-regression` pipeline.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by Frawless — APPROVED** [review]

**Review by scholzj — APPROVED** [review]
LGTM aassuming it works. Thanks.

What impact does this have at Acceptance, Helm Acceptance, Bridge, Migration, and Upgrade pipelines? I assume it switches the first three to KRaft as well, which is IMHO fine. But we should make sure the later two keep working properly as well.

**Comment by scholzj** [comment]
Also, I guess you should have opened the PR from a branch directly in the Strimzi repo as you probably cannot really test it now?

**Comment by im-konge** [comment]
I can't, I tried to include it on my repository
But I can push to Strimzi repo directly and from there create the pipeline and run the tests here.

> What impact does this have at Acceptance, Helm Acceptance, Bridge, Migration, and Upgrade pipelines? 

Everything will by default run in KRaft. The Upgrade pipeline is not that much affected, as each suite runs it's own mode -> the regular StrimziUpgrade/DowngradeST (KafkaUpgradeDowngradeST included) are running in ZK mode, KRaft...ST in KRaft. The MigrationST is skipped if the NodePools and KRaft are not enabled, which is not the case and it will not have any influence on running the ST. I can run it here and see if it's okay.

**Review by see-quick — APPROVED** [review]

**Review by henryZrncik — APPROVED** [review]

**Pull request merged**
