### PR TITLE
AZP: Add new pipeline for better verification

### PR DESCRIPTION
**Pull request by Frawless**
### Type of change

- Enhancement / new feature

### Description

This PR adds a new pipeline, which is able to trigger other pipelines and perform more complex verification of the images just by trigger one job. 

`acceptance` and `upgrade` will be triggered at first in parallel. In case that both pass, all other regressions will be executed one by one to save job count (estimated time for running all regressions jobs is around 15 hours). In case that `regression` will fail, the following regression jobs will be executed anyway.

image

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by scholzj** [comment]
Why did it not run the build pipeline? Just a glitch? Or did you break it?

**Comment by Frawless** [comment]
I assumed that `build` pipeline will be executed anyway. The images are build as part of the STs pipelines. However, I can try to add `build` pipeline as well and run it only for release branches for example?

**Comment by scholzj** [comment]
@Frawless No, I did not meant that build should be part of the pipeline ... I meant that build pipeline did not start for this PR.

**Comment by Frawless** [comment]
oh....good question. Guess it's some azure problem. Let me try to commit something

**Comment by Frawless** [comment]
ok it seems the changes in the hierarchy caused it. I think it's trying to do some kind of merge of pipelines from master and from my branch and the paths in master are different.

**Comment by scholzj** [comment]
You mean that it will fix it self after you merge it?

**Comment by Frawless** [comment]
Maybe or we will need to re-import `build` pipeline in Azure.

**Comment by Frawless** [comment]
I have basically the same issue on my personal AZP

**Comment by Frawless** [comment]
Results - https://dev.azure.com/jstejska/strimzi/_build/results?buildId=465&view=results

**Review by scholzj — APPROVED** [review]
LGTM assuming it does not break the other pipelines.

**Review by see-quick — APPROVED** [review]
LGTM, build pipeline seems to work after the last commit related to the path in `build-pipeline`. Anyway, great work!

**Pull request merged**
