### PR TITLE
Add 0.19.0 to upgrade tests

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

We should add the 0.19.0 release to the upgrade tests so that the upgrade from 0.18.0 -> 0.19.0 and 0.19.0 -> master are covered

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=upgrade

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=upgrade

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=upgrade

**Comment by scholzj** [comment]
I think the tests are fighting through infra issues. The design of this with two very long tests makes this a bit fragile. But it seems to pass on Jenkins. Assuming @Frawless is really off and not following GitHub, maybe someone else from @strimzi/maintainers can review this?

**Comment by scholzj** [comment]
@see-quick @im-konge Maybe one of you can review it as well?

**Comment by Frawless** [comment]
@see-quick could you please take a look on it? Upgrade was not fully stable on azure for me, not sure exactly why (maybe not enough resources - 8cpu16ram on jenkins vs 2cpu7ram on azure). TBH I didn't have much time to investigate it before my vacation. 

Anyway, if it's working on Jenkins, it should be fine from my pov.

**Comment by im-konge** [comment]
@scholzj @Frawless @see-quick If I'm right, we wanted to somehow refactor these upgrade tests and if it works on Jenkins, I think that's fine for now

**Comment by see-quick** [comment]
So I have briefly take a look on logs in Azure and it most likely problem with resources. There is a case where Kafka cluster can not start because of not enough resource. Specifically EO `my-cluster-entity-operator-8456c67658-nb8z2`.  Anyway, the result of these tests was: 
```
[ERROR] Tests run: 13, Failures: 0, Errors: 1, Skipped: 3, Flakes: 1
```
As previously mentioned by @Frawless. If Jenkins passing it's ok. I will create an issue to investigate more and hopefully resolve this issue.

**Pull request merged**
