### PR TITLE
Add microshift to list of allowed systemtest clusters

### PR DESCRIPTION
**Pull request by kornys**
### Type of change

Add microshift into allowed list of clusters to systemtest

### Description

Currently I'm unable to trigger tests on microshift due to error 
```
NoCluster Unable to find a cluster; tried [minikube, kubectl, oc]
```
This PR adds microshift into list.

### CODE REVIEW

**Review by Frawless — APPROVED** [review]
We should also identify tests that are not executable on microshift like connect build, etc, but it is not needed in scope of this PR.

**Review by im-konge — APPROVED** [review]
LGTM. Thanks for the PR :)

**Comment by scholzj** [comment]
Should we merge this?

**Comment by im-konge** [comment]
Yeah, will do.

**Pull request merged**
