### PR TITLE
Allow PRs run on crc in Jenkins

### PR DESCRIPTION
**Pull request by kornys**
### Type of change

- Enhancement / new feature

### Description

Ability to run PRs on crc in Jenkins

### Checklist

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by kornys** [comment]
@strimzi-ci run tests testcase=OpenShiftTemplatesST test_only crc

**Comment by kornys** [comment]
@strimzi-ci run tests testcase=OpenShiftTemplatesST test_only crc

**Comment by scholzj** [comment]
Is this now ready for review?

**Comment by kornys** [comment]
@scholzj not yet I need to complete pushing inages to internal registry

**Comment by kornys** [comment]
@strimzi-ci run tests profile=travis

**Comment by kornys** [comment]
@strimzi-ci run tests profile=travis crc

**Comment by kornys** [comment]
@strimzi-ci run tests profile=travis crc

**Comment by kornys** [comment]
@strimzi-ci run tests profile=travis

**Comment by kornys** [comment]
@strimzi-ci run tests profile=travis crc

**Comment by kornys** [comment]
@strimzi-ci run tests profile=travis crc

**Comment by Frawless** [comment]
Build on CRC env is currently not working cause some unclosed vertx in tests. @stanlyDoge is working on fix which will be delivered in separate PR. `test_only` on CRC is working without any issues.

**Comment by kornys** [comment]
@strimzi-ci run tests profile=travis crc

**Comment by kornys** [comment]
@strimzi-ci run tests profile=travis

**Comment by kornys** [comment]
@strimzi-ci run tests profile=travis crc

**Comment by kornys** [comment]
@strimzi-ci run tests profile=travis crc

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests profile=travis crc

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=travis crc

**Comment by scholzj** [comment]
@Frawless Is this needed for 0.17 as well?

**Comment by Frawless** [comment]
@scholzj No, we don't need it and there should be no conflicts in case of cherry-pick the tests later.

**Comment by scholzj** [comment]
Thanks for the PR @kornys

**Pull request merged**
