### PR TITLE
Update OAuth library version to 0.15.0

### PR DESCRIPTION
**Pull request by mstruk**
### Type of change

- Bugfix

### Description

Update the version of OAuth to 0.15.0. This PR does not integrate the new features, but the new version of the librare provides some bug fixes.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
I think at least in attributes.adoc is a version of the Oauth library that should be bumped.

**Comment by mstruk** [comment]
> I think at least in attributes.adoc is a version of the Oauth library that should be bumped.

True, missed this one.

**Review by scholzj — APPROVED** [review]
Thanks.

**Review by ppatierno — APPROVED** [review]

**Review by see-quick — APPROVED** [review]

**Pull request merged**
