### PR TITLE
Eliminate spotbugs errors

### PR DESCRIPTION
**Pull request by stanlyDoge**
Signed-off-by: Stanislav Knot <sknot@redhat.com>

### Type of change
- Bugfix
- Refactoring

### Description
There are few spotbugs errors in systemtest module.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by Frawless** [comment]
@strimzi-ci run tests

**Comment by scholzj** [comment]
Why is the`systemtests` module not checked by spotbugs in CI?

**Comment by stanlyDoge** [comment]
I do not know why. It is not in the `SUBDIRS` and thus the `sputbugs` target is not run over systemtests https://github.com/strimzi/strimzi-kafka-operator/blob/0c77ffddf8df0ecc92522c60deaea4388e827141/Makefile#L14

**Comment by stanlyDoge** [comment]
Spotbugs check in CI added in https://github.com/strimzi/strimzi-kafka-operator/pull/2249

**Pull request merged**
