### PR TITLE
Remove the JBOD storage check from `KafkaRebalanceAssemblyOperator`

### LINKED ISSUE #10280: [Bug]: Cannot use Cruise Control to rebalance disks on KafkaNodePools with JBOD volumes
### Bug Description

When creating a KafkaRebalance resource for a cluster containing a node pool with multiple volumes (JBOD), it fails with an error stating that the cluster does not have JBOD volumes.

### Steps to reproduce

1. Create a cluster with multiple volumes using storage type jbod:

    ```yaml
   apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaNodePool
    metadata:
      name: dual-role
      labels:
        strimzi.io/cluster: my-cluster
    spec:
      replicas: 3
      roles:
        - controller
        - broker
      storage:
        type: jbod
        volumes:
          - id: 0
            type: persistent-claim
            size: 10Gi
            deleteClaim: false
            kraftMetadata: shared
          - id: 1
            type: persistent-claim
            size: 10Gi
            deleteClaim: false
            kraftMetadata: shared
    ---
    
    apiVersion: kafka.strimzi.io/v1beta2
    kind: Kafka
    metadata:
      name: my-cluster
      annotations:
        strimzi.io/node-pools: enabled
        strimzi.io/kraft: enabled
    spec:
      cruiseControl: {}
      kafka:
        version: 3.7.0
        metadataVersion: 3.7-IV4
        listeners:
          - name: plain
            port: 9092
            type: internal
            tls: false
          - name: tls
            port: 9093
            type: internal
            tls: true
        config:
          offsets.topic.replication.factor: 1
          transaction.state.log.replication.factor: 1
          transaction.state.log.min.isr: 1
          default.replication.factor: 1
          min.insync.replicas: 1
      entityOperator:
        topicOperator: {}
        userOperator: {}
   ```

2. Create a KafkaRebalance resource

   ```yaml
   apiVersion: kafka.strimzi.io/v1beta2
   kind: KafkaRebalance
   metadata:
     name: proposal
     labels:
       strimzi.io/cluster: my-cluster
   spec: 
     skipHardGoalCheck: true
     rebalanceDisk: true
     goals:
     - CpuCapacityGoal
     - DiskCapacityGoal
     - RackAwareGoal
     - MinTopicLeadersPerBrokerGoal
     - ReplicaCapacityGoal
   ```

3. Describe the resource and observe the following status condition:

   ```
   Conditions:
     Last Transition Time:  2024-06-29T21:03:53.198686083Z
     Message:               Cannot set rebalanceDisk=true for Kafka clusters with a non-JBOD storage config. Intra-broker balancing only applies to Kafka deployments that use JBOD storage with multiple disks.
     Reason:                InvalidResourceException
     Status:                True
     Type:                  NotReady

   ```

### Expected behavior

Cruise Control should rebalance the data across JBOD volumes.

### Strimzi version

0.41.0

### Kubernetes version

v1.28.3

### Installation method

YAML files

### Infrastructure

Minikube

### Configuration files and logs

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

Currently, when intra-broker rebalancing is requested by the user, the `KafkaRebalanceAssemblyOperator` checks whether the Kafka cluster is using JBOD storage and if not, raises an error. However, the check is only checking the storage in the `Kafka` CR and thus does not work when node pools or KRaft are used.

Fixing the check to support node pools seems fairly complicated:
* It would need to be able to query and check both Kafka and KafkaNodePool CRs
* It would need to understand controller, broker or mixed node pools
* The JBOD usage flag is not really binary anymore as some nodepools might use JBOD while others might not

Cruise Control actually doesn't seem to have any problem to run the intra-broker rebalancing when JBOD storage is not used. It just proceeds with the rebalance without really doing anything. So the check does not seem to be worth fixing and maintaining and this PR simply removes it. If the user without a JBOD storage runs intra-broker rebalancing, they will not get the error anymore to inform them that it does not make sense. But everything will work fine without any problems.

This should resolve #10280 

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Comment by ShubhamRwt** [comment]
LGTM but isn't it possible that this can cause confusion? I mean if a user tries intra-broker balancing without JBOD storage, they will get a still proposal through which they can rebalance but in reality it is wrong? Also aren't we changing the behaviour here, earlier we would move the rebalance to `NotReady` state but now we are continuing the rebalance. Maybe just a warning in the status section depicting that `Intra-broker balancing only applies to Kafka deployments that use JBOD storage with multiple disks` and also mentioning about how this message is irrelevant in case of NodePools and KRaft?

**Review by ppatierno — APPROVED** [review]
I also looked at Cruise Control code and it seems to be no complaining about asking for `rebalance_disk` but not having JBOD. I guess this choice is the simpler one.
Anyway I would like to have @kyguy view too.

**Review by kyguy — APPROVED** [review]
>  I mean if a user tries intra-broker balancing without JBOD storage, they will get a still proposal through which they can rebalance but in reality it is wrong?

When requesting an intra-broker balance on a Kafka cluster with a non-JBOD storage configuration, Cruise Control will return a proposal for an inter-broker balance instead. 

We added this check to protect users from accidentally executing an inter-broker balance but I am ok with removing it for the following reasons:

(1)  To get in a situation where a user would be at risk of accidentally running an inter-broker balance instead of an intra-broker balance they would have already had to have misconfigured their storage configuration. The chances of doing these two things in succession unknowingly are slim.

(2) I agree that keeping the check is not worth the resulting `KafkaNodePools` bug or the hacking/maintaining of code to address it.

(3) This is how bare-metal Cruise Control behaves by default anyway, there are no guardrails to protect against this specific scenario by default

Most important thing is to resolve the issue blocking rebalances, we can investigate putting guardrails at a later date so long as it doesn't impede other features or functionality

**Pull request merged**
