### PR TITLE
Upgrade Prometheus JMX exporter 0.1.0 → 0.11.0

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Enhancement / new feature

### Description

Upgrade Prometheus JMX exporter 0.1.0 → 0.11.0

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by scholzj** [comment]
Was I too naive when I assumed that Tom run the dashboards and alerts and
saw that they work fine with this? :-o

**Comment by ppatierno** [comment]
@scholzj yes you were :P

**Comment by stanlyDoge** [comment]
@scholzj @ppatierno I did entire chain (prometheus, alerts, grafana for zk and kafka) and everything seems to work fine with 0.11.0.

**Comment by ppatierno** [comment]
@stanlyDoge thanks! but Travis is failing can you take a look at it?

**Pull request merged**
