### PR TITLE
Fix shouldUpdateTopicInKafkaWhen* test flakiness

### PR DESCRIPTION
**Pull request by fvaleri**
### Type of change

- Bugfix

### Description

Attempt to fix shouldUpdateTopicInKafkaWhen* test flakiness.
We cannot reproduce locally, so I would need to use some CI time to verify.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by fvaleri** [comment]
@see-quick I ran the CI for 10 times without issues. Can you also check and confirm? Thanks.

**Comment by see-quick** [comment]
> @see-quick I ran the CI for 10 times without issues. Can you also check and confirm? Thanks.

I will take a look at this tomorrow. Thanks

**Comment by fvaleri** [comment]
This is unrelated to previous test failures and new:

```sh
2024-12-12T15:18:58.6368702Z [ERROR] io.strimzi.operator.topic.KafkaHandlerIT.shouldDescribeTopics -- Time elapsed: 9.002 s <<< ERROR!
2024-12-12T15:18:58.6369340Z java.util.NoSuchElementException: No value present
2024-12-12T15:18:58.6369827Z 	at java.base/java.util.Optional.get(Optional.java:143)
2024-12-12T15:18:58.6370319Z 	at io.strimzi.operator.topic.KafkaHandlerIT.shouldDescribeTopics(KafkaHandlerIT.java:246)
```

Here we fixed an ordering issue, and that's fine. But I don't understand why `changeTopic` and `describeTopic` are sometimes not executed. 

I think we need to enable trace level and maybe add some more logging. I also wonder if `testcontainers` could be somewhat responsible. Does it run differently on Azure compared to dev machines? @see-quick

**Comment by see-quick** [comment]
>  I also wonder if testcontainers could be somewhat responsible. Does it run differently on Azure compared to dev machines? @see-quick

only if you use an ARM-based machine locally, otherwise it should be 1:1. Plus on minikube there is also a memory and CPU limit (6.9GB and 2CPUs AFAIK).

> I also wonder if testcontainers could be somewhat responsible.

Not sure but with more logging f.e., [1] we can have more info and troubleshoot that issue better.  

[1] - https://github.com/strimzi/test-container/pull/123

**Comment by fvaleri** [comment]
Closing as this work has been incorporated into #10914.

**Pull request closed without merging**
