### PR TITLE
Use the right default image for init and tls sidecar containers

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

This fixes the bug found by @kyguy where we seem to incorectly detect default images for init containers and tls sidecars.

### Checklist

- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by scholzj** [comment]
@tombentley Because we do not have any. The way this is read directly form the environment variables makes it hard to test. I think we will need bigger refactoring to be able to cover it with some unit tests. But that would be IMHO too big for 0.14.0 release.

**Comment by tombentley** [comment]
Then please can someone open an issue for adding regression tests ± larger refactoring, so that it isn't just forgotten about after 0.14.

**Comment by scholzj** [comment]
I opened #2005 to get back to this in the future.

**Pull request merged**
