### PR TITLE
ST: Break infinite loop for producers in tests

### PR DESCRIPTION
**Pull request by Frawless**
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

### Type of change

- Bugfix

### Description

This PR adds a break for our implementation of Kafka producer. Before this, the producer were running in memory until end of the test plan and generate tons of useles debug log.

This should be cherry-picked to `release-0.20.x`

### Checklist

- [] Make sure all tests pass

### CODE REVIEW

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=externalclients test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=externalclients test_only testcase=!StrimziUpgradeST

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=externalclients test_only testcase=!StrimziUpgradeST,!SpecificST

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=externalclients test_only testcase=!StrimziUpgradeST,!SpecificST

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=externalclients test_only testcase=!StrimziUpgradeST,!SpecificST

**Comment by Frawless** [comment]
I think test failures on Jenkins are caused by some infra issues, because Azure is green without any issues. @see-quick could you do a review please?

**Comment by michalxo** [comment]
@strimzi-ci run tests profile=externalclients test_only testcase=!StrimziUpgradeST,!SpecificST

**Comment by michalxo** [comment]
@strimzi-ci run tests profile=externalclients test_only testcase=!StrimziUpgradeST,!SpecificST

**Comment by see-quick** [comment]
Yes as we discussed. I think that assumption that Jenkins (infra issues) is correct and with green Azure is OK.

**Review by see-quick — APPROVED** [review]

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=externalclients test_only testcase=!StrimziUpgradeST,!SpecificST

**Comment by Frawless** [comment]
This should be cherry-picked to `release-0.20.x`

**Review by scholzj — APPROVED** [review]

**Pull request merged**
