### PR TITLE
Remove env recreate in case of test failure

### PR DESCRIPTION
**Pull request by Frawless**
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

### Type of change

- Refactoring

### Description

Strimzi should be fault-tolerant system, so in case of test failure, Strimzi should deal with it and should be operational for the following tests/operations. Based on that, we don't need to recreate test environment when some test fail.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by samuel-hawker** [comment]
So you can remove this without any additions to the code? Or is that to come?

**Comment by Frawless** [comment]
@samuel-hawker  yes, in general, Strimzi should deal with problems during test failures. For example, Kafka will not be ready in time -> until this change the whole environment will be recreated (delete namespace -> create namespace -> create new CO) but with this change, the CO will remain same for the whole test class. Problematic Kafka CR will be deleted at the end of the test, but the next test will create new Kafka and Strimzi should be operational and server this new cluster without issues.  

Maybe we should change the name of Kafka cluster for each test case.

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=KafkaST test_only

**Comment by ppatierno** [comment]
@Frawless didn't you mention that the cluster name should be different for each test?

**Comment by Frawless** [comment]
We have it different in some cases, but mostly it's set to `my-cluster`. There is no problems with it at all, but for example if we want to run tests in parallele, we need to change it

**Comment by Frawless** [comment]
@scholzj I think the only possible issue would be failures during teardown phase when for example Kafka pod are stuck in terminating state. Currently, we have like 1/2 failures only during nightly builds so I think it should not impact us too much. I think I can run multiple PR builds on Jenkins to see if it's stable for now or not.

This change is also a requirement for test parallel execution via surefire/junit5.

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=KafkaST test_only

**Pull request merged**
