### PR TITLE
[systemtest] Add test for multi-node Connect/ConnectS2I

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change
- Enhancement / new feature

### Description

Add test for multi-node Kafka Connect/ConnectS2I - checks functionality of network policies and if messages are passed by connector.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass

### CODE REVIEW

**Comment by im-konge** [comment]
@strimzi-ci run tests profile=regression testcase=ConnectST#testMultiNodeKafkaConnectWithConnectorCreation,ConnectS2IST#testMultiNodeKafkaConnectS2IWithConnectorCreation test_only

**Comment by im-konge** [comment]
@strimzi-ci run tests profile=regression testcase=ConnectST#testMultiNodeKafkaConnectWithConnectorCreation,ConnectS2IST#testMultiNodeKafkaConnectS2IWithConnectorCreation test_only

**Comment by scholzj** [comment]
@im-konge There seem to be some checkstyle failures which you need to fix I guess.

**Comment by im-konge** [comment]
@scholzj I think it's fixed now

**Comment by im-konge** [comment]
@strimzi-ci run tests profile=regression testcase=ConnectST#testMultiNodeKafkaConnectWithConnectorCreation,ConnectS2IST#testMultiNodeKafkaConnectS2IWithConnectorCreation test_only

**Pull request merged**
