### PR TITLE
Migrate to UBI8 base image

### LINKED ISSUE #4472: Switch Docker Base Image to UBI8
**Is your feature request related to a problem? Please describe.**
The base image is built upon CentOS 7, thus resultant docker images which will leverage kafka-base are also on CentOS 7, which is older than UBI 8.

**Describe the solution you'd like**
It would be better to equip UBI 8 ( latest and greatest ) and continue the builds, given that RedHat is now releasing docker images which is freely accessible to all.

**Describe alternatives you've considered**
RedHat's UBI8-minimal or UBI 8

^^^ @gerrith3 , @seth-priya

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

This PR implements [SP-24](https://github.com/strimzi/proposals/blob/main/023-using-ubi8-as-base-image.md) and migrates Strimzi to use Red Hat UBI8 base image.

This should close #4472.

### Checklist

- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi/maintainers This should be now ready for review.

**Review by tombentley — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Pull request merged**
