### PR TITLE
Fix typo in import control

### PR DESCRIPTION
**Pull request by fvaleri**
This change fixes a typo in the import-control configuration file.

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
I guess the rule is not needed if everything worked despite the typo?

**Comment by fvaleri** [comment]
Unlike `Labels` that is in `operator-common/io/strimzi/operator/common/model`, `Annotations` is in `operator-common/io/strimzi/operator/common`. Is this correct, or we want to move `Annotations` inside model and keep the rule?

**Comment by scholzj** [comment]
> Unlike `Labels` that is in `operator-common/io/strimzi/operator/common/model`, `Annotations` is in `operator-common/io/strimzi/operator/common`. Is this correct, or we want to move `Annotations` inside model and keep the rule?

Sorry, I don't follow what you mean by this.

If the rule refers to a wrong class and nothing is failing, it seems that either the import control does not work properly or the rule is not needed at all.

**Comment by fvaleri** [comment]
We have two similar rules for operator-common:

```sh
<import-control pkg="io.strimzi" strategyOnMismatch="allowed">
    <subpackage name="operator.common.model" strategyOnMismatch="disallowed">
        ...
        <allow class="io.strimzi.api.ResourceLabels" />        <!-- rule 1 -->
        <allow class="io.strimzi.api.ResourceAnnotations" />   <!-- rule 2 -->
```

These rules are supposed to be used by the following classes:

```sh
io.strimzi.operator.common.model.Labels // extends io.strimzi.api.ResourceLabels 
io.strimzi.operator.common.Annotations // extends io.strimzi.api.ResourceAnnotations
```

Nothing is failing because `Annotations` is NOT in the `operator.common.model` package. 

Now, there are two paths here:

1. Simply get rid of rule 2
2. Move the `Annotations` class from `io.strimzi.operator.common.` to `io.strimzi.operator.common.model` and keep the current change.

**Comment by scholzj** [comment]
I would probably remove the rule.

**Review by scholzj — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Review by see-quick — APPROVED** [review]

**Pull request merged**
