### PR TITLE
[system test] Update Azure KRaft pipelines to run KRaft

### PR DESCRIPTION
**Pull request by see-quick**
### Type of change

- Bugfix

### Description

Currently, we do not run all Azure profiles as KRaft (as we should). This PR fixes such a problem.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
Did I really set it only for one job and then _randomly_ selected the same job to check it works? Sorry 🤦

**Comment by see-quick** [comment]
> Did I really set it only for one job and then randomly selected the same job to check it works? Sorry 🤦

No problem, it was a bad review from my side :/.

**Review by Frawless — APPROVED** [review]

**Review by im-konge — APPROVED** [review]

**Comment by see-quick** [comment]
There is a one-fail, which I fixed in the previous commit. 
```java
Conditions:
	Type: Warning
	Message: The .spec.zookeeper section in the Kafka custom resource is ignored in KRaft mode and should be removed from the custom resource.
	Type: Warning
	Message: The .spec.kafka.replicas property in the Kafka custom resource is ignored when node pools are used and should be removed from the custom resource.
	Type: Warning
	Message: The .spec.kafka.storage section in the Kafka custom resource is ignored when node pools are used and should be removed from the custom resource.
	Type: NotReady
	Message: The Kafka cluster my-cluster-74fcefe3 is invalid: [At least one KafkaNodePool with the controller role and at least one replica is required when KRaft mode is enabled]
```
I would not trigger the pipeline for this one change okay? :)

**Comment by im-konge** [comment]
@see-quick I think we should move the whole test to run in the KRaft mode, but for now, I guess that's good 
Thanks

**Comment by see-quick** [comment]
Hmm it seems we have failed this test case but my change does not cause it 
```java
[ERROR] Errors: 
[ERROR] io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperatorWithPoolsMockTest.testReconcileReplacesAllDeletedSecrets(VertxTestContext)
[ERROR]   Run 1: KafkaAssemblyOperatorWithPoolsMockTest.testReconcileReplacesAllDeletedSecrets(VertxTestContext) » FatalProblem Error while waiting for restarted pod my-cluster-pool-a-2 to become ready
[ERROR]   Run 2: KafkaAssemblyOperatorWithPoolsMockTest.testReconcileReplacesAllDeletedSecrets(VertxTestContext) » FatalProblem Error while waiting for restarted pod my-cluster-pool-b-3 to become ready
[ERROR]   Run 3: KafkaAssemblyOperatorWithPoolsMockTest.testReconcileReplacesAllDeletedSecrets(VertxTestContext) » FatalProblem Error while waiting for restarted pod my-cluster-pool-b-4 to become ready
[ERROR]   Run 4: KafkaAssemblyOperatorWithPoolsMockTest.testReconcileReplacesAllDeletedSecrets(VertxTestContext) » FatalProblem Error while waiting for restarted pod my-cluster-pool-b-4 to become ready
[ERROR]   Run 5: KafkaAssemblyOperatorWithPoolsMockTest.testReconcileReplacesAllDeletedSecrets(VertxTestContext) » FatalProblem Error while waiting for restarted pod my-cluster-pool-a-2 to become ready
[ERROR]   Run 6: KafkaAssemblyOperatorWithPoolsMockTest.testReconcileReplacesAllDeletedSecrets(VertxTestContext) » FatalProblem Error while waiting for restarted pod my-cluster-pool-a-2 to become ready
```
even 6 runs are not enough to get this test case passed. I would re-trigger the build, but we should fix such a test. :) I don't know if this is happening on other PRs but I would assume yes.

**Pull request merged**
