### PR TITLE
Make CO log level configurable

### PR DESCRIPTION
**Pull request by Frawless**
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

### Type of change

- Bugfix
- Enhancement / new feature

### Description

After adding dynamic logging for CO, we lost an option to change log level via env var. This PR adds this option for yaml bundle installation and for helm installation as well.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by stanlyDoge — APPROVED** [review]

**Review by scholzj — APPROVED** [review]

**Comment by Frawless** [comment]
I am going to debug the issue on AZP. It looks that helm-acceptance has something wrong with pulling images, which are actually stored locally. This issue is not caused by my changes, locally it's working fine.

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=acceptance install_type=helm test_only

**Comment by Frawless** [comment]
@samuel-hawker any comments to this PR?

**Comment by Frawless** [comment]
Ok after my latest changes there is one failure in helm-acceptance. I think it's just flaky or it's connected to the wrong match in our CO log checker. It's not connected to my changes.

**Pull request merged**
