### PR TITLE
Fix logging errors and updating KafkaRebalance status

### LINKED ISSUE #6824: Errors on `KafkaRebalance` custom resource not logged properly
While applying a `KafkaRebalance` with `add-brokers` mode but missing the mandatory `brokers` list, the custom resource doesn't move immediately in the `NotReady` state with a condition showing a clear error message.
Even the operator doesn't print the error until the next reconcile.

```shell
2022-05-16 15:19:43 INFO  KafkaRebalanceAssemblyOperator:399 - Reconciliation #71(kafkarebalance-watch) KafkaRebalance(default/my-rebalance): Rebalance action from state [New]
2022-05-16 15:20:51 INFO  ClusterOperator:128 - Triggering periodic reconciliation for namespace default
2022-05-16 15:20:51 INFO  AbstractOperator:226 - Reconciliation #72(timer) Kafka(default/my-cluster): Kafka my-cluster will be checked for creation or modification
2022-05-16 15:20:51 INFO  AbstractOperator:226 - Reconciliation #73(timer) KafkaRebalance(default/my-rebalance): KafkaRebalance my-rebalance will be checked for creation or modification
2022-05-16 15:20:51 INFO  KafkaRebalanceAssemblyOperator:399 - Reconciliation #73(timer) KafkaRebalance(default/my-rebalance): Rebalance action from state [New]
2022-05-16 15:20:51 ERROR AbstractOperator:253 - Reconciliation #73(timer) KafkaRebalance(default/my-rebalance): createOrUpdate failed
java.lang.IllegalArgumentException: The brokers list is mandatory when using the add-brokers rebalancing mode
    at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.convertRebalanceSpecToRebalanceOptions(KafkaRebalanceAssemblyOperator.java:344) ~[io.strimzi.cluster-operator-0.29.0.jar:0.29.0]
    at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.reconcile(KafkaRebalanceAssemblyOperator.java:419) ~[io.strimzi.cluster-operator-0.29.0.jar:0.29.0]
    at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.lambda$reconcileRebalance$29(KafkaRebalanceAssemblyOperator.java:1210) ~[io.strimzi.cluster-operator-0.29.0.jar:0.29.0]
    at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-05-16 15:20:51 WARN  AbstractOperator:532 - Reconciliation #73(timer) KafkaRebalance(default/my-rebalance): Failed to reconcile
java.lang.IllegalArgumentException: The brokers list is mandatory when using the add-brokers rebalancing mode
    at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.convertRebalanceSpecToRebalanceOptions(KafkaRebalanceAssemblyOperator.java:344) ~[io.strimzi.cluster-operator-0.29.0.jar:0.29.0]
    at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.reconcile(KafkaRebalanceAssemblyOperator.java:419) ~[io.strimzi.cluster-operator-0.29.0.jar:0.29.0]
    at io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperator.lambda$reconcileRebalance$29(KafkaRebalanceAssemblyOperator.java:1210) ~[io.strimzi.cluster-operator-0.29.0.jar:0.29.0]
    at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
    at java.lang.Thread.run(Thread.java:829) ~[?:?]
2022-05-16 15:20:55 INFO  AbstractOperator:517 - Reconciliation #72(timer) Kafka(default/my-cluster): reconciled
```

Instead, when a wrong `brokers` list is provided (i.e. not existing ids), the `KafkaRebalance` custom resource moves to `NotReady` but no error logged by operator or put a condition with error in the resource status.

```shell
2022-05-16 15:23:06 INFO  KafkaRebalanceAssemblyOperator:399 - Reconciliation #76(kafkarebalance-watch) KafkaRebalance(default/my-rebalance): Rebalance action from state [New]
2022-05-16 15:23:06 INFO  KafkaRebalanceAssemblyOperator:1229 - Reconciliation #76(kafkarebalance-watch) KafkaRebalance(default/my-rebalance): Requesting Cruise Control rebalance [dryrun=true]
2022-05-16 15:23:06 INFO  CrdOperator:113 - Reconciliation #76(kafkarebalance-watch) KafkaRebalance(default/my-rebalance): Status of KafkaRebalance my-rebalance in namespace default has been updated
2022-05-16 15:23:06 INFO  KafkaRebalanceAssemblyOperator:435 - Reconciliation #76(kafkarebalance-watch) KafkaRebalance(default/my-rebalance): State updated to [NotReady] and annotation strimzi.io/rebalance is not set 
2022-05-16 15:23:06 INFO  KafkaRebalanceAssemblyOperator:399 - Reconciliation #77(kafkarebalance-watch) KafkaRebalance(default/my-rebalance): Rebalance action from state [NotReady]
2022-05-16 15:23:06 INFO  KafkaRebalanceAssemblyOperator:435 - Reconciliation #77(kafkarebalance-watch) KafkaRebalance(default/my-rebalance): State updated to [NotReady] and annotation strimzi.io/rebalance is not set 
2022-05-16 15:24:51 INFO  ClusterOperator:128 - Triggering periodic reconciliation for namespace default
2022-05-16 15:24:51 INFO  AbstractOperator:226 - Reconciliation #78(timer) Kafka(default/my-cluster): Kafka my-cluster will be checked for creation or modification
2022-05-16 15:24:51 INFO  AbstractOperator:226 - Reconciliation #79(timer) KafkaRebalance(default/my-rebalance): KafkaRebalance my-rebalance will be checked for creation or modification
2022-05-16 15:24:51 INFO  KafkaRebalanceAssemblyOperator:399 - Reconciliation #79(timer) KafkaRebalance(default/my-rebalance): Rebalance action from state [NotReady]
2022-05-16 15:24:51 INFO  KafkaRebalanceAssemblyOperator:435 - Reconciliation #79(timer) KafkaRebalance(default/my-rebalance): State updated to [NotReady] and annotation strimzi.io/rebalance is not set 
2022-05-16 15:24:51 INFO  AbstractOperator:517 - Reconciliation #79(timer) KafkaRebalance(default/my-rebalance): reconciled
2022-05-16 15:24:54 INFO  AbstractOperator:517 - Reconciliation #78(timer) Kafka(default/my-cluster): reconciled
```

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Bugfix

### Description

This PR fixes #6824.
It also change the Cruise Control API because the "brokers not exist" error coming from CC when `brokers` list contains broker ids not in the cluster, should be treated as an unrecoverable error which needs user intervention (and not like not enough data in window or proposal not ready).
Finally, the PR also adds a fix to the status condition removed reason and message when the resource is in the NotReady state (which is not related to the issue but is more general). Maybe this last point would need a better refactoring of the update status code.

### Checklist

- [x] Make sure all tests pass
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

### CODE REVIEW

**Review by ShubhamRwt — APPROVED** [review]
LGTM @ppatierno

**Review by kyguy — APPROVED** [review]
LGTM

**Review by tomncooper — APPROVED** [review]
LGTM

**Comment by ppatierno** [comment]
This PR has to be cherry-picked to the 0.29.x release branch.

**Pull request merged**
