### PR TITLE
sourcelabels line missing

### PR DESCRIPTION
**Pull request by biohazd**
sourcelabels line missing, Im not sure what it should be

### Type of change

_Select the type of your PR_

- Enhancement

### Description

sourcelabels line missing, Im not sure what it should be

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by scholzj** [comment]
@ppatierno @stanlyDoge Did you had any chance to look at this? You are the Prometheus experts.

**Comment by stanlyDoge** [comment]
Not yet :( @biohazd can you please explain, what is the issue with missing `sourcelabels`?

**Comment by biohazd** [comment]
I had to commet  out lines 26 to 34 to get it to work.  So something is wrong with that block.   I'm not sure why it fails.

**Comment by stanlyDoge** [comment]
Prometheus configuration doc says it is optional (`Brackets indicate that a parameter is optional.` https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config). 
Can you provide more details? Did you use Strimzi examples for deploying metrics? What is your k8s version? What is the Strimzi version? Do Prometheus logs say something suspicious? What are the symptoms which are you observing?

**Comment by scholzj** [comment]
@biohazd Could you please provide some more details? @stanlyDoge tried to validate it, but I guess he needs to better understand your envirionment, what versions of Strimzi, Prometheus etc. you were using and so on.

**Comment by scholzj** [comment]
Thsi PR has been discussed on the Strimzi community meeting today. Since we do not have enough information and understanding about that the problem is and when does it happen, we will close this PR. We can reopen it later if needed. Thanks.

**Pull request closed without merging**
