### PR TITLE
Clean old features from the CRD generator

### PR DESCRIPTION
**Pull request by omjikush09**
### Type of change

- Refactoring

### Description

Clean old features from the CRD generator [#issue](https://github.com/strimzi/strimzi-kafka-operator/issues/7663)

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by omjikush09** [comment]
Hi, This PR can take some as I am learning about CRD and I have my exams.. :sob:

**Comment by scholzj** [comment]
@omjikush09 This is not a critical issue, so no worries. I think the changes you did are good so far, but I think there is more stuff to remove. If you want, we can also consider doing it in smaller parts and remove it tep by step few lines in one Pr, few in another one etc.

**Review by scholzj — COMMENTED** [review]
I think there are some more places which can be cleaned up - try to look for the `crdApiVersion.compareTo` => that seems to be a good identifier for things to either remove completely or just remove the `if`.

@tombentley WDYT ... should we remove the `crdApiVersion` completely as we have only `v1` now? There might be some `v2` version in the future. But we have no idea where it will be needed. So if we keep it without using it, it might not be anyway useful in the future.

**Comment by omjikush09** [comment]
Hi, I tried to do but multiple test cases are failing. Will ping you on slack.

**Review by scholzj — COMMENTED** [review]
The `CrdGeneratorTest.java` seems to have some additional tests which would need to be updated to use the v1 API and not the v1beta1 API. You also mentioned on Slack that the custom resource sued by the test is not applicable on Kubernetes - can you please provide more details?

**Comment by omjikush09** [comment]
```The CustomResourceDefinition "examples.crdgenerator.strimzi.io" is invalid: 
* spec.validation.openAPIV3Schema.properties[alternatives].oneOf[0].items.type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[alternatives].oneOf[0].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[alternatives].oneOf[1].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[alternatives].oneOf[1].x-kubernetes-preserve-unknown-fields: Forbidden: must be false to be structural
* spec.validation.openAPIV3Schema.properties[alternatives].type: Required value: must not be empty for specified object fields
* spec.validation.openAPIV3Schema.properties[either]: Required value: because it is defined in spec.validation.openAPIV3Schema.oneOf[0].properties[either]
* spec.validation.openAPIV3Schema.properties[or]: Required value: because it is defined in spec.validation.openAPIV3Schema.oneOf[1].properties[or]
* spec.validation.openAPIV3Schema.properties[typedAlternatives].oneOf[0].properties[key2].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[typedAlternatives].oneOf[0].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[typedAlternatives].oneOf[1].properties[key1].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[typedAlternatives].oneOf[1].type: Forbidden: must be empty to be structural
* spec.validation.openAPIV3Schema.properties[typedAlternatives].type: Required value: must not be empty for specified object fields
```
Error when applying simpleTest.yaml to minikube and this CRD is generated by test

**Comment by scholzj** [comment]
I will try to have a look at it tomorrow. But I think these things are forbidden in the `v1` schema, so they can be removed.

**Comment by scholzj** [comment]
So, the `alternatives` and `typedAlternatives` ... I think those should be removed. Including all the classes it references, the annotation, the code generating the spec and docs, etc. since that should not be used anymore in the current CRD spec. I'm not entirely sure what would the problem be with the `either` and `or` fields. They should be fine and supported I think. This is also used in the `KafkaMirrorMaker` CRD, so not sure why would it not work here.

To be honest, this issue is quite complicated. And I'm not sure how much more time we will spend if we go through this the way that you run into some issues and I try to investigate it a few days later. Unfortunately, I do not have a prepared list of things that need to be removed as I would need to go through this step by step and actually remove them to figure it out. So I'm afraid I'm not sure what is the best way to proceed here.

**Comment by scholzj** [comment]
@omjikush09 So, should we close this? Or do you want to continue with it and try to proceed with removing the alternatives?

**Comment by omjikush09** [comment]
@scholzj  I tried to remove but no luck. So I think I would rollback back my last commit then we can merge it.

**Comment by scholzj** [comment]
I'm not sure if rollback really helps as it would be still incomplete. We
need to do this properly including the tests and old features etc.

**Comment by omjikush09** [comment]
Hi, @scholzj  I know it will not be complete but as you have told we complete it in multiple parts so I thought we can do it that way.
Ya if you want you can close this PR and create a new PR when the error is resolved.

**Comment by scholzj** [comment]
> Hi, @scholzj I know it will not be complete but as you have told we complete it in multiple parts so I thought we can do it that way.

We can do it in parts, but it would need to have some system. The first commit seems to remove things from the middle. Doing it in parts would be for example to have a PR which removes the alternatives part etc. -> starting from the outside and not from the middle.

So I think it is better to close it and I will try to have a more detailed look at it when I find more time. But anyway, thanks a lot for the effort you put into it!

**Pull request closed without merging**
