### PR TITLE
[ST] - Dual-stack support for Kind on TF

### PR DESCRIPTION
**Pull request by see-quick**
### Type of change

- Enhancement / new feature

### Description

This PR introduces dual-stack (IPv4/IPv6) support to our Kind cluster, allowing seamless networking transitions and operations in both IP environments. 

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by jankalinic — APPROVED** [review]

**Review by im-konge — APPROVED** [review]

**Review by henryZrncik — APPROVED** [review]

**Comment by see-quick** [comment]
The pipeline fails on an issue related to the ZooKeeper. So I think we can merge this one... :) 
```
Message: Failed to connect to Zookeeper oauth-cluster-tls-name-zookeeper-0.oauth-cluster-tls-name-zookeeper-nodes.test-suite-namespace.svc:2181,oauth-cluster-tls-name-zookeeper-1.oauth-cluster-tls-name-zookeeper-nodes.test-suite-namespace.svc:2181,oauth-cluster-tls-name-zookeeper-2.oauth-cluster-tls-name-zookeeper-nodes.test-suite-namespace.svc:2181. Connection was not ready in 300000 ms.
```

**Pull request merged**
