### PR TITLE
Add a unit test case for validateCreateBootstrapService method.

### PR DESCRIPTION
**Pull request by see-quick**
### Type of change

- Enhancement / new feature

### Description

This PR adds a unit test case for the `validateCreateBootstrapService` method. 

### Checklist

- [x] Write tests
- [x] Make sure all tests pass

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
I think you misread the code. This option is _true_ by default. The bootstrap service is always created. On `type: loadbalancer` listener, you can disable it (because LBs cost money so you have more motivation to do so ;-)).

So what the validator does is it checks that id the listener is not LB type, the `createBootstrapService` has to be true. Which I think works in the original code and you break it.

**Comment by see-quick** [comment]
> I think you misread the code. This option is _true_ by default. The bootstrap service is always created. On `type: loadbalancer` listener, you can disable it (because LBs cost money so you have more motivation to do so ;-)).
> 
> So what the validator does is it checks that id the listener is not LB type, the `createBootstrapService` has to be true. Which I think works in the original code and you break it.

I see my bad...should I at least add a unit for validation of this part `errors.add("listener " + listener.getName() + " cannot configure createBootstrapService because it is not load balancer listener");`, because I don't see that is covered.

**Review by scholzj — COMMENTED** [review]
Adding test is fine. But you should clean the unrelated changes.

**Comment by see-quick** [comment]
> Adding test is fine. But you should clean the unrelated changes.

Yes, and I have also changed the name of the PR.

**Review by scholzj — APPROVED** [review]

**Pull request merged**
