### PR TITLE
Upgrade Kafka Bridge to 0.21.0

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Task

### Description

This Pr upgrades the Kafka Bridge to the new release 0.21.0 (currently using the Release Candidate 1)

### Checklist

- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Review by ppatierno — APPROVED** [review]

**Review by sknot-rh — APPROVED** [review]

**Comment by sknot-rh** [comment]
Failed STs are not related to the changes in his PR. It failed because of the Kafka did not start successfully (e.g. `Timeout after 1320000 ms waiting for Wait for Kafka: my-cluster-972563046`)

**Pull request merged**
