### PR TITLE
Structural schema

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Bugfix

### Description

Kubernetes 1.15 introduced the idea of [structural schemas](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/) which CRDs in `apiextensions.k8s.io/v1` [started enforcing](https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#specifying-a-structural-schema).

Our schemas were not structural because the top level object lacked a `type`. This was added as a workaround for openshift 3.10-rc0 which we no longer support. So this PR adds the `type` back and also adds a tiny ST which checks the `status` of the CRD to check that kube doesn't think our CRDs are non-structural.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by tombentley** [comment]
More careful testing reveals that kubernetes v1.11 still has trouble with a top level `type` whereas v1.12 seems OK with it. So I guess we're stuck with non-structural schemas for as long as we support v1.11.

**Comment by scholzj** [comment]
Should we close this PR than @tombentley?

**Comment by ron1** [comment]
FYI, it appears issue [Allow more fields at root of CRD schema if status is enabled](https://bugzilla.redhat.com/show_bug.cgi?id=1803163) is resolved in OCP 3.11.188.

**Comment by scholzj** [comment]
@ron1 That is an interesting news. Thanks for sharing.

**Comment by scholzj** [comment]
@ron1 You are right, thanks. Unofrtunately, Kubernetes 1.11 still does not work. So we would need to limit the support for Kube 1.12+ and OpenShfit 3.11.188+

**Comment by ron1** [comment]
@scholzj I have seen other operators declare Kubernetes 1.12+ and OCP 3.11 as pre-requisites.

**Comment by scholzj** [comment]
That would be of course possible ... But it means it might cut of some users. So we should consider if it is worth it. The only actual benefit I'm aware of right now is nicer editing in OCP4 UI. Especially given that we should also think about migration to CRD v1 which are supoprted from Kube 1.16 / OCP 4.4.

**Comment by scholzj** [comment]
Closing in favour of #3653

**Pull request closed without merging**
