### PR TITLE
ST: Username longer than 64 characters

### PR DESCRIPTION
**Pull request by serrss**
### Type of change
- New ST

### Description
Added ST to check cases when openSSL can't create TLS users with username longer than 64 characters.
Conditions that are checked:
1. User with username = 65 characters
2. User with username = 64 characters
3. SCRAM_SHA user with username = 65 characters

### Checklist
- [ ] Write tests
- [ ] Make sure all tests pass

### CODE REVIEW

**Comment by serrss** [comment]
@strimzi-ci run tests testcase=UserST#testUserWithNameMoreThan64Chars

**Comment by serrss** [comment]
@Frawless This a negative case, we don't expect cluster availability for the user here. Right now and in this ST we just need to check that error was handled properly(cluster availability for the user we check via other tests in UserST). For more details about this issue, you can read #1698

**Comment by Frawless** [comment]
@serrss oh I see, in that case LGTM :)

**Comment by tombentley** [comment]
@asorokhtey @granzoto please can you review.

**Pull request merged**
