### PR TITLE
[systemtest] Update upgrade/downgrade with 0.34.0

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Enhancement

### Description

This PR updates upgrade/downgrade files with `0.34.0` after the release.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by jankalinic — APPROVED** [review]

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=all groups=olmupgrade

**Review by Frawless — APPROVED** [review]

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=all groups=olmupgrade

**Pull request merged**
