### PR TITLE
Continue refactoring of the `test` module

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Refactoring

### Description

This PR continues the cleanup and refactoring of the `test` module:
* It splits the `TestUtils` into 3 different classes:
    * `CrdUtils` class with the methods and fields for working with CRDs
    * `ReadWriteUtils` for reading and writing various files and converting them tot he right types
    * The original `TestUtils` with the rest of the methods and fields that did not fit the other classes
* It tries to consolidate the methods, remove duplicates and keep really generic shared methods
* It adds Javadocs and enables the Javadoc validation for the `test` module

There are few more TODOs -> if this PR is approved, I will open issues to track them.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
#10557 and #10556 opened for the follow-up work.

**Pull request merged**
