### PR TITLE
[ST] ConnectST: switch from (deprecated) External Config volumes to volume mounts. 

### PR DESCRIPTION
**Pull request by henryZrncik**
### Type of change

- Enhancement 

### Description

External Config for volumes is now deprecated so the test swtiches to the usage of Volumes and Volume Mounts which covers the same functionality.

### CODE REVIEW

**Comment by im-konge** [comment]
The changes look good to me. However, should we check also the deprecated way?

**Comment by henryZrncik** [comment]
Good Point, before removing I have checked presence/absence of deprecation warnings manually and as this would need another PR to remove it in version or two so I did not saw much added value in keeping it, but i can bring back one of it and assert for warning if you consider it worth of keeping.

**Review by scholzj — APPROVED** [review]

**Comment by im-konge** [comment]
> Good Point, before removing I have checked presence/absence of deprecation warnings manually and as this would need another PR to remove it in version or two so I did not saw much added value in keeping it, but i can bring back one of it and assert for warning if you consider it worth of keeping.

I mean if it's just deprecated and the values will be used, then we should check it. If it's deprecated and ignored, we don't need to check that there is some deprecation message.

**Comment by im-konge** [comment]
> It is deprecated but used if configured by users. But I'm not sure we want to have a ST for every single thing that has new and deprecated way to do things 🤷.

I didn't mean adding another test for it, just to keep it in the spec (in some way) of the Kafka CR instead of removing it (thus adding the "new way") and check both. It will not take much more execution time IMHO. But if it doesn't make sense, then I'm fine with it 🤷

**Review by see-quick — APPROVED** [review]

**Review by im-konge — APPROVED** [review]

**Pull request merged**
