### PR TITLE
[ST] Use real test execution instead of milis from epoch in collecting logs from CO

### PR DESCRIPTION
**Pull request by Frawless**
### Type of change

- Bugfix

### Description

`assertNoCoErrorsLogged()` got miliseconds since eponch instead of real test execution time in seconds. This resulted in something like that:

```
2024-02-01 08:06:05 INFO  [AbstractST:437] Search in strimzi-cluster-operator log for errors in last 1706774095840 second(s)
2024-02-01 08:07:46 DEBUG [Exec:418] Failed to exec command: 'bash -c kubectl --namespace co-namespace logs Deployment/strimzi-cluster-operator --since=1706774095840s | grep  -e Exception -e Error -e Throwable -e OOM -B 1' (return code: 1)
2024-02-01 08:07:46 DEBUG [Exec:418] ======STDERR START=======
2024-02-01 08:07:46 DEBUG [Exec:418] error: invalid argument "1706774095840s" for "--since" flag: time: invalid duration "1706774095840s"
See 'kubectl logs --help' for usage.
2024-02-01 08:07:46 DEBUG [Exec:418] ======STDERR END======
2024-02-01 08:07:46 INFO  [BaseCmdKubeClient:501] Exception not found
```

which is obviously wrong. This PR resolves that.

### Checklist

- [ ] Make sure all tests pass

### CODE REVIEW

**Comment by Frawless** [comment]
Current log from azure:
```
2024-02-01 10:14:41 [main] INFO  [AbstractST:437] Search in strimzi-cluster-operator log for errors in last 144 second(s)
2024-02-01 10:14:41 [main] INFO  [BaseCmdKubeClient:501] Exception not found
```

The value for log collector is correct.

**Review by see-quick — APPROVED** [review]

**Review by im-konge — APPROVED** [review]
LGTM, thanks :)

**Review by scholzj — APPROVED** [review]

**Pull request merged**
