### PR TITLE
Add Strimzi 0.21.1 to Upgrade STs

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Task

### Description

Add Strimzi 0.21.1 release to the Upgrade system test JSON. Also, as suggested by @Frawless, it changes from version 0.20.0 to the patch version 0.20.1.

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=upgrade

**Review by Frawless — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
