### PR TITLE
Expose REST endpoint for brokerState metric

### PR DESCRIPTION
**Pull request by tinaselenge**
### Type of change

- Enhancement / new feature

### Description

Expose REST endpoint for metric collections such as broker state. The purpose is to make the Kafka Roller aware of broker state that are not exposed via the Kafka Admin API or Kubernetes API. This could be also useful for kafka readiness probe. 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. I think this should have a proposal first to discuss how it should work and look like. Things such as used ports, technologies, how should it be secured etc.

**Comment by tinaselenge** [comment]
@scholzj Thanks for the feedback. I might have prematurely raised the PR, I should have discussed it with the team using the commit in my repo.

**Comment by scholzj** [comment]
Should we close this until the related proposals are finalized?

**Comment by tinaselenge** [comment]
I agree. Closing the issue until the [proposal](https://github.com/strimzi/proposals/pull/71) is finalised.

**Pull request closed without merging**
