### PR TITLE
feat: Switch SimpleAcl to new AclAuthorizer class

### PR DESCRIPTION
**Pull request by samuel-hawker**
Signed-off-by: Andrew Schofield <andrew_schofield@uk.ibm.com>

### Type of change

- Enhancement

### Description

Closes: #2880 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by scholzj** [comment]
@samuel-hawker You seem to be missing the CRD changes for `helm3`. I also wonder if the change for the `050-ConfigMap-strimzi-cluster-operator.yaml` should have a corresponding change in the Helm charts or whether this is just your Helm version which generates it with `|-` instead of `|`.

**Comment by scholzj** [comment]
I think it is also worth mentioning it in CHANGELOG.md.

**Comment by samuel-hawker** [comment]
Thanks Jakub, I was working on fixing this, for some reason some of the files aren't generating properly locally...


I will add to the CHANGELOG too.

**Comment by samuel-hawker** [comment]
Pushed up a changelog entry, I am not expert when it comes to ACLs, so please suggest improvement if you think of any.

**Comment by scholzj** [comment]
@strimzi-ci run tests false profile=regression testcase=io.strimzi.systemtest.security.SecurityST

**Pull request merged**
