### PR TITLE
Permit setting extra env vars through Helm for the Cluster Operator

### LINKED ISSUE #5860: Cluster operator's Kubernetes client has fixed timeout
Creating a `Service` resource in my Kubernetes cluster takes as long as 30 seconds because of a bunch of webhooks and backend calls that get made. But Strimzi's Cluster Operator has a fixed timeout of 10 seconds. As a result, the operator fails every time when it tries to create its first service, which happens to be `<cluster-name>-zookeeper-client`.

I'd like to be able to configure the timeout to a higher value. In my case, I'm using Helm to deploy and configure my Strimzi operator; I'd like to be able to set that configuration through a Helm value.

One way this might work is through environment variables. The Fabric8io Kubernetes client will obey certain environment variables, all listed [on their README](https://github.com/fabric8io/kubernetes-client/blob/v5.9.0/README.md), to configure things like timeouts.

### PR DESCRIPTION
**Pull request by spenczar**
### Type of change
Enhancement / new feature

### Description

Fixes #5860. 

Lets Helm users configure additional environment variables for the Cluster
Operator container through Helm values and templating.

The extraEnvs value takes a list of environment variables. These should be in
the form of EnvVar values, as in a Container spec, like this:

```yaml
   - name: KUBERNETES_REQUEST_TIMEOUT
     value: 60000
   - name: KUBERNETES_REQUEST_RETRIES
     value: 2
```

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] ~Write tests~ (N/A: no helm tests)
- [ ] Make sure all tests pass
- [x] Update documentation
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md
- [x] ~Supply screenshots for visual changes, such as Grafana dashboards~ (N/A: not visual)

### CODE REVIEW

**Review by scholzj — APPROVED** [review]

**Comment by spenczar** [comment]
That build failure looks real, I think I edited the wrong file. Will fix in a sec, here.

**Comment by scholzj** [comment]
Yeah, I approved it before noticing it. The changes should go to `packaging/helm-chart`. Thanks

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
@spenczar Thanks for the PR! 👍

**Comment by vweckerle** [comment]
I am not sure if I understand the comment above correctly. Is a helm values.yaml file with the following content supposed to work?
```
extraEnvs:
  - name: "JAVA_OPTS"
    value: "-Xms=256m -Xmx=256m"
```

If I try this with the 0.27.0 helm chart, I always get this error:
```
YAML parse error on strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml: error converting YAML to JSON: yaml: line 100: did not find expected key
helm.go:88: [debug] error converting YAML to JSON: yaml: line 100: did not find expected key
```

If I remove extraEnvs: or leave it empty, helm throws no errors.

Full output:
```
$ helm upgrade strimzi-kafka-operator strimzi/strimzi-kafka-operator --values values.yaml --version 0.27.0 --dry-run --debug
upgrade.go:139: [debug] preparing upgrade for strimzi-kafka-operator
Error: UPGRADE FAILED: YAML parse error on strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml: error converting YAML to JSON: yaml: line 100: did not find expected key
helm.go:88: [debug] error converting YAML to JSON: yaml: line 100: did not find expected key
YAML parse error on strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Upgrade).prepareUpgrade
	helm.sh/helm/v3/pkg/action/upgrade.go:231
helm.sh/helm/v3/pkg/action.(*Upgrade).RunWithContext
	helm.sh/helm/v3/pkg/action/upgrade.go:140
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:200
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_amd64.s:1581
UPGRADE FAILED
main.newUpgradeCmd.func2
	helm.sh/helm/v3/cmd/helm/upgrade.go:202
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:255
runtime.goexit
	runtime/asm_amd64.s:1581
```

Full values.yaml:
```
namespace: "strimzi-kafka-operator"
watchAnyNamespace: "true"
resources:
  requests:
    memory: "512Mi"
  limits:
    memory: "512Mi"
extraEnvs:
  - name: "JAVA_OPTS"
    value: "-Xms=256m -Xmx=256m"
```

Thanks!

**Comment by spenczar** [comment]
Well, that's embarrassing. `toYaml` doesn't work there at all, so this implementation is just broken - I'm able to reproduce the same error as you. Sorry and thanks for pointing that out @vweckerle. I'll make a follow-up issue.

I am puzzled that I didn't see this when I was testing the change, but I was working on it with a system that wrapped a lot of this stuff behind many layers of indirection, so maybe I had a different Helm version, or something. Regardless - it would also be nice to have automated tests that `helm template` works.

**Comment by spenczar** [comment]
I've opened  #6145 for this.

**Pull request merged**
