### PR TITLE
Update bridge dashboard with new related metrics prefix

### PR DESCRIPTION
**Pull request by ppatierno**
Signed-off-by: Paolo Patierno <ppatierno@live.com>

### Type of change

- Refactoring

### Description

This PR updates the bridge Grafana dashboard with the new `strimzi_bridge_` prefix used for the bridge metrics.
It's related to https://github.com/strimzi/strimzi-kafka-bridge/pull/450.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by ppatierno** [comment]
This PR cannot be merged until a new bridge 0.17.1 is released with the changed metrics prefix.

**Comment by tombentley** [comment]
@samuel-hawker I agree about screenshots. Might be an idea to add it to the PR template that for metrics changes a screenshot should be included.

**Comment by ppatierno** [comment]
I don't think that this PR needs screenshots. It's just a metrics renaming stuff but the dashboard itself is the same.
It comes from the already merged https://github.com/strimzi/strimzi-kafka-operator/pull/3265 where there are the screenshots.

**Comment by samuel-hawker** [comment]
> I don't think that this PR needs screenshots. 

I agree with this Paolo, but in general more complicated contributions do make a reviewer wish there was a screenshot

**Comment by ppatierno** [comment]
Absolutely. I agree with having screenshots on monitoring related PR (if needed) as I had for the one which added bridge metrics.

**Pull request merged**
