### PR TITLE
feat: Add DNS generator

### PR DESCRIPTION
**Pull request by samuel-hawker**
Add separate class for dns name generator
Rename a few things in abstract model and improve null
checking at boundaries

Signed-off-by: Samuel Hawker <samuel.hawker@ibm.com>

### Type of change

_Select the type of your PR_

- Bugfix
- Enhancement / new feature
- Refactoring
- Documentation

### Description

_Please describe your pull request_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
I think it would be great to open more PRs next time and not mix unrelated changes into one PR. It is not really clear to me if the changes to `getRequiredEnvVars` or `OrderedProperties` are committed by mistake. It would also improve the traceability of the changes. It would also make reviewing much easier since suddenly the file with only the `getRequiredEnvVars` would not mix with those with the DNS name change.

**Comment by samuel-hawker** [comment]
Sorry didn't mean to mix them in, I can pull the unrelated changes out if you want?

**Comment by scholzj** [comment]
No, you can keep it as it is here. It is not so big PR ... just something we can maybe avoid in the future ;-).

**Review by ppatierno — APPROVED** [review]
LGTM even if there is still this kind of mixing using a DnsGenerator instance or using a static method that at the end creates an instance internally and then calls the non-static method.

**Comment by samuel-hawker** [comment]
So the reasoning behind the field in this one is because multiple of the methods share the same common parameters, not to mention they are used multiple times in the same. place in the CA generation.

**Comment by ppatierno** [comment]
@samuel-hawker yeah I got this one. Anyway I am fine with this PR.

**Pull request merged**
