### PR TITLE
Issue-766: Updated reconciliation interval and zk session timeout default value

### PR DESCRIPTION
**Pull request by echernous**
### Type of change

- Enhancement
- Documentation

### Description

https://github.com/strimzi/strimzi-kafka-operator/issues/766
Synced zk session timeout and reconciliation interval default values for UO and TO

### Checklist

- [ ] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. We were discussing this issue on the community call today and the outcome was that the recocniliation interval as 120s is ok. But the Zookeeper timeout should be 18s instead of 20 since that is what Kafka is using. Could you please update it? Thanks.

**Review by scholzj — COMMENTED** [review]
LGTM assuming the tests pass. Maybe you can add some note about the changed defaults to https://github.com/strimzi/strimzi-kafka-operator/blob/main/CHANGELOG.md?

**Review by kyguy — APPROVED** [review]

**Comment by echernous** [comment]
Hey @scholzj, thanks for the review! I will add a changelog note shortly

**Review by scholzj — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Comment by scholzj** [comment]
@echernous When running the system tests, it seems that the `CruiseControlApiST.testCruiseControlBasicAPIRequests` test is failing. I first thought that it was just some flaky. But I already restarted it 3 times, so I looked at the test. It seems that it waits for 1 minute for some topics to appear. And I think that 1 minute might not be enough anymore because you increased the timeout for the TO reconciliation. Can you maybe look at it and see if increasing the timeout helps?

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
