### PR TITLE
Remove stability counter in PodUtils

### PR DESCRIPTION
**Pull request by see-quick**
Signed-off-by: see-quick <maros.orsak159@gmail.com>

### Type of change

- Enhancement / new feature
- Refactoring

### Description

This PR removes stability counter inside our PodUtils. I have tested this on minikube and cluster and it seems everything works without any issues. 

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by im-konge — APPROVED** [review]

**Review by Frawless — APPROVED** [review]
LGTM, the main reason for this is to save a lot of time from the test execution. As long as the tests will be stable, the change should be fine.

**Review by im-konge — APPROVED** [review]

**Pull request merged**
