### PR TITLE
[DOC] Kafka Exporter link updates

### PR DESCRIPTION
**Pull request by PaulRMellor**
Signed-off-by: prmellor <pmellor@redhat.com>
**Documentation**

Updates to links for _Configuring Kafka Exporter_ section in the _Deploying_ doc.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by PaulRMellor** [comment]
@scholzj I've been asked about replacing the example `image` with _working_ image name.

**Comment by scholzj** [comment]
@PaulRMellor I think there is a reason for having an _example_ image name there. The real image name does not need to be specified there, so having it there would be misleading. So if the example image name is confusing, I guess the alternative would be something what is a bit more clear placeholder.

**Comment by PaulRMellor** [comment]
> @PaulRMellor I think there is a reason for having an _example_ image name there. The real image name does not need to be specified there, so having it there would be misleading. So if the example image name is confusing, I guess the alternative would be something what is a bit more clear placeholder.

@scholzj - thanks. Maybe we could change to something like _my-registry.io/my-org/my-exporter-cluster:latest_
(`my-org/my-image:latest` is used in a few places)

**Comment by scholzj** [comment]
@PaulRMellor `my-registry.io/my-org/my-exporter-cluster:latest` would be totally fine for me.

**Review by scholzj — APPROVED** [review]

**Review by laidan6000 — APPROVED** [review]

**Pull request merged**
