### PR TITLE
feat: Cleanup kafka assembly futures (Part 1)

### PR DESCRIPTION
**Pull request by samuel-hawker**
### Type of change
- Refactoring

### Description

Cleanup assembly futures to make them more readable
remove unneeded promises, use compose success/failure handler where
appropriate

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by samuel-hawker** [comment]
In this PR I used the 
`Future.compose(successHandler, failureHandler)` pattern to clean up a lot of our manual result checks, as well as removed promises where future chaining was appropriate
The if checks have also been inverted to remove readability, let me know if you disagree with any of these changes, i know the git diffs can be hard to read.

**Comment by scholzj** [comment]
We need to better synchronise on what are you refactoring. Because I spent the last two weeks changing this as part of the improved listeners configuration. :-(

**Comment by samuel-hawker** [comment]
Hey Jakub, happy to park this till after you're done? Or revert the changes to the pieces you're touching.
Never meant to be a thorn in your side!
We can chat about this today?

**Comment by samuel-hawker** [comment]
Closing to rework this.

**Pull request closed without merging**
