### PR TITLE
Delete unused StatefulSetDiff class which has been replaced

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

It seems that some time ago the class `StatefulSetDiff`has been moved into `ResourceOperatorSupplier`. However, the old class was renamed and still used only in tests. This PR removes the old unused class to avoid any confusions. The test is kept to test the new class.

### CODE REVIEW

**Comment by tombentley** [comment]
Why was it copied into ResourceOperatorSupplier? They're completely unrelated classes AFAICS. If anything we should get rid of the member class and keep the top level one, no?

**Comment by scholzj** [comment]
I don't know, I wondered about that as well ... but I thought that you did it when you created the `ResourceOperatorSupplier` so there must be some reason :-D. But I can close this PR and open a new one to change it the other way as well.

**Comment by tombentley** [comment]
`git annotate` say you did it, but maybe it was a mistaken drag-and-drop or similar. In any case, I think a different PR is needed.

**Comment by scholzj** [comment]
Hmm ... ok :-o. That must have been some mistake while moving the files here and there when creating the `operator-common` module. I will close tis and open a new one to fix it the other way around. Thanks.

**Comment by scholzj** [comment]
@tombentley I open a new PR #849 for this.

**Pull request closed without merging**
