### PR TITLE
Bump Vert.x 4.2.5

### PR DESCRIPTION
**Pull request by ppatierno**
Bumping Vert.x to 4.2.5

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
LGTM assuming it works.

**Comment by ppatierno** [comment]
@scholzj as already done for the bridge, I needed to bump Netty version to 4.1.74.Final as well due to this PR in Vert.x Web using a new field in Netty.

https://github.com/vert-x3/vertx-web/pull/2122/files
https://github.com/netty/netty/blob/netty-4.1.74.Final/codec-http/src/main/java/io/netty/handler/codec/http/HttpHeaderNames.java#L75

**Pull request merged**
