### PR TITLE
Chores: bump up f8 dep

### PR DESCRIPTION
**Pull request by stanlyDoge**
Signed-off-by: Stanislav Knot <sknot@redhat.com>

### Type of change
- chores

### Description
Upgrade fabric8 dependency 4.10.x -> 4.11.x

### Checklist
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests

**Comment by Frawless** [comment]
Regarding the regression failures:
Most of the failures were already resolved at https://github.com/strimzi/strimzi-kafka-operator/pull/3531 so it should work after rebase. I suggested to Standa to run `RollingUpdateST.testExternalLoggingChangeTriggerRollingUpdate` just to double check if it's test issue or fabric8. Otherwise LGTM.

**Review by scholzj — APPROVED** [review]

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests

**Comment by im-konge** [comment]
@strimzi-ci run tests

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests false profile=acceptance io.strimzi.systemtest.metrics.MetricsST#testKafkaBrokersCount

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests false profile=acceptance io.strimzi.systemtest.metrics.MetricsST#testKafkaBrokersCount

**Comment by scholzj** [comment]
@strimzi-ci run tests false profile=acceptance testcase=io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testScramShaAuthWithWeirdUsername,io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testTlsAuthWithWeirdUsername,io.strimzi.systemtest.kafka.ListenersST#testCustomSoloCertificatesForRoute,io.strimzi.systemtest.connect.ConnectS2IST#testKafkaConnectorWithConnectS2IAndConnectWithSameName,io.strimzi.systemtest.connect.ConnectST#testKafkaConnectAndConnectorFileSinkPlugin

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests false profile=acceptance testcase=io.strimzi.systemtest.bridge.HttpBridgeKafkaExternalListenersST#testScramShaAuthWithWeirdUsername,io.strimzi.systemtest.kafka.ListenersST#testCustomSoloCertificatesForRoute,io.strimzi.systemtest.connect.ConnectS2IST#testKafkaConnectorWithConnectS2IAndConnectWithSameName

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests false profile=acceptance testcase=io.strimzi.systemtest.kafka.ListenersST#testCustomSoloCertificatesForRoute,io.strimzi.systemtest.connect.ConnectS2IST#testKafkaConnectorWithConnectS2IAndConnectWithSameName

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests false profile=acceptance testcase=io.strimzi.systemtest.kafka.ListenersST#testCustomSoloCertificatesForRoute,io.strimzi.systemtest.connect.ConnectS2IST#testKafkaConnectorWithConnectS2IAndConnectWithSameName

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests

**Comment by rohanKanojia** [comment]
Hi guys, How much time do these tests usually take to complete? I see two workflows are already failing :cold_sweat: . Are these related to fabric8?
```
[ERROR] io.strimzi.systemtest.connect.ConnectST.testHostAliases
[ERROR]   Run 1: ConnectST.testHostAliases:1139 » KubeCluster `kubectl --namespace connect-clus...
[ERROR]   Run 2: ConnectST.testHostAliases:1139 » KubeCluster `kubectl --namespace connect-clus...
[ERROR]   Run 3: ConnectST.testHostAliases:1139 » KubeCluster `kubectl --namespace connect-clus...
[INFO] 
[INFO] 
[ERROR] Tests run: 29, Failures: 0, Errors: 1, Skipped: 3

[ERROR] io.strimzi.systemtest.mirrormaker.MirrorMaker2ST.testHostAliases
[ERROR]   Run 1: MirrorMaker2ST.testHostAliases:806 » KubeCluster `kubectl --namespace mirrorma...
[ERROR]   Run 2: MirrorMaker2ST.testHostAliases:806 » KubeCluster `kubectl --namespace mirrorma...
[ERROR]   Run 3: MirrorMaker2ST.testHostAliases:806 » KubeCluster `kubectl --namespace mirrorma...
[INFO] 
[ERROR] io.strimzi.systemtest.mirrormaker.MirrorMakerST.testHostAliases
[ERROR]   Run 1: MirrorMakerST.testHostAliases:741 » KubeCluster `kubectl --namespace mm-cluste...
[ERROR]   Run 2: MirrorMakerST.testHostAliases:741 » KubeCluster `kubectl --namespace mm-cluste...
[ERROR]   Run 3: MirrorMakerST.testHostAliases:741 » KubeCluster `kubectl --namespace mm-cluste.
```

**Comment by stanlyDoge** [comment]
AFAIK these tests are not related to f8 but to Azure environment. @Frawless ^

**Comment by scholzj** [comment]
@stanlyDoge Yeah, the host alias tests should be fixed in #3737

**Comment by scholzj** [comment]
@strimzi/maintainers The test look good and the code to me as well. Could you please review so that we can move forward with this and merge it?

**Review by tombentley — APPROVED** [review]

**Pull request merged**
