### PR TITLE
Bump Vert.x 4.5.6

### PR DESCRIPTION
**Pull request by ppatierno**
Trivial PR to bump to Vert.x 4.5.6

### CODE REVIEW

**Review by scholzj — CHANGES_REQUESTED** [review]
You should probably sync also Netty & co?

**Comment by ppatierno** [comment]
> You should probably sync also Netty & co?

Done. It seems to be only Netty.

**Review by see-quick — APPROVED** [review]

**Review by scholzj — APPROVED** [review]
LGTM assuming the tests pass.

**Pull request merged**
