### PR TITLE
proper link to examples/metrics

### PR DESCRIPTION
**Pull request by tringuyen-yw**
### Type of change

- Documentation

### Description

Fix the quote `examples/metrics` to a proprer clickable link.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ X] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
I'm not sure there is a single link which would work in every place, or? How will the link to `/examples/metrics` work for example on the website or when the user unpacks it from the release ZIP?

Maybe using something like this could work:
```
link:https://github.com/strimzi/strimzi-kafka-operator/tree/{GithubVersion}/examples/metrics[examples/metrics]
```

**Comment by scholzj** [comment]
@tringuyen-yw Also, can you please fix the DCO signoff? The instructions should be under the _Details_ link next to the DCO status.

**Comment by tringuyen-yw** [comment]
@scholzj the link `/examples/metrics` refers to the root of the project. When Asciidoc builds the HTML, it would generate the proprer link. On [Github, working branch](https://github.com/YoppWorks/strimzi-kafka-operator/blob/Tri_Strimzi-doc-fix-link-examples-metrics/documentation/modules/metrics/ref_metrics-config-files.adoc), the link is working OK.

But to play it safe, we can of course set the absolute link. What does `{GithubVersion}` expands to? 

Will make change now and do the DCO signoff

**Comment by tringuyen-yw** [comment]
@scholzj Committed the link you suggested 
You can check on the working branch that the link to `examples/metrics` is now broken because of the `{GithubVersion}` attributed which is not rendered: [ref_metrics-config-files.adoc](https://github.com/YoppWorks/strimzi-kafka-operator/blob/Tri_Strimzi-doc-fix-link-examples-metrics/documentation/modules/metrics/ref_metrics-config-files.adoc)

Would you be OK if I hardcode the link to `tree/main` instead of `tree/{GithubVersion}`

```
link:https://github.com/strimzi/strimzi-kafka-operator/tree/main/examples/metrics[examples/metrics]
```
This would make a link always pointing to `master` [examples/metrics](https://github.com/strimzi/strimzi-kafka-operator/tree/main/examples/metrics)

**Comment by scholzj** [comment]
> You can check on the working branch that the link to examples/metrics is now broken because of the {GithubVersion} attributed which is not rendered: ref_metrics-config-files.adoc

When the documentation is built, the argument with the `GithubVersion` is passed into it. So when you do `make docu_html`, you should see the linked rendered to either point to the `main` branch or in case of releases it will point to the right tag (this is important, because the current `main` branch metric examples would not work with older Strimzi versions etc.)

If you search the `documentation` folder, there should be a file `attributes.adoc`. Maybe you can also add the `GithubVersion` attribute there with the `main` as a default value. That should make sure that in case you do not use one of the `make` command to build the docs, you get at least to the `main` branch. You can just add there something like:
```
:GithubVersion: main
```

**Review by scholzj — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Review by tombentley — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR @tringuyen-yw

**Pull request merged**
