### PR TITLE
minor copy edits

### PR DESCRIPTION
**Pull request by joaedwar**
### Type of change

_Select the type of your PR_

- Documentation

### Description

Minor copy edits for docs

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by PaulRMellor — APPROVED** [review]

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
@joaedwar Could you please fix the DCO signoff? The instructions should be under the _Details_ link next to the _DCO_ status.

**Review by ppatierno — APPROVED** [review]

**Review by sknot-rh — APPROVED** [review]

**Comment by scholzj** [comment]
@joaedwar Could you please fix the DCO? We cannot merge it without it. The instructions should be under the Details link next to the DCO status.

**Comment by PaulRMellor** [comment]
Please cherry-pick to 0.26 when merged.

**Comment by scholzj** [comment]
@PaulRMellor The DCO needs to be fixed first

**Pull request merged**
