### PR TITLE
Update ADOPTERS.md

### PR DESCRIPTION
**Pull request by tym83**
Adding Ænix case in adopters' list

### Type of change

_Select the type of your PR_

- Documentation

### Description

Add new case in adopters file

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md
- [x] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by ppatierno — APPROVED** [review]
That's cool! Thanks for the PR!
Do you think you would be interested to be on the Strimzi website as well?
You could open a PR with your logo. This is an example of PR for doing so https://github.com/strimzi/strimzi.github.io/pull/435

**Review by scholzj — APPROVED** [review]
Thanks @tym83

**Comment by tym83** [comment]
> That's cool! Thanks for the PR! Do you think you would be interested to be on the Strimzi website as well? You could open a PR with your logo. This is an example of PR for doing so [strimzi/strimzi.github.io#435](https://github.com/strimzi/strimzi.github.io/pull/435)

Yes, we are interested in that:) And by the way, we make "Technical partners" page on our website and would to ask you if you don't mind to put your logo and link there too?

**Comment by ppatierno** [comment]
> Yes, we are interested in that:) And by the way, we make "Technical partners" page on our website and would to ask you if you don't mind to put your logo and link there too?

On this front I don't know because the Strimzi project is part of the CNCF foundation and not sure about the legal implications of doing that. I can ask and let you know if you want. @scholzj wdyt?

**Comment by scholzj** [comment]
Nobody asked that before. But I guess why not. Just keep in mind that we are just an open-source community, so not really a Technical partner in some business sense. So I think we just need to make sure it is not confusing.

**Pull request merged**
