### PR TITLE
Add non-regression profile

### PR DESCRIPTION
**Pull request by see-quick**
Signed-off-by: see-quick <maros.orsak159@gmail.com>

### Type of change

- Enhancement / new feature

### Description

This PR adds a non-regression profile, which complements our regression (i.e., seven jobs for Kafka, Security Oauth etc.). 

Currently non-regression pipeline contains following test suites:
```java
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.security.custom.CustomCaST
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.bridge.HttpBridgeCorsST
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.utils.KafkaVersionUtilsTest
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.kafka.KafkaVersionsST
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.kafka.QuotasST
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.specific.SpecificIsolatedST
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.specific.ClusterOperationIsolatedST
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.operators.topic.TopicScalabilityIsolatedST
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.operators.NamespaceDeletionRecoveryIsolatedST
```
but it should 
```java
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.specific.SpecificIsolatedST
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.specific.ClusterOperationIsolatedST
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.operators.topic.TopicScalabilityIsolatedST
2023-01-19 11:41:15 [main] INFO  [TestExecutionListener:55] -> io.strimzi.systemtest.operators.NamespaceDeletionRecoveryIsolatedST
```
and this is resolved in https://github.com/strimzi/strimzi-kafka-operator/pull/7939. 

### Checklist

- [ ] Make sure all tests pass

### CODE REVIEW

**Comment by im-konge** [comment]
`TopicScalabilityIsolatedST` and `KafkaVersionsST` shouldn't be there

`KafkaVersionsST` is part of the kafka regression pipeline
`TopicScalabilityIsolatedST` should not be run on the AZP, I already had an attempt to add scalability pipeline, but Azure machines are not big enough to actually handle all those topics (or users for user scalability)

**Comment by scholzj** [comment]
As I said offline ... I think it would be good to start by explaining why are these not part / should not be part of the regression pipeline. We are not using enough of the pipelines we have, so not sure adding yet another pipeline helps. The idea of having something called `non-regression` also seems quite weird - it does not make much sense to me.

**Comment by see-quick** [comment]
> The idea of having something called non-regression also seems quite weird - it does not make much sense to me.

Well, the motivation behind it is to group all test cases which should not be in the regression, such as Scalability, Recovery etc. Currently, I have changed it to add only the profile.

**Comment by scholzj** [comment]
> Well, the motivation behind it is to group all test cases which should not be in the regression, such as Scalability, Recovery etc. Currently, I have changed it to add only the profile.

Yeah, but I think the question is why are they not in regression.

**Pull request closed without merging**
