### PR TITLE
Fix `KafkaRebalanceAssemblyOperator` to not ignore exception coming from Cruise Control

### LINKED ISSUE #10631: Remove-brokers rebalancing seems to get stuck by race condition
When un-empty nodes are scaled down, the scale-down is blocked ad the nodes need to be first cleaned up for example using the _remove-brokers_ feature in Cruise Control. Once the scaled-down nodes are empty, CO will execute the scale-down and delete them. But it seems that there is a space for a race condition between the `KafkaAssemblyOperator` and `KafkaRebalanceAssemblyOperator`:
* The _remove brokers_ rebalance is ongoing and `KafkaRebaanceAssemblyOperator` marks the `KafkaRebalance` resource as `Rebalancing` and periodically (every 2 minutes) checks the progress
* `KafkaAssemblyOperator` sees that the nodes are already empty and proceeds to scale-down the broker and roll Cruise Control with the new cluster configuration
* Later (after the CC is rolled) the `KafkaRebalanceAssemblyOperator` starts another reconciliation round. But it seems that:
  * Cruise Control does not like the request anymore and throws exception:
    ```
    com.linkedin.kafka.cruisecontrol.exception.KafkaCruiseControlException: java.lang.IllegalArgumentException: Broker 14 does not exist.
    ```
  * The `KafkaRebalanceAssemblyOperator` tries to recreate it and seems to get stuck:
    ```
    colog | grep "#313(timer)"
    2024-09-23 21:13:37 INFO  AbstractOperator:266 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): KafkaRebalance my-cluster-auto-rebalancing-remove-brokers will be checked for creation or modification
    2024-09-23 21:13:37 INFO  KafkaRebalanceAssemblyOperator:317 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): Rebalance action is performed and KafkaRebalance resource is currently in [Rebalancing] state
    2024-09-23 21:13:37 INFO  KafkaRebalanceAssemblyOperator:854 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): Getting Cruise Control rebalance user task status
    2024-09-23 21:13:37 WARN  KafkaRebalanceAssemblyOperator:863 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): User task 670c1383-aa04-4979-8cc6-41fe9f69efce not found, going to generate a new proposal
    2024-09-23 21:13:37 INFO  KafkaRebalanceAssemblyOperator:1113 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): Requesting Cruise Control rebalance [dryrun=true]
    2024-09-23 21:14:37 INFO  AbstractOperator:401 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): Reconciliation is in progress
    2024-09-23 21:15:37 INFO  AbstractOperator:401 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): Reconciliation is in progress
    2024-09-23 21:16:37 INFO  AbstractOperator:401 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): Reconciliation is in progress
    2024-09-23 21:17:37 INFO  AbstractOperator:401 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): Reconciliation is in progress
    2024-09-23 21:18:37 INFO  AbstractOperator:401 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): Reconciliation is in progress
    2024-09-23 21:19:37 INFO  AbstractOperator:401 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): Reconciliation is in progress
    2024-09-23 21:20:37 INFO  AbstractOperator:401 - Reconciliation #313(timer) KafkaRebalance(myproject/my-cluster-auto-rebalancing-remove-brokers): Reconciliation is in progress
    ```

### PR DESCRIPTION
**Pull request by ShubhamRwt**
### Type of change

This PR fixes #10631. Now the KafkaRebalanceAssemblyOperator doesn't ignore the Illegal argument excepts which comes from Cruise Control and move the KafkaRebalance to `NotReady` in case any IllegalArgumentExceptions occurs

- Bugfix
- Enhancement / new feature
- Refactoring
- Documentation

### Description

_Please describe your pull request_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
I'm not sure I follow the changes, that is probably more something for @ppatierno. But should there be some unit tests to check what you describe? You just changed some unit tests where reconciliation was failing to succeeding. It is not clear to me why. But none seems to test the situation I had where the reconciliation was stuck.

**Comment by ppatierno** [comment]
@scholzj I had an offline conversation with @ShubhamRwt about this and right now this is the best solution to fix that issue. Right now errors coming from CC are not handled pretty well. Some of them are "translated" into actual responses (i.e. the not enough data in window) to avoid showing errors to users and putting the KR in a "NotReady" state but showing a "PendingProposal" (because that's what the error means).
Said that, in this case we hava an actual error but failing the future doesn't pop up into the chain of calls moving the resource to "NotReady" so we decided to go this way for now in order to have this fix soon and also @see-quick tests to pass in relation to the stuck situation you see.
After this, I will try to revisit the way we handle CC errors to improve it, but it's better doing that later imho.

**Comment by scholzj** [comment]
TBH, I do bot understand the code here very well. So my main issue was that
it does not look anything like what the PR name/description suggests.

So, maybe the PR is good and the explanation of what it does needs to be
better? I don't know, you should be better placed to decide that.

**Comment by ppatierno** [comment]
I went deeper in debugging the issue and I found the related problem which is about a "never ending" reconciliation keeping the `Rebalancing` state on the `KafkaRebalance` and of course not leaving the lock for the next reconciliation.
I will open a PR soon with the proposed fix. Then I guess this one could be closed.

**Comment by ppatierno** [comment]
After further investigation I found the root cause of the issue and fixed it via #10717.
We can close this one when #10717 is merged.

**Comment by scholzj** [comment]
If #10717 replaces this you should probably close it right away to avoid any confusions?

**Pull request closed without merging**
