### PR TITLE
[systemtest][cleanup] Change recovery timeouts, create some connector methods

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Enhancement

### Description

In this PR I'm gonna do the cleanup of our system tests. After discussion with @Frawless I left some timeouts without change, so I took look at it. When I was going through the tests, I found some things that we can change/do different way. So I done this:

- moved `deleteConsumer(...)` from `HttpBridgeBaseST` to `BridgeUtils` as I think that all these methods should be together.
- created methods for Connector config -> I added wait for Connector config change (and changed it in tests) and add method for getting the Connector config
- add constant for recovery timeout and changed it in tests
- changed name of `HttpBridgeCors` to `HttpBridgeCorsST` -> to match one pattern
- fix typo in comment
- add constant for medium poll interval
- fix inline

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=regression testcase=RecoveryST, ConnectST#testKafkaConnectorWithConnectAndConnectS2IWithSameName, ConnectS2IST#testDeployS2IAndKafkaConnectorWithMongoDBPlugin+testKafkaConnectorWithConnectS2IAndConnectWithSameName, HttpBridge*ST

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=regression testcase=ConnectST#testKafkaConnectorWithConnectAndConnectS2IWithSameName,ConnectS2IST#testDeployS2IAndKafkaConnectorWithMongoDBPlugin+testKafkaConnectorWithConnectS2IAndConnectWithSameName,HttpBridge*ST

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests test_only profile=regression testcase=rollingupdate.*ST,SecurityST

**Comment by im-konge** [comment]
@strimzi-ci run tests true profile=regression testcase=io.strimzi.systemtest.rollingupdate.KafkaRollerST#testKafkaRollsWhenTopicIsUnderReplicated

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=regression testcase=KafkaRollerST

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=regression testcase=KafkaRollerST

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=regression testcase=KafkaRollerST

**Pull request merged**
