### PR TITLE
Add current Raft state metric to the exported metrics

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

This PR adds the _current raft state_ metric to the exported metrics. It lists the state of the Kafka node: leader, observer, follower etc. which seems like it might be useful.

### Checklist

- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Comment by scholzj** [comment]
@ppatierno This seemed useful to me. WDYT?

**Review by ppatierno — APPROVED** [review]
Yes I think it's useful thanks.
It would be also interesting to have it reflected on the Grafana dashboard.
See here for example, https://www.kineticedge.io/blog/kafka-raft/, the "Node State" table looks useful to me.

**Review by see-quick — APPROVED** [review]

**Comment by scholzj** [comment]
@ppatierno Yeah, that would make sense. I opened #10533 to add it to Grafana as well.

**Comment by ppatierno** [comment]
> @ppatierno Yeah, that would make sense. I opened https://github.com/strimzi/strimzi-kafka-operator/pull/10533 to add it to Grafana as well.

@scholzj I guess you meant issue #10538 :-)

**Comment by scholzj** [comment]
Yeah, sorry 🤦

**Pull request merged**
