### PR TITLE
Adding wildcard to jar names used in image scripts

### PR DESCRIPTION
**Pull request by kyguy**
### Type of change

_Select the type of your PR_
- Refactoring

### Description
Makes image scripts more flexible for handling jar names with specific version suffixes

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by scholzj** [comment]
Do you need this in 0.14.0?

**Comment by kyguy** [comment]
I don't need them, just nice to have. I can get by without them here in 0.14.0

**Comment by scholzj** [comment]
I do not think it is guaranteed. We just have to be careful and not name anything else starting with `trasing-agent` etc. And hope nobody else creates such JAR which we would for some reason pull. So in most cases it is probably reasonable enough, but not guaranteed.

**Comment by ppatierno** [comment]
what's the advantage that we take on doing this? we are naming the agents with specific names, without any version in the appendix, or?

**Comment by kyguy** [comment]
Yes, currently we remove the versioned suffixes from the jar names when we copy them from their source directories [1]. This would be a step toward retaining the versioned suffixes in the jar names which would give us the advantage of being able to determine the jar versions in an image at a glance.

[1] https://github.com/strimzi/strimzi-kafka-operator/blob/master/docker-images/kafka/Makefile#L21

**Comment by tombentley** [comment]
@kyguy I don't recall if I did that renaming because I encountered the problem of 0 matches, or whether I did it for consistency with the other jars in `lib`. I know I've had issues with globs not matching anything. but it might not have been here. I wonder if `shopt -s failglob` would help... I suppose not because the script is not `set -e`. In any case I'm happy enough for this to be merged.

**Comment by kyguy** [comment]
@tombentley +1. For 0 matches, the script continues even with errors from `shopt -s failglob` and `ls` unless we include `set -e` in the script. For > 1 matches, the script appears to continue either way, as the command completes successfully, listing the > 1 matches.

**Comment by scholzj** [comment]
@tombentley Is this something what can be merged? Or is the 0 or >1 matches a concern?

**Comment by tombentley** [comment]
After discussing it with @kyguy I'm happy for this to be merged.

**Pull request merged**
