### PR TITLE
ST: add tests for bridge periodic reconciliation

### PR DESCRIPTION
**Pull request by Frawless**
### Type of change

- Enhancement / new feature

### Description

Add new system tests, which cover Bridge periodic reconciliation.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass

### CODE REVIEW

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=bridge

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=bridge

**Comment by kornys** [comment]
@strimzi-ci nebehej testy :-D

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=RecoveryST

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=bridge testcase=RecoveryST

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=bridge testcase=RecoveryST

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=bridge testcase=RecoveryST

**Comment by Frawless** [comment]
I am not sure why Jenkins didn't add results from the test run, but all tests are green now.

**Pull request merged**
