### PR TITLE
Retire the log-dump wrapper script and related ST as it doesn't seem to be useful

### PR DESCRIPTION
**Pull request by fvaleri**

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
Thanks.

**Review by ppatierno — APPROVED** [review]

**Review by im-konge — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Comment by scholzj** [comment]
@fvaleri Can you rebase it, please? I think @im-konge's PR caused some conflicts.

**Pull request merged**
