### PR TITLE
fix: Mock Kube deployment patcher handle zero replicas

### PR DESCRIPTION
**Pull request by samuel-hawker**
In cases where the deployment is initialized with zero
replicas NPEs can be triggered from a null lookup in the
map. Avoid this by initializing an empty list in the map
if not set

Signed-off-by: Samuel Hawker <samuel.hawker@ibm.com>

### Type of change

_Select the type of your PR_

- Bugfix
- Enhancement / new feature
- Refactoring
- Documentation

### Description

_Please describe your pull request_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.ConnectST#testKafkaConnectWithFileSinkPlugin

**Comment by samuel-hawker** [comment]
@tombentley good catch! We were deleting a 0 replica deployment and never increased it so hadn't thought to make it modifiable.
I have added another commit to change this.

**Comment by scholzj** [comment]
@samuel-hawker There seems to be some checkstyle issue which crashed the build. Can you have a look at it?

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
