### PR TITLE
ST: Add some new tests cases

### PR DESCRIPTION
**Pull request by Frawless**
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

### Type of change

- Enhancement / new feature

### Description

This PR add test cases which covers the following PR:
https://github.com/strimzi/strimzi-kafka-operator/pull/2337 - Add discovery labels and annotations
https://github.com/strimzi/strimzi-kafka-operator/pull/2564 - CO validation for  cluster size

### Checklist

- [x] Write tests
- [x] Make sure all tests pass

### CODE REVIEW

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=KafkaST#testSendMessagesPlainAnonymous+testSendMessagesPlainScramSha+testSendMessagesTlsAuthenticated+testKafkaOffsetsReplicationFactorHigherThanReplicas,HttpBridgeST test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=KafkaST#testSendMessagesPlainAnonymous+testSendMessagesPlainScramSha+testSendMessagesTlsAuthenticated+testKafkaOffsetsReplicationFactorHigherThanReplicas,HttpBridgeST test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=KafkaST#testSendMessagesPlainAnonymous+testSendMessagesPlainScramSha+testSendMessagesTlsAuthenticated+testKafkaOffsetsReplicationFactorHigherThanReplicas,HttpBridgeST test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.KafkaST#testSendMessagesPlainAnonymous test_only

**Comment by Frawless** [comment]
@ppatierno could you review this please?

**Comment by Frawless** [comment]
Cherry-pick to `release-0.17.x` please

**Comment by ppatierno** [comment]
@Frawless done!

**Pull request merged**
