### PR TITLE
Updated helm-unittest version for s390x

### PR DESCRIPTION
**Pull request by dandotimujahid**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

_Updated helm-unittest version to 0.6.3 for s390x as binaries are available for ss390x since v0.6.2_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by dandotimujahid** [comment]
Is it ok to update the helm-unittest version globally for all the archs? In the current PR, helm-unittest version is updated only for s390x as binary is available for s390x since version v0.6.2.

**Comment by im-konge** [comment]
Hi @dandotimujahid , I think that you can update it for all of the architectures, not just for the s390x arch. And thanks for looking into it! :)

**Comment by dandotimujahid** [comment]
@im-konge, Thanks for your suggestion. I have updated the helm-unittest version globally for all the archs.

**Review by im-konge — APPROVED** [review]
LGTM - the Helm UTs seem to pass fine, thanks for the PR :)

**Review by scholzj — APPROVED** [review]

**Review by see-quick — APPROVED** [review]
Thanks

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
