### PR TITLE
Add image.imagePullPolicy to values.yaml

### PR DESCRIPTION
**Pull request by rishinair11**
### Type of change
- Documentation

### Description
The operator `Deployment` template contains the provision to customize the `imagePullPolicy`, but that's not mentioned in the `values.yaml`.
This PR makes it clearer.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md
- [x] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. First of all, you are modifying the wrong files. Any changes should be done  in the `./packaging/` folder. Second, I'm not entirely sure what exactly are you trying to achieve with this PR. The option is properly described in the README and is super simple. Why does it need to have a commented out example in the values file?

**Comment by rishinair11** [comment]
@scholzj Hey, thanks for the reply. 
My bad, i’ll make changes in the correct file. 

Yep it’s in the README but sometimes users (like me 😅) may check the values.yaml directly as its faster. 

Let me know if that makes sense.

**Comment by scholzj** [comment]
Well, the README is there for some purpose - to cover and explain the various options. I can probably live with this change if done right, but to be honest, it does not seem to make sense to me. If we follow this approach everywhere, every file and every example we have will be full of commented-out things that are not used. Reading the relevant documentation is the right thing to learn things, not from commented-out lines in the values file.

**Comment by rishinair11** [comment]
Makes sense to me on second thought. Wasnt aware that the field was documented i. the README. 
Closing this PR.

**Pull request closed without merging**
