### PR TITLE
[MO] - [system test] -> KafkaConnect (SASL_PLAINTEXT) and KafkaOauth plain

### PR DESCRIPTION
**Pull request by see-quick**
Signed-off-by: morsak <xorsak02@stud.fit.vutbr.cz>

### Type of change

- Enhancement / new feature

### Description

This PR adds a system test for verification that KafkaConnect with SASL_PLAINTEXT authentification configured is able to connect to KafkaOauth cluster using plain communication.

### Checklist

- [x] Write tests
- [ ] Make sure all tests pass

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
Nice one covering two features ... SASL PLAIN and OAUTH over SASL PLAIN 👍

**Review by im-konge — APPROVED** [review]

**Comment by see-quick** [comment]
All tests passed except `SecurityST.testAutoReplaceClientsCaKeysTriggeredByAnno` which is not related to this change... )

**Comment by scholzj** [comment]
@Frawless Do you want to review this? Or should we merge it?

**Review by Frawless — APPROVED** [review]

**Pull request merged**
