### PR TITLE
Added Helvetia to adopters

### PR DESCRIPTION
**Pull request by ppatierno**
Signed-off-by: Paolo Patierno <ppatierno@live.com>

### Type of change

- Documentation

### Description

This PR adds Helvetia as an adopter and reorders the list alphabetically.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by scholzj** [comment]
Why do you think it should be ordered alphabetically and not first come, first served?

**Comment by samuel-hawker** [comment]
I am fine with either ordering, is there a precedent set by other Opensource projects?

**Comment by ppatierno** [comment]
> Why do you think it should be ordered alphabetically and not first-come, first-served?

the FIFO is not clear if it should be read from top to bottom or in the opposite direction.
Anyway, I don't think that there is a prize for using a FIFO. It's just a list where order doesn't mean something interesting so alphabetically makes much more sense to me.

**Comment by scholzj** [comment]
> Anyway, I don't think that there is a prize for using a FIFO and for companies coming first. It's just a list where order doesn't mean something interesting so alphabetically makes much more sense to me.

Right, it has no meaning - that is why I do not see the need for any ordering. On the practical side, you will need to explain to users who just add them self to the end that they need to change the PR and move their company into the right place etc. Or you would need to reorder it afterwards every-time. That is really my only concern about it. Otherwise I don't care.

**Comment by ppatierno** [comment]
With no clear ordering, companies could be confused about adding their name on the top or at the bottom (we could do differently so you don't know who is first come first served at the end). From the list, it should be clear the alphabetic order and anyway because I don't expect a massime amount of PRs on this, we can just check during review suggesting to put the name in the right position but still alphabetic order would make more sense than fifo.

**Comment by scholzj** [comment]
> With no clear ordering, companies could be confused about adding their name on the top or at the bottom (we could do differently so you don't know who is first come first served at the end).

And does it matter if the order doesn't matter?

Anyway ... I approved it if you wanna merge it this way.

**Pull request merged**
