### PR TITLE
[DOC] Kafka Connect migration edits

### PR DESCRIPTION
**Pull request by PaulRMellor**
Signed-off-by: prmellor <pmellor@redhat.com>

A few minor edits following review of _Migrating from Kafka Connect with S2I to Kafka Connect_ procedure in _Using Guide_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
LGTM. Out of curiosity ... why do you have the custom resource names in fixed font here? Should it be removed similarly to the Kubernetes resources?

**Review by laidan6000 — APPROVED** [review]
Thanks for making those edits. I think line 81 is still using the wrong variable.

**Comment by laidan6000** [comment]
Also, I just want to check that this content is linked somehow to the related content in #4298

**Comment by PaulRMellor** [comment]
> LGTM. Out of curiosity ... why do you have the custom resource names in fixed font here? Should it be removed similarly to the Kubernetes resources?

Holding back for now. Daniel and I spoke briefly about it after the last discussion and weren't convinced of the most easily maintained and consistent approach

**Comment by PaulRMellor** [comment]
> Also, I just want to check that this content is linked somehow to the related content in #4298

Sorry. Looking in the wrong place. Corrected now!

**Comment by PaulRMellor** [comment]
> Also, I just want to check that this content is linked somehow to the related content in #4298

Linked to https://github.com/strimzi/strimzi-kafka-operator/pull/4310

**Comment by PaulRMellor** [comment]
> Thanks for making those edits. I think line 81 is still using the wrong variable.

Sorry. Looking at wrong variable. Corrected now!

**Pull request merged**
