### PR TITLE
[systemtest] Rewrite External Kafka Clients

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Type of change

- Bugfix

### Description

Because of issue with running tests where the external Kafka clients are used "against" the Kafka 3.0.0, I'm rewriting it to fix this problem - and removing dependency of Vert.x Kafka client, which contains methods, which are not present in Kafka clients 3.0.0 anymore.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
LGTM assuming it works .... should be also reviewed by @Frawless

**Review by Frawless — APPROVED** [review]

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only groups=externalclients

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=all groups=externalclients

**Pull request merged**
