### PR TITLE
Add suport for setting priorityClassName to the operator pod

### PR DESCRIPTION
**Pull request by giskou**
### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

Add suport for setting priorityClassName to the operator pod

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally (helm template --validate)
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
I think the changes look good. But you have to do them to the `packaging/helm-charts` folder. The `helm-charts` folder is the Helm Chart from the last release and cannot be changed - only by the next release.

**Comment by giskou** [comment]
Ah, right. I will update this PR.
Sorry about that 😅

**Review by sknot-rh — APPROVED** [review]

**Review by scholzj — APPROVED** [review]
LGTM. Thanks for the PR.

**Pull request merged**
