### PR TITLE
Minor correction in docs for configuring TLS for internal clients

### PR DESCRIPTION
**Pull request by xsreality**
Kafka client application should be running inside the Kubernetes cluster

### Type of change

- Documentation

### Description

Minor correction in docs for configuring TLS for internal clients.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by scholzj** [comment]
@xsreality Thanks for the PR. Can you fix the DCO sign-off please? It should be something like this:

```
git commit --amend --signoff
git push --force-with-lease origin patch-1
```

You can find more details about DCO when you click on the _Details_ link next to DCO in the Pr status section.

**Comment by xsreality** [comment]
@scholzj Oops forgot about that, it's done now!

**Comment by scholzj** [comment]
Thanks @xsreality

**Comment by scholzj** [comment]
@ppatierno Could you have a look at this please?

**Comment by scholzj** [comment]
Thanks for the PR!

**Pull request merged**
