### PR TITLE
Refactor kafkarebalance handling methods

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Refactoring

### Description

This PR refactors some parts of the `KafkaRebalanceAssemblyOperator` in order to use the reconciliation flow of the base `AbstractOperator` class.
It removes its own implementation of the watcher handler and also refactor the signature of the `createOrUpdate` and `delete` method to return the correct types.
In relation to that, it refactors the reconciliation methods and remove the `KafkaRebalance` status update so that it can be done through the `AbstractOperator` class.
In summary, the current rebalance operator is not following the overall reconciliation flow (and corresponding methods calls) from the `AbstractOperator` but it's implementing its own. The PR fixes it.
It starts from the call to `AbstractOperator.reconcile()`, through calling the specific `createOrUpdate` and `delete` methods implementation (in the rebalance operator) until the status update in the handler of the `AbstractOperator`.

### Checklist

- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
LGTM assuming it works 😉

**Review by fvaleri — APPROVED** [review]
LGTM. Thanks.

Tested with `KafkaRebalanceAssemblyOperatorTest` and `CruiseControlST`.

**Review by ShubhamRwt — APPROVED** [review]
LGTM but looks like there are some ST failures w.r.t topic replicas change

**Comment by fvaleri** [comment]
> LGTM but looks like there are some ST failures w.r.t topic replicas change

This is a timeout, and I think @Frawless was looking into this. It's not happening when running locally, but it happens on CI from time to time.

**Comment by Frawless** [comment]
Test will be more stable when this will be merged - https://github.com/strimzi/strimzi-kafka-operator/pull/10166 but currently I am blocked by bug in test-clients so I am waiting for the fix. I would just rerun the job for now.

**Comment by ppatierno** [comment]
There is that build job with seems to run forever here but if you follow the details link it ended and it's green.
https://dev.azure.com/cncf/strimzi/_build/results?buildId=173237
I guess it's just an issue with GitHub integration so I am going to merge the PR with all the regressions and Cruise Control STs green.

**Comment by scholzj** [comment]
@ppatierno Yeah, looks like it is just stuck. Feel free to merge it.

**Comment by ppatierno** [comment]
@kyguy I know you are off so I will merge this to be able to continue with my work. Please, have a look anyway and if any comment we can always open a new PR. Thanks!

**Pull request merged**
