### PR TITLE
ST: Add check for MM2 connectors readiness

### PR DESCRIPTION
**Pull request by Frawless**
### Type of change

- Enhancement / new feature

### Description

This PR enhances the current MM2 status test with additional check for its connectors.

### Checklist

- [ ] Make sure all tests pass

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
LGTM assuming it works. Are you sure the connectors will be always there? Or do we need to check their count or something.

**Comment by Frawless** [comment]
Good point....I think there always should be connectors created when mm2 CR is ready, but tbh not sure how many. I think I always saw 3 or 4.

**Comment by scholzj** [comment]
Should be 3 normally ... source, checkpoint and heartbeat => they correspond to the sections in the CR.

**Comment by Frawless** [comment]
Ok, I will add check that there are 3 connectors in the status

**Review by scholzj — APPROVED** [review]

**Pull request merged**
