### PR TITLE
Adjust deprecated OAuth authentication parameters

### PR DESCRIPTION
**Pull request by mstruk**
This PR depends on the release of strimzi-kafka-oauth 0.4.0, specifically on [strimzi-kafka-oauth#36](https://github.com/strimzi/strimzi-kafka-oauth/pull/36)

Signed-off-by: Marko Strukelj <marko.strukelj@gmail.com>

### Type of change

_Select the type of your PR_

- Refactoring

### Description

Adjust usage of OAUTH_TOKENS_NOT_JWT and OAUTH_VALIDATION_SKIP_TYPE_CHECK to align with changes in strimzi-kafka-oauth

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by mstruk** [comment]
Can we trigger CI re-run - I assume the staging repo will be used where 0.4.0 is now available?

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by scholzj** [comment]
@mstruk I added the staging repo also to the 3rd party libs which are separate Maven project. I hope you don't mind. That should fix the image build.

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by mstruk** [comment]
@scholzj Ah, great.
I only did `mvn clean install -DskipTests` locally. Didn't generate images, so I didn't notice :/

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=oauth

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=oauth

**Pull request merged**
