### PR TITLE
[DOC] Files removed from Kafka config section

### PR DESCRIPTION
**Pull request by PaulRMellor**
Signed-off-by: prmellor <pmellor@redhat.com>

**Documentation**

Files removed as part of a restructure of the Kafka config section of the _Using Guide_

DELETED FILES
assembly-deployment-configuration-kafka.adoc //not yet
assembly-kafka-broker-replicas.adoc
proc-configuring-kafka-broker-replicas.adoc
assembly-kafka-broker-configuration.adoc
proc-configuring-kafka-brokers.adoc
assembly-zookeeper-replicas.adoc
proc-configuring-zookeeper-replicas.adoc
assembly-zookeeper-node-configuration.adoc
proc-configuring-zookeeper-nodes.adoc
ref-zookeeper-node-configuration.adoc
assembly-zookeeper-connection.adoc
assembly-resource-limits-and-requests.adoc
proc-configuring-resource-limits-and-requests.adoc
ref-resource-limits-and-requests.adoc
con-kafka-logging.adoc
con-entity-operator-logging.adoc
assembly-kafka-rack.adoc
assembly-healthchecks.adoc
proc-configuring-healthchecks.adoc
ref-healthchecks.adoc
assembly-prometheus-metrics.adoc
proc-configuring-metrics.adoc
ref-prometheus-metrics.adoc
assembly-kafka-jmx-options.adoc
proc-configuring-kafka-jmx-options.adoc
assembly-jvm-options.adoc
proc-configuring-jvm-options.adoc
ref-jvm-options.adoc
assembly-configuring-container-images.adoc
proc-configuring-container-images.adoc
ref-configuring-container-images.adoc
assembly-tls-sidecar.adoc
ref-tls-sidecar.adoc
proc-configuring-tls-sidecar.adoc
con-scheduling.adoc
assembly-scheduling-based-on-other-pods.adoc (pod scheduling)
assembly-node-scheduling.adoc
assembly-dedicated-nodes.adoc
ref-tolerations.adoc
con-scheduling-based-on-other-pods.adoc
con-scheduling-to-specific-nodes.adoc
con-dedicated-nodes.adoc
con-jmxtrans.adoc 
assembly-kafka-exporter-configuration.adoc 
assembly-deployment-configuration-kafka.adoc
proc-configuring-kafka-entity-operator.adoc

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by PaulRMellor** [comment]
To be merged after https://github.com/strimzi/strimzi-kafka-operator/pull/4064 has been merged

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
The build is failing because of the broker links. I think this will need a rebase after #4064 is merged.

**Review by laidan6000 — APPROVED** [review]
LGTM

**Comment by scholzj** [comment]
@PaulRMellor Could you please look at the conflicts and resolve them?

**Comment by PaulRMellor** [comment]
@scholzj fixed the merge conflicts

**Comment by scholzj** [comment]
@ppatierno Looks like your review was requested here ... do you plan to review it? Or can it be merged without you? I has the required approvals (from me and Paul).

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
