### PR TITLE
Concurrent delete

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Bugfix

### Description

In ST an NPE has been occasionally observed:

2020-02-06 18:55:20 DEBUG StatefulSetOperator:297 - Patching StatefulSet kafka-cluster-test/my-cluster-zookeeper
2020-02-06 18:55:20 DEBUG ZookeeperSetOperator:168 - StatefulSet my-cluster-zookeeper in namespace kafka-cluster-test has been patched
2020-02-06 18:55:20 ERROR KafkaAssemblyOperator:476 - Reconciliation #9(watch) Kafka(kafka-cluster-test/my-cluster): Current Kafka resource not found
2020-02-06 18:55:20 ERROR KafkaAssemblyOperator:232 - Failed to set status for my-cluster
2020-02-06 18:55:20 ERROR AbstractOperator:124 - Reconciliation #9(watch) Kafka(kafka-cluster-test/my-cluster): createOrUpdate failed
java.lang.NullPointerException: null
	at io.strimzi.operator.cluster.operator.resource.StatefulSetOperator.maybeRollingUpdate(StatefulSetOperator.java:96) ~[io.strimzi.cluster-operator-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.zkRollingUpdate(KafkaAssemblyOperator.java:1387) ~[io.strimzi.cluster-operator-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator.lambda$reconcile$21(KafkaAssemblyOperator.java:274) ~[io.strimzi.cluster-operator-0.18.0-SNAPSHOT.jar:0.18.0-SNAPSHOT]
	at io.vertx.core.Future.lambda$compose$3(Future.java:360) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.SucceededFuture.setHandler(SucceededFuture.java:41) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.Future.lambda$compose$3(Future.java:365) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.Future.lambda$map$4(Future.java:407) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:107) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:152) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.complete(FutureImpl.java:113) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:178) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.FutureImpl.handle(FutureImpl.java:21) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) ~[io.vertx.vertx-core-3.8.4.jar:3.8.4]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510) [io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518) [io.netty.netty-transport-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044) [io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.42.Final.jar:4.1.42.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]

The cause seems to be that the `Kafka` CR is deleted part way through a reconciliation. Kubernetes GC causes the child resources to be deleted which can result in a `ReconciliationResult.Noop` with a null resource. This null resource is used later without a check for null.

It's not _completely_ clear how this null arises withing `AbstractResourceOperator.reconcile()` (presumably it's via Noop), but by having a much clearer contract about which `ReconciliationResults` permit null we should be able to track it down. Also the usual case for a caller of `ReconciliationResult.resource()` is to expect a non-nullable result, so throw a clearer exception when the result would be null.

cc @Frawless 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by tombentley** [comment]
@strimzi-ci run tests

**Comment by tombentley** [comment]
@strimzi-ci run tests

**Comment by ppatierno** [comment]
@tombentley should we wait for Jenkins green before merging this?

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.UserST#testUpdateUser

**Comment by Frawless** [comment]
Log from last run is gone already so I trigger just that failing test. However, I don't think the fail was caused by these changes.

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.UserST#testUpdateUser

**Comment by tombentley** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.UserST#testUpdateUser

**Comment by tombentley** [comment]
Cherry-picked to 0.17.

**Pull request merged**
