### PR TITLE
Connect dashboard is useable also for the connect S2I

### PR DESCRIPTION
**Pull request by stanlyDoge**
### Type of change
- Bugfix

### Description
https://github.com/strimzi/strimzi-kafka-operator/issues/1883
Implemented option 2).
Tested with both (connect and connectS2I).

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by stanlyDoge** [comment]
Snímek z 2019-08-12 12-56-09
Snímek z 2019-08-12 12-56-21
Snímek z 2019-08-12 12-56-33

**Comment by ppatierno** [comment]
@stanlyDoge did you try with both KafkaConnect and KafkaConnectS2I?

**Comment by stanlyDoge** [comment]
@ppatierno I mentioned it in the PR description. Yes, I did :)

**Comment by ppatierno** [comment]
who takes care of PR descriptions? :P

**Pull request merged**
