### PR TITLE
[systemtest][fix] logCurrentResourceStatus NPE fix

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Type of change

- Bugfix

### Description

Even I tried to fix our method for printing current status of CR - messages and conditions from pods - it sometimes happen that it throws the NPE. So I'm adding `if`s to check if the current condition message/status is not null.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only

**Review by Frawless — APPROVED** [review]
You should update PR description. LGTM

**Review by scholzj — APPROVED** [review]

**Comment by im-konge** [comment]
The test failures are not related to this PR, gonna fix it ASAP in separate.

**Comment by im-konge** [comment]
Fix for the acceptance is in #3556

**Pull request merged**
