### PR TITLE
Reuse Util.decodeFromBase64

### LINKED ISSUE #9745: [Enhancement]: Use Util.decodeFromBase64 from operator-common module
### Related problem

_No response_

### Suggested solution

In #9483 the method `decodeFromBase64` was introduced in `operator-common/src/main/java/io/strimzi/operator/common/Util.java`. The same logic is used in multiple places and across different modules. It would be good to use the new method instead, similar to what we have for the companion method `encodeToBase64`.

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MichaelMorrisEst**
### Type of change

Refactoring

### Description

Refactor to make use of Util.decodeFromBase64 to reduce code duplication.

Closes #9745 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [X] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [X] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
Thanks for the PR. The changes look good to me.

**Review by fvaleri — COMMENTED** [review]
Thanks for working on this.

I see that there are few missing replacements in the following classes:

- KafkaUserModelTest
- ListenersST

I was also wondering if we should create overloaded methods to cover cases where it takes or return a byte array. Same for the encoding method. This would be a different PR though. Wdyt?

**Comment by scholzj** [comment]
@fvaleri Let's take it step by step to avoid having huge and big PRs full of conflicts and taking a long time to handle.

**Comment by fvaleri** [comment]
> @fvaleri Let's take it step by step to avoid having huge and big PRs full of conflicts and taking a long time to handle.

Sure, they could be multiple PRs.

**Comment by MichaelMorrisEst** [comment]
I deliberately excluded the occurrences in KafkaUserModelTest and ListenersST as, unlike the other cases, the charset used in the String constructor is not specified (i.e. the platform's default charset is used)

Perhaps it is ok to use  <code>decodeFromBase64(String data)</code> resulting in US_ASCII now being used in these places? 

Or perhaps I should:
- change <code>decodeFromBase64(String data)</code> to not specify the charset in the String constructor, i.e. no longer use US_ASCII by default
- use that in KafkaUserModelTest and ListenersST, so behaviour is as today
- use <code>decodeFromBase64(String data, Charset charset)</code> with US_ASCII as charset everywhere <code>decodeFromBase64(String data)</code> is currently used

**Comment by scholzj** [comment]
I think that in `KafkaUSerModelTest, `US_ASCII` should be fine. I think it is the same in the case where a String is created from base64 in `ListenersST`.

**Review by fvaleri — APPROVED** [review]
LGTM. Thanks.

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks for the PR!

**Comment by MichaelMorrisEst** [comment]
Thanks for taking the time to review, I can also look at creating issues/PRs for the comment above by @fvaleri on also having methods for byte[], taking it one piece at a time

**Comment by scholzj** [comment]
> Thanks for taking the time to review, I can also look at creating issues/PRs for the comment above by @fvaleri on also having methods for byte[], taking it one piece at a time

Sure, feel free to look into it if you want.

**Pull request merged**
