### PR TITLE
include "metadata.log.dir" as forbidden prefix

### PR DESCRIPTION
**Pull request by showuon**
### Type of change

- Bugfix

### Description

`metadata.log.dir` is also like `log.dir` in data log: https://kafka.apache.org/documentation/#brokerconfigs_metadata.log.dir . This should be forbidden config as `log.dir`.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [V] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Can you please fix the DCO signoff?

**Comment by showuon** [comment]
> Can you please fix the DCO signoff?

Fixed. Thanks.

**Comment by scholzj** [comment]
@showuon It looks like you did not update the derived resources:

```
ERROR: Uncommitted changes in derived resources:
M	documentation/modules/appendix_crds.adoc
M	packaging/helm-charts/helm3/strimzi-kafka-operator/crds/040-Crd-kafka.yaml
M	packaging/install/cluster-operator/040-Crd-kafka.yaml
Run the following to add up-to-date resources:
  mvn clean verify -DskipTests -DskipITs \
    && make crd_install \
    && make dashboard_install \
    && make helm_install \
    && git add packaging/install/ packaging/helm-charts/ documentation/modules/appendix_crds.adoc cluster-operator/src/main/resources/cluster-roles \
    && git commit -s -m 'Update derived resources'
```

Can you do it, please? Or if you want, I can run it myself and push it into the PR. Just let me know.

**Comment by showuon** [comment]
@scholzj  , updated. Thanks.

**Review by scholzj — APPROVED** [review]
Thanks.

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
