### PR TITLE
added filtering by namespace in grafana panels

### PR DESCRIPTION
**Pull request by AliDotS**
### Enhancement

Added filtering by namespace in grafana pane

If the same topic is used in multiple namespaces, panels show aggregated results
With filtering by namespace this doesn't happen

### CODE REVIEW

**Comment by sknot-rh** [comment]
Hi. Thanks for the PR. Could you please sign your commit? You can use `git commit --amend --no-edit --signoff` and push.

**Comment by AliDotS** [comment]
> Hi. Thanks for the PR. Could you please sign your commit? You can use `git commit --amend --no-edit --signoff` and push.

It should be signed now.

**Review by ppatierno — APPROVED** [review]
Thanks for the PR!

**Review by sknot-rh — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
