### PR TITLE
Label minikube node on azure to make SpecificST working

### PR DESCRIPTION
**Pull request by Frawless**
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

### Type of change

- Bugfix

### Description

This PR fixes tests added in https://github.com/strimzi/strimzi-kafka-operator/pull/3873 on azp. The tests weren't executed on Azure and it seems we didn't even execute them before.

### Checklist

- [ ] Make sure all tests pass

### CODE REVIEW

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=SpecificST test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=SpecificST test_only

**Comment by Frawless** [comment]
The failure is caused by CruiseControl test which is fixed in https://github.com/strimzi/strimzi-kafka-operator/pull/4008

**Review by scholzj — APPROVED** [review]

**Pull request merged**
