### PR TITLE
[systemtest][fix] Fix CC acceptance test

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Bugfix

### Description

This PR gonna fix `testCruiseControlWithRebalanceResource` which was failing in our acceptance profile. Problem here was, that after my previous PR where I changed the timeouts for the resources, only 4 minutes on waiting for `ProposalReady` wasn't enough. So I added new method just for KafkaRebalance resource (to get the right timeout) to the `ResourceOperation` class, where it returns timeout depended on each state.

Also I moved enum in `KafkaRebalanceUtils` to be in separate class, in the `enums` folder.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by im-konge** [comment]
@ppatierno @scholzj @Frawless if you think that we should split the timeouts to more groups, leave me a comment please.

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only

**Comment by im-konge** [comment]
@Frawless I think that @tomncooper will do something about it. @scholzj should I add the enum to API?

**Comment by scholzj** [comment]
I do not think we should do it here in this PR. If others changed the mind it can be done in a separate PR.

**Comment by im-konge** [comment]
Okay, so after the review from @ppatierno we can merge it

**Pull request merged**
