### PR TITLE
Add support for Kafka 3.9.0

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

This PR adds support for Kafka 3.9.0. It also removed support for Kafka 3.7.0 and 3.7.1.

_It is currently based on 3.9.0-RC5._ 

### Checklist

- [x] Make sure all tests pass
- [x] Update documentation
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by celvin** [comment]
Is there a projected date for this to be completed?

@azure-pipelines
build Failing after 29m — Build #20241014.8 had test failures
[Details](https://github.com/strimzi/strimzi-kafka-operator/pull/10706/checks?check_run_id=31522246509)
@azure-pipelines
build (Strimzi Unit & IT tests Test Strimzi test_strimzi_java-17) Failing after 9m — Strimzi Unit & IT tests Test Strimzi test_strimzi_java-17 failed
[Details](https://github.com/strimzi/strimzi-kafka-operator/pull/10706/checks?check_run_id=31522133264)

**Comment by ppatierno** [comment]
@celvin it depends on the Kafka community and when 3.9.0 is released. Thanks to this draft, Jakub found a regression in the KRaft migration process in Kafka and they fixed it but a new release candidate is needed before the final one.

**Comment by scholzj** [comment]
Closing until the GA or next RC.

**Pull request closed without merging**
