### PR TITLE
fix(helm): Remove `=` in Xms and Xmx definitions in comments

### PR DESCRIPTION
**Pull request by pando85**
### Type of change

_Select the type of your PR_

- Bugfix

### Description

Invalid code in commented code.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
The change it self is good. But you have to do it to the files in `packaging/...`. The files you are changing are the released files and they cannot be changed.

**Comment by pando85** [comment]
Hello @scholzj ,

I updated my commit changing them in the `packaging/...` too but it should be just in the `packaging/...` or in both? I don't get it, sorry.

**Comment by scholzj** [comment]
> I updated my commit changing them in the packaging/... too but it should be just in the packaging/... or in both? I don't get it, sorry.

Sorry for not being clear. It should be changed only in the `packaging/...`.

**Comment by pando85** [comment]
Done, thanks.

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks!

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
