### PR TITLE
ST: Fix zookeeper upgrade test

### PR DESCRIPTION
**Pull request by Frawless**
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

### Type of change

- Bugfix

### Description

Lukas accidentally commited duplicity code to `KafkaST` which was already in `ZookeeperUpgradeST` (it's needed only there). This PR removes it.

I also added fix for zookeeper upgrade test, from where I accidentally removed upgrade of `log.message.format.version` from upgrade and downgrade instead only from downgrade.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=upgrade testcase=ZookeeperUpgradeST test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=upgrade testcase=ZookeeperUpgradeST test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=upgrade testcase=ZookeeperUpgradeST test_only

**Comment by tombentley** [comment]
Cherry picked for 0.17

**Pull request merged**
