### PR TITLE
ST: Fix NPE in SecurityST and ConnectS2IST

### PR DESCRIPTION
**Pull request by Frawless**
### Type of change

_Select the type of your PR_

- Bugfix

### Description
Same situation as in https://github.com/strimzi/strimzi-kafka-operator/pull/2950. We shouldn't inherit test classes, because maven-surefire then reruns all loaded tests.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by Frawless** [comment]
@strimzi-ci run tests test_only profile=regression testcase=SecurityST,SslConfigurationST

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.security.SecurityST#testAutoRenewCaCertsTriggerByExpiredCertificate,io.strimzi.systemtest.security.SecurityST#testCaRenewalBreakInMiddle,io.strimzi.systemtest.security.SecurityST#testCertificates,ConnectS2IST#testChangeConnectS2IConfig test_only

**Comment by Frawless** [comment]
I can wait until you will merge it and then resolve conflicts. I think few `SecurityST` tests are broken by wrong path to resource certs anyway

**Comment by scholzj** [comment]
@Frawless Ok. The reason I touched it was that one of the tests was failing in one class and passing in the other.

**Comment by scholzj** [comment]
@Frawless Ok, the Zookeeper PR is merged now. So you can look at the conflict. Sorry.

**Comment by Frawless** [comment]
@scholzj no worries, I resolve the conflict and rename the PR. Now, let's wait for tests result.

@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.security.SecurityST#testAutoRenewCaCertsTriggerByExpiredCertificate,io.strimzi.systemtest.security.SecurityST#testCaRenewalBreakInMiddle,io.strimzi.systemtest.security.SecurityST#testCertificates,ConnectS2IST#testChangeConnectS2IConfig test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.security.SecurityST#testCertificates test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.security.SecurityST#testCertificates test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.security.SecurityST#testCertificates test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests test_only profile=regression testcase=SecurityST

**Pull request merged**
