### PR TITLE
docs(uto): updates UTO docs to promote unidirectional mode as primary/default

### PR DESCRIPTION
**Pull request by PaulRMellor**
**Documentation**

Updates the docs to promote the Unidirectional Topic Operator (UTO) from preview.
Switches the order for  the **Deploying the standalone Topic Operator** procedure.
That is, shows install of the UTO as the standard install, and installation of the Bidirectional Topic Operator (BTO) as the alternative.

Continues from work in https://github.com/strimzi/strimzi-kafka-operator/pull/9316

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by tombentley — COMMENTED** [review]
The changes seem fine. I wonder if we should add some words to alert users to the fact that once the feature gate reaches GA the BTO will be unavailable. We're currently talking about it being an "alternative", and that's true right not, but it's only really a short-term "alternative".

**Review by fvaleri — APPROVED** [review]
Thanks.

**Review by ppatierno — APPROVED** [review]

**Comment by PaulRMellor** [comment]
> The changes seem fine. I wonder if we should add some words to alert users to the fact that once the feature gate reaches GA the BTO will be unavailable. We're currently talking about it being an "alternative", and that's true right not, but it's only really a short-term "alternative".

Thanks @tombentley - you're right. So I've added a note in the standalone section and where we introduce the two modes:
[docs(review): note on phasing out bto](https://github.com/strimzi/strimzi-kafka-operator/pull/9370/commits/601264ce393aae98f08336d9979ca7e8bd38b8ea)

**Comment by scholzj** [comment]
@tombentley Do you have something more for this?

**Comment by scholzj** [comment]
Discussed on the community call on 30.11.2023: @tombentley Do you have anything more on this? Thanks.

**Review by scholzj — APPROVED** [review]

**Pull request merged**
