### PR TITLE
Add RackAwareDistributionGoal to CC goal config by default

### PR DESCRIPTION
**Pull request by kyguy**
### Type of change

- Enhancement / new feature

### Description

Resolves https://github.com/strimzi/strimzi-kafka-operator/issues/10297

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for looking into this @kyguy

**Review by see-quick — APPROVED** [review]

**Review by fvaleri — APPROVED** [review]
LGTM. Thanks @kyguy.

**Review by ShubhamRwt — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
