### PR TITLE
Fix #6019 moving log4j to test scope

### LINKED ISSUE #6019: Minimize api dependencies
**Is your feature request related to a problem? Please describe.**
The api module has very broad compile dependencies, including on log4j and vert.x core.

**Describe the solution you'd like**
The log4j dependencies can be test instead.  The vert.x dependency seems to only be for a single annotation - but the dependency has a large transitive footprint.  It doesn't appear that vert.x offers another narrow dependency, maybe they could be persuaded to release one.

Similarly it looks like an upstream issue is warranted against fabric8 to depend only on a client api without pulling in all the transitive dependencies.  I'll make sure something for that is captured for fabric8 6.  The only thing that seems problematic is the direct usage of KubernetesDeserializer.registerCustomKind.

### PR DESCRIPTION
**Pull request by shawkins**
### Type of change

- Refactoring

### Description

Initial change towards #6019 to minimize dependencies exposed by the api module.

### CODE REVIEW

**Comment by scholzj** [comment]
Can you fix the DCO please @shawkins?

**Comment by shawkins** [comment]
> Can you fix the DCO please @shawkins?

Yes, no problem.

**Review by scholzj — APPROVED** [review]
Thanks for the PR

**Review by Frawless — APPROVED** [review]

**Pull request merged**
