### PR TITLE
[ST] Add UnidirectionalTopicOperator to FG pipelines in Azure

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Bugfix

### Description

This PR adds `UnidirectionalTopicOperator` to FG pipelines in Azure, as it was missing there and it was only present in the KRaft pipelines.

### Checklist

- [ ] Make sure all tests pass

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
LGTM if the tests pass.

**Review by henryZrncik — APPROVED** [review]

**Pull request merged**
