### PR TITLE
[ST] NamespaceDeletionRecoveryIsolatedST modifications

### PR DESCRIPTION
**Pull request by jankalinic**
### Type of change

- Refactoring

### Description

This PR should fix problems with NamespaceDeletionRecoveryIsolatedST. PVs were not present at the time of the test and hardcoded provisioner for them was working only for openshift clusters provisioned on openstack, but not for aws. So this PR gets default provisioner for the StorageClass and creates PVs correctly. So now everything works fine for these environments, but for minikube / microshift there is a need to create PVs and StorageClass (set to local) before the test run (as advised in https://kubernetes.io/docs/concepts/storage/storage-classes/)

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by jankalinic** [comment]
@strimzi-ci run tests --ocp-version=4.13 --install-type=bundle --testcase=NamespaceDeletionRecoveryIsolatedST

**Review by Frawless — APPROVED** [review]
Changes lgtm,  guess you just missing the regression tag as we discussed (add it and trigger jobs).

**Review by im-konge — APPROVED** [review]

**Review by see-quick — APPROVED** [review]

**Comment by im-konge** [comment]
@strimzi-ci run tests --ocp-version=4.13 --install-type=bundle --testcase=NamespaceDeletionRecoveryIsolatedST

**Comment by jankalinic** [comment]
@strimzi-ci run tests --ocp-version=4.13 --install-type=bundle --testcase=NamespaceDeletionRecoveryIsolatedST

**Pull request merged**
