### PR TITLE
chore: make the format of example yaml files more consistent

### PR DESCRIPTION
**Pull request by nakamasato**
### Type of change

_Select the type of your PR_

- Chore

### Description

_Please describe your pull request_

- Remove trailing spaces from example yaml files
- Unify EOF of example yaml files
- Automate checking trailing spaces and EOF for example yaml files by Github Actions (https://pre-commit.com)
	- local: `pre-commit install` to run the validation every time you commit.
	- CI: github to run `pre-commit`.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by scholzj** [comment]
Can you explain more about why is it needed and how does it work? Does it fail when the trailing spaces are not to its liking?

**Comment by nakamasato** [comment]
@scholzj Thank you for following up. This is totally a nice-to-have suggestion. It'd be better at least for me if we have a consistent format check for YAML files. 
Of course, the current files with trailing spaces or lines work as expected. If you think it's not necessary to have consistency in the trivial format in Strimzi project, it's also fine for me. 
What do you think?

**Comment by scholzj** [comment]
@nakamasato So how does the check work? Does it just fail when the validation fails?

**Comment by nakamasato** [comment]
@scholzj Yes, exactly! Sorry for the lack of explanation in the description.
We can check in the same way in your local and CI:
- You can enable it by `pre-commit install` in your local (https://pre-commit.com/) so every time you commit, `pre-commit` automatically checks the target files defined in `.pre-commit-config.yaml`.
- Run `pre-commit` in CI to automatically check the files.

**Review by scholzj — APPROVED** [review]
Ok, lets give it a try and see how it works. Thanks for the PR.

**Review by sknot-rh — APPROVED** [review]

**Review by Frawless — APPROVED** [review]
Guess we could also add https://github.com/ibiqlik/action-yamllint in the future to check yaml syntax of our examples.

**Pull request merged**
