### PR TITLE
Fix the Jenkins PR build

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

After the changes to the build system, the Jenkins PR build does not work anymore when it is supposed to build the imaged. This PR tries to fix it.

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=smoke

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=smoke

**Comment by scholzj** [comment]
@strimzi-ci run tests test_only profile=smoke

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=smoke

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=smoke

**Comment by scholzj** [comment]
@strimzi-ci run tests test_only profile=smoke

**Review by Frawless — APPROVED** [review]

**Pull request merged**
