### PR TITLE
Clarify sentence about auto-creation of ClusterRoleBindings

### PR DESCRIPTION
**Pull request by kaihil**
### Type of change

_Select the type of your PR_

- Documentation

### Description
See https://github.com/strimzi/strimzi-kafka-operator/discussions/5116

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for noticing this and opening the PR. The change looks good. Could you please fix the DCO? The instructions should be under the _Details_ link next to the `DCO` status in the PRs status section.

**Review by Frawless — APPROVED** [review]

**Comment by scholzj** [comment]
@kaihil Any chance you can fix the DCO as described above? The PR looks good, but we cannot merge it without the DCO.

**Comment by kaihil** [comment]
@scholzj Done :) Thanks for mentioning!

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
@kaihil Great, thanks. I will merge it after the tests finish.

**Pull request merged**
