### PR TITLE
Fix incomplete Connect build URL regex

### PR DESCRIPTION
**Pull request by fvaleri**
Without the ending $, the string is considered valid if the expression matches anywhere within the string.

https://json-schema.org/understanding-json-schema/reference/string.html#regular-expressions

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Can you please update the description?

**Comment by tombentley** [comment]
Can we review the other uses of pattern, because I wouldn't be surprised if this wasn't the only incorrect usage.

**Review by scholzj — APPROVED** [review]

**Comment by fvaleri** [comment]
> Can we review the other uses of pattern, because I wouldn't be surprised if this wasn't the only incorrect usage.

Right, I found few other places where `^...$` is missing. I'm going to commit a fix for them too.

**Review by tombentley — APPROVED** [review]
LGTM, but one nit: Can we add something to the Javadoc for `@Pattern` to note the behaviour?

**Comment by fvaleri** [comment]
Sure, let me add that note.

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
