### PR TITLE
Upgrade kubernetes-client to 5.0.0

### PR DESCRIPTION
**Pull request by sknot-rh**
### Type of change

- Refactoring

### Description

Upgrading dependency. Doneable classes removed. `Spec` and `Status` are now part of CustomResource (I think we can extend `io.fabric8.kubernetes.api.model.Status` for our status classes). 

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — APPROVED** [review]

**Review by im-konge — APPROVED** [review]
Thanks for updating the STs :) LGTM

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
@Frawless @tombentley Do you plan to review this? Or can it be merged? It passed the tests and is already approved by me and Paolo.

**Comment by tombentley** [comment]
I have looked at it, and my only reservation is that I'm not completely sure how well it will work with the move to `v1beta2`. The `CustomResource` constructor now figures out the API version from the annotations on the class, meaning that our subclasses of `CustomResource` (e.g. `Kafka` etc) need to be annotated with `@Version` and so are version specific. It don't fully understand the consequences of that. Maybe there are none, maybe we can work around it, or maybe for those subclasses we'd end up needing per-version "CR root" classes (I'm pretty sure the rest of the classes could stay the same). I guess there's only one way we'll find out, and there isn't a good alternative which doesn't involve merging this PR.

**Review by tombentley — APPROVED** [review]

**Pull request merged**
