### PR TITLE
Add support for Kafka 2.8.0

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

This PR adds support for Apache Kafka 2.8.0. Debezium - used as the test cluster in some integration tests - is currently not ready for Kafka 2.8.0. So this PR does not move the operators to use 2.8.0 clients - just adds support for running 2.8.0 as operand. Since we currently do not use any 2.8.0 feature in the operator code, this should not be a blocker and can be fixed later when needed / when Debezium supports 2.8.

_Note: The failing regression tests are related to Helm Charts. That seems to be caused by a bug in the tests. I raised #4778 for this._

### Checklist

- [x] Make sure all tests pass
- [x] Update documentation
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by tombentley — APPROVED** [review]
I've only looked at the config model part, but it looks ok to me.

**Review by sknot-rh — APPROVED** [review]

**Pull request merged**
