### PR TITLE
Openssl refactor (#4573)

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Enhancement / new feature
- Refactoring

### Description

This is the same as the PR I opened a few weeks ago, but reverted because it broke the regression tests. The problem was that the centos7 version of openssl is older and some of the commands didn't work. This PR makes the same functionality work in that version of openssl.

* Support generating intermediate CA certs
* Improve logging in OpenSslCertManager

Signed-off-by: Tom Bentley <tbentley@redhat.com>

### CODE REVIEW

**Comment by ppatierno** [comment]
@tombentley I see this PR marked as Draft but you requested my review. Is it now final or still draft?

**Comment by tombentley** [comment]
@ppatierno @scholzj this is identical to the PR which we previously merged and later reverted (so you've already reviewed this). It now works because the switch to UBI-8 brought a more recent version on openssl.

**Review by scholzj — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
