### PR TITLE
Allow disabling leader election in Helm chart

### PR DESCRIPTION
**Pull request by SoerenHenning**
### Type of change

_Select the type of your PR_

- Enhancement / new feature
- Refactoring

### Description

As proposed in #8893, this PR adds the option to set the `STRIMZI_LEADER_ELECTION_ENABLED` in the Helm chart.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Please check my reply on the issue you opened. This is not the right solution for your problem - it might not solve it or it might solve it only for a few weeks until something new breaks it. A real solution is to update your RBAC resources.

That said, I do not think it is a problem to have a flag to disable the leader election. So if you want, I do not think it is problem to merge it. I just want to make sure you don't expect more from it then what it can do. If you wanna proceed with this, please add the new option to the README file of the Helm chart.

**Comment by SoerenHenning** [comment]
As replied to the linked issue #8893, I do not need this feature anymore. In case you still want to merge it, I updated the README file. (As the operator provides this option, I see no reason why the Helm chart should not support it.)

**Review by scholzj — APPROVED** [review]
LGTM. Thanks.

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
