### PR TITLE
[ST] AlternativeReconcileTriggersST addition of volumes check

### PR DESCRIPTION
**Pull request by henryZrncik**
### Type of change

- Refactoring

### Description

addition of volume presence/absence check when modifying jbod storage.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Update documentation

### CODE REVIEW

**Review by jankalinic — APPROVED** [review]

**Review by im-konge — APPROVED** [review]

**Comment by im-konge** [comment]
@strimzi-ci run tests --profile=regression --install-type=bundle --cluster-type=minikube --cluster-version=stable --testcase=AlternativeReconcileTriggersST

**Review by see-quick — APPROVED** [review]

**Comment by henryZrncik** [comment]
@strimzi-ci run tests --profile=regression --install-type=bundle --cluster-type=minikube --cluster-version=stable --testcase=AlternativeReconcileTriggersST

**Comment by henryZrncik** [comment]
@strimzi-ci run tests --profile=regression --install-type=bundle --cluster-type=minikube --cluster-version=stable --testcase=AlternativeReconcileTriggersST

**Comment by henryZrncik** [comment]
@strimzi-ci run tests --profile=regression --install-type=bundle --cluster-type=minikube --cluster-version=stable --testcase=AlternativeReconcileTriggersST

**Comment by henryZrncik** [comment]
@strimzi-ci run tests --profile=regression --install-type=bundle --cluster-type=minikube --cluster-version=stable --testcase=AlternativeReconcileTriggersST

**Comment by henryZrncik** [comment]
@strimzi-ci run tests --profile=regression --install-type=bundle --cluster-type=minikube --cluster-version=stable --testcase=AlternativeReconcileTriggersST --parallel-count=1

**Pull request merged**
