### PR TITLE
[ST] Add 0.37.0 to STs after the release

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Enhancement

### Description

This PR adds Strimzi `0.37.0` version to the upgrade/downgrade files and also to `Environment` class after the release.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by Frawless — APPROVED** [review]

**Review by see-quick — APPROVED** [review]

**Comment by im-konge** [comment]
@strimzi-ci run tests --cluster-type=ocp --profile=all --groups=olmupgrade --cluster-version=4.13

**Comment by im-konge** [comment]
OLM upgrade fails because Strimzi 0.37.0 is not available in the catalog - so I would need to wait or merge it and try it afterwards.

**Comment by scholzj** [comment]
> OLM upgrade fails because Strimzi 0.37.0 is not available in the catalog - so I would need to wait or merge it and try it afterwards.

They were out of disk space so some tests were failing. They passed now, so I guess it will be merged as some merge queue is processed or something like that.

**Review by henryZrncik — APPROVED** [review]

**Comment by im-konge** [comment]
@strimzi-ci run tests --cluster-type=ocp --profile=all --groups=olmupgrade --cluster-version=4.13

**Comment by im-konge** [comment]
@strimzi-ci run tests --cluster-type=ocp --profile=all --groups=olmupgrade --cluster-version=4.13

**Comment by im-konge** [comment]
@strimzi-ci run tests --cluster-type=ocp --profile=all --groups=olmupgrade --cluster-version=4.13

**Comment by im-konge** [comment]
@strimzi-ci run tests --cluster-type=ocp --profile=all --groups=olmupgrade --cluster-version=4.13

**Comment by im-konge** [comment]
@strimzi-ci run tests --cluster-type=ocp --profile=all --groups=olmupgrade --cluster-version=4.13

**Comment by im-konge** [comment]
@strimzi-ci run tests --cluster-type=ocp --profile=all --groups=olmupgrade --cluster-version=4.13 --env=OLM_OPERATOR_VERSION=6.6.6;CLUSTER_OPERATOR_INSTALL_TYPE=OLM;OLM_SOURCE_NAME=strimzi-source;

**Comment by im-konge** [comment]
@strimzi-ci run tests --cluster-type=ocp --profile=all --groups=olmupgrade --cluster-version=4.13 --env=OLM_OPERATOR_VERSION=6.6.6;CLUSTER_OPERATOR_INSTALL_TYPE=OLM;OLM_SOURCE_NAME=strimzi-source;

**Pull request merged**
