### PR TITLE
Helm: Using release name instead of hard code name

### PR DESCRIPTION
**Pull request by haoxins**
### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

Using Release name instead of the hard code name in the Helm chart

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. Some quick comments:
* All changes done to the Helm Chart outside of the regular releae have to be done to ther `packaging/helm-charts` directory. The `helm-charts` changes only during a release. So you would need to update your PR.
* That said, I do not think your changes work anyway. The Operator is creating binding for some of these roles using the fixed names. So when you change the names, you break the operator. So I do not think this can done.
* It would be great to have a proper description explaining also the motivation of this and what does it help with.

**Comment by scholzj** [comment]
Well, as I said, it will not work anyway. The roles need to have their original names. 

Even if it worked, I'm also not sure why will the names be more meaningful this way. Your system will be full of resources for different versions which will IMHO not get deleted. I also don't understand how would upgrade work -> who will deelte the old deployment for example?

**Comment by haoxins** [comment]
> I also don't understand how would upgrade work -> who will deelte the old deployment for example?

Yes, we can't, but this will be useful for the new users.
This is a broken change anyway.

**Comment by scholzj** [comment]
That could make the Helm chart configurable but backwards compatible, yes. But it will not solve the issue that the operator will not work. You would need to extend the whole operator code to be ready for this as wel - to have the (cluster)role names configurable inside the operator. So it would be a a bit more complicated than just the Helm Chart.

**Comment by haoxins** [comment]
> But it will not solve the issue that the operator will not work. 

I'm new to `Strimzi`, after take a glance at the code and pods, I know what you said.

Will consider to contribute this feature in the future.

**Pull request closed without merging**
