### PR TITLE
[DOC] new secure communications image

### PR DESCRIPTION
**Pull request by PaulRMellor**
Signed-off-by: prmellor <pmellor@redhat.com>

**Documentation**

An updated image to show secure communication in a cluster. 
Image now consistent with newer images in guide
Condition removed, as it's a generic image

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ppatierno** [comment]
in the picture, it's not clear why the client is using 9094 and 9093 to connect to brokers. It seems it needs both of them. Is it clear somewhere that one is external and the other is internal? Maybe we should put two different clients in the picture. One using 9094 and another one using 9093, calling them external and internal clients respectively?

**Comment by PaulRMellor** [comment]
> in the picture, it's not clear why the client is using 9094 and 9093 to connect to brokers. It seems it needs both of them. Is it clear somewhere that one is external and the other is internal? Maybe we should put two different clients in the picture. One using 9094 and another one using 9093, calling them external and internal clients respectively?

Thanks @ppatierno - it might be clear enough for what we want to show -- secure connections. That said, I like the idea.

**Comment by PaulRMellor** [comment]
@ppatierno Hi paolo. We have separate clients now.

**Comment by ppatierno** [comment]
That's cool thanks!

**Pull request merged**
