### PR TITLE
Adds proper error message when Cruise Control fails to generate the `rebalance` proposal

### LINKED ISSUE #8444: Provide proper error message when Cruise Control fails to generate `KafkaRebalance` proposal
When Cruise Control fails to generate a proposal, the operator doesn't really record any useful errors and user has to go into the Cruise Control logs to find out what the issue was. For example when the rebalance fails because of rack aware goals with following error:

```
2023-04-27 15:51:16 WARN  GoalOptimizer:606 - Detected unfixable proposal optimization
com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException: [RackAwareGoal] Insufficient number of racks to distribute each replica (Current: 1, Needed: 3). Add at least 2 racks with brokers. Add at least 2 racks with brokers.
	at com.linkedin.kafka.cruisecontrol.analyzer.goals.AbstractGoal.optimize(AbstractGoal.java:130) ~[cruise-control-2.5.121.jar:?]
	at com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer.optimizations(GoalOptimizer.java:467) ~[cruise-control-2.5.121.jar:?]
	at com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer.optimizations(GoalOptimizer.java:403) ~[cruise-control-2.5.121.jar:?]
	at com.linkedin.kafka.cruisecontrol.analyzer.GoalOptimizer$ProposalCandidateComputer.run(GoalOptimizer.java:599) ~[cruise-control-2.5.121.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

The operator seems to only report this:

```
2023-04-27 15:20:38 INFO  KafkaRebalanceAssemblyOperator:405 - Reconciliation #26(kafkarebalance-watch) KafkaRebalance(myproject/my-rebalance): Rebalance action is performed and KafkaRebalance resource is currently in [New] state
2023-04-27 15:20:38 INFO  KafkaRebalanceAssemblyOperator:1254 - Reconciliation #26(kafkarebalance-watch) KafkaRebalance(myproject/my-rebalance): Requesting Cruise Control rebalance [dryrun=true]
2023-04-27 15:20:38 INFO  CrdOperator:133 - Reconciliation #26(kafkarebalance-watch) KafkaRebalance(myproject/my-rebalance): Status of KafkaRebalance my-rebalance in namespace myproject has been updated
2023-04-27 15:20:38 INFO  KafkaRebalanceAssemblyOperator:405 - Reconciliation #27(kafkarebalance-watch) KafkaRebalance(myproject/my-rebalance): Rebalance action is performed and KafkaRebalance resource is currently in [PendingProposal] state
2023-04-27 15:20:43 INFO  KafkaRebalanceAssemblyOperator:1254 - Reconciliation #27(kafkarebalance-watch) KafkaRebalance(myproject/my-rebalance): Requesting Cruise Control rebalance [dryrun=true]
2023-04-27 15:20:48 INFO  KafkaRebalanceAssemblyOperator:1254 - Reconciliation #27(kafkarebalance-watch) KafkaRebalance(myproject/my-rebalance): Requesting Cruise Control rebalance [dryrun=true]
2023-04-27 15:20:48 ERROR KafkaRebalanceAssemblyOperator:880 - Reconciliation #27(kafkarebalance-watch) KafkaRebalance(myproject/my-rebalance): Cruise Control getting rebalance proposal failed
2023-04-27 15:20:48 ERROR KafkaRebalanceAssemblyOperator:485 - Reconciliation #27(kafkarebalance-watch) KafkaRebalance(myproject/my-rebalance): Status updated to [NotReady] due to error: null
2023-04-27 15:20:48 INFO  CrdOperator:133 - Reconciliation #27(kafkarebalance-watch) KafkaRebalance(myproject/my-rebalance): Status of KafkaRebalance my-rebalance in namespace myproject has been updated
2023-04-27 15:20:48 INFO  KafkaRebalanceAssemblyOperator:405 - Reconciliation #28(kafkarebalance-watch) KafkaRebalance(myproject/my-rebalance): Rebalance action is performed and KafkaRebalance resource is currently in [NotReady] state
```

We should be able to provide a better error than `null`.

### PR DESCRIPTION
**Pull request by ShubhamRwt**
### Type of change

_Select the type of your PR_

- Bugfix
- Enhancement / new feature
- Refactoring
- Documentation

### Description

This PR fixed #8444. This fix adds proper error message when Cruise Control fails to generate the `rebalance` proposal. 
The error is also propagated to the  `kafkaRebalance` status. 

For eg. 

In the `KafkaRebalance` status we will get something like
```
status:
  conditions:
  - lastTransitionTime: "2023-05-05T08:08:07.066887167Z"
    message: 'Error for request: my-cluster-cruise-control.myproject.svc:9090/kafkacruisecontrol/rebalance?json=true&dryrun=true&verbose=true&skip_hard_goal_check=false&rebalance_disk=false.
      Server returned: Error processing POST request ''/rebalance'' due to: ''com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException:
      [RackAwareGoal] Insufficient number of racks to distribute each replica (Current:
      1, Needed: 3). Add at least 2 racks with brokers. Add at least 2 racks with
      brokers.''.'
    reason: CruiseControlRestException
    status: "True"
    type: NotReady
  observedGeneration: 1
```
and log will look like

```
ERROR KafkaRebalanceAssemblyOperator:880 - Reconciliation #1(kafkarebalance-watch) KafkaRebalance(myproject/my-rebalance): Cruise Control getting rebalance proposal failed
ERROR KafkaRebalanceAssemblyOperator:485 - Reconciliation #1(test-trigger) KafkaRebalance(cruise-control-namespace/my-rebalance): Status updated to [NotReady] due to error:Error for request: my-cluster-cruise-control.myproject.svc:9090/kafkacruisecontrol/rebalance?json=true&dryrun=true&verbose=true&skip_hard_goal_check=false&rebalance_disk=false.
      Server returned: Error processing POST request ''/rebalance'' due to: ''com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException:
      [RackAwareGoal] Insufficient number of racks to distribute each replica (Current:
      1, Needed: 3). Add at least 2 racks with brokers. Add at least 2 racks with
      brokers
```

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
Thanks. LGTM. Hopefully it does not screw the message in other errors.

**Review by ppatierno — APPROVED** [review]
I am fine as well, if you tested other error conditions which are still being logged fine

**Comment by kyguy** [comment]
Although the current proposed code changes will propagate this full Cruise Control error back the Cluster Operator logs and the `KafkaRebalance` resource, I notice two things:

(1) The code strays from the pattern of using `e.getCause()` that other exception propagating code uses.
(2) The code reports `CruiseControlRestException` in the `KafkaRebalance` status instead of the exception thrown by Cruise Control:  `OptimizationFailureException`

This leads me to believe the core of this issue is caused by how the Cluster Operator creates and handles exceptions it catches from Cruise Control. To resolve (1) and (2), I think we need to take a closer look at how we propagate exceptions in the `internalRebalance` method of the CruiseControlApiImpl class [1]. Maybe add a conditional clause to fail with an `OptimizationFailureException` or modify the code so that it fails with a conditon that doesn't have a `null` cause when running `e.getCause()`.

[1] https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/cruisecontrol/CruiseControlApiImpl.java#L219-L221

**Comment by ShubhamRwt** [comment]
@kyguy I agree with both the points. With the current code that we have what we do is we that if we get an error status code like `500` or some other error code we will throw `CruiseControlRestException` and in the error message we append the incoming json string from Cruise Control. I did tried to add a cause to the `CruiseControlRestException` but I was doubtful that whether we will always get `OptimizationFailureException`. The exception might differ for different errors. As per the current logic  IMO i think its fine to throw `CruiseControlRestException` instead  of the real one and get the error message but we can totally improve it @kyguy as you suggested but for that I guess we will need to first see how we can obtain the exception coming from cruise control since currently we are just getting a json response

**Comment by kyguy** [comment]
>  I did tried to add a cause to the CruiseControlRestException but I was doubtful that whether we will always get OptimizationFailureException. The exception might differ for different errors. 

It would be ideal if we could update the logic to handle the general case of any exception coming from the Cruise Control response. 

>  I guess we will need to first see how we can obtain the exception coming from cruise control since currently we are just getting a json response

From what I understand we do something similar already for `IllegalArgumentException` in the `internalRebalance` method in the CruiseControlApiImpl class linked above.

**Comment by ShubhamRwt** [comment]
Closing this since we have decided to come up with another solution

**Pull request closed without merging**
