### PR TITLE
Rolling update in ST does not work with 1 zk replica

### PR DESCRIPTION
**Pull request by stanlyDoge**
Signed-off-by: Stanislav Knot <sknot@redhat.com>

### Type of change
- Bugfix

### Description
Some tests depending on the rolling update should not use zk cluster of 1 replica. The quorum is lost during RU and the things are about to hit the fan.

Credit to @tombentley 

### Checklist

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.LogSettingST#testGcLoggingSetDisabled

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.LogSettingST#testGcLoggingSetDisabled

**Comment by tombentley** [comment]
I think we should add warn level logging to the CO when it observes a CR with ephemeral storage and replicas=1, because we _know_ that that's going to break the moment the ZK pod needs to be rolled, so we should say so somewhere the user might see it. It doesn't have to be this PR, of course.

**Comment by scholzj** [comment]
I opened #2555 for the warning - it should be done in separate PR.

**Pull request merged**
