### PR TITLE
[systemtest] Update test-clients to 0.5.2

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Enhancement

### Description

This PR updates the test-clients used in STs to `0.5.2`, which contains a fix for race condition between sending the messages and waiting for the acknowledgement - [test-clients#59](https://github.com/strimzi/test-clients/pull/59)

### Checklist

- [ ] Make sure all tests pass

### CODE REVIEW

**Review by Frawless — APPROVED** [review]

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=all testcase=MetricsIsolatedST

**Pull request merged**
