### PR TITLE
Updated bridge to 0.26.1

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Task

### Description

This PR updates the Bridge version to 0.26.1

### Checklist

- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Comment by ppatierno** [comment]
Using this PR for an early regression STs run against the bridge 0.26.1-rc1

**Review by scholzj — APPROVED** [review]

**Comment by ppatierno** [comment]
Updated to the final bridge 0.26.1 release.

**Pull request merged**
