### PR TITLE
#9734 - added toString to whole model, including Password, PasswordSe…

### PR DESCRIPTION
**Pull request by kockas**
…cretSource and PasswordSource classes

### Type of change

- Bugfix

### Description

Implementation of the issue #9734
All classes in the model package and sub-packages now contain toString generated by Lombok's `@ToString`.
Additionally:
 - each class contains generate hashCode and equals using `@EqualsAndHashCode`
 - when class has a Parent, both `@EqualsAndHashCode` and `@ToString`  are using `callSuper=true`
 - existing toString methods were removed
 - toString is also within classes `Password`, `PasswordSecretSource`, `PasswordSource` as they in fact do not contain secrets
 - class `KubernetesVersion` is left intact with manual hashCode, equals, and toString

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
It looks like the scope of the dependnecies changed:
```
[INFO] --- maven-dependency-plugin:3.3.0:analyze-only (analyze) @ api ---
[WARNING] Unused declared dependencies found:
[WARNING]    com.fasterxml.jackson.core:jackson-core:jar:2.16.1:compile
[WARNING] Non-test scoped test only dependencies found:
[WARNING]    com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.16.1:compile
```

Can you please update the `api/pom.xml` accordingly?

**Review by ppatierno — APPROVED** [review]
Thanks for the PR! LGTM and it seems regressions are all green.

**Review by scholzj — APPROVED** [review]
LGTM. Thanks for the PR.

**Pull request merged**
