### PR TITLE
Introduce Helm Chart unit tests

### PR DESCRIPTION
**Pull request by maciej-tatarski**
### Type of change

- Enhancement / new feature

### Description

Adding unit tests for helm charts.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass

### CODE REVIEW

**Comment by maciej-tatarski** [comment]
@scholzj I applied all the suggestions :)

**Review by scholzj — APPROVED** [review]
LGTM. Thanks!

**Review by im-konge — APPROVED** [review]
LGTM, thanks a lot 🙂!

**Review by ppatierno — APPROVED** [review]
LGTM. Not an Helm user/expert but the tests seem to make sense to me :-) Thanks!

**Comment by scholzj** [comment]
Thanks for the PR @maciej-tatarski

**Pull request merged**
