### PR TITLE
Add NodeIds in KafkaNodePool printer columns

### PR DESCRIPTION
**Pull request by Vince-Chenal**
### Type of change

- Enhancement

### Description

Add a new printer column for KafkaNodePool objects: NodeIds.

### Checklist

- [ ] Make sure all tests pass
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Review by scholzj — CHANGES_REQUESTED** [review]
I think the idea seems reasonable assuming it works. But in any case, you would need to build the project to generate the new CRD definitions and not just modify the Java class.

**Comment by Vince-Chenal** [comment]
Hey,
Sorry not familiar yet with this operator, I did push the CRDs and I'm currently running tests locally. Thanks :pray:

**Review by scholzj — COMMENTED** [review]
You will need to do the change tot he CRD also in the `packaging/helm/...` directory. You can run the `make crd_install` command to copy it out.

**Review by scholzj — APPROVED** [review]
Thanks.

**Comment by Vince-Chenal** [comment]
I was able to finally run the tests (acceptance+integration), which are running fine locally :+1: 
Thank you

**Review by Frawless — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]
LGTM. My only concern could be how the output will be easily screwed up with a cluster having i.e. 50 brokers and even not using an IDs range from 0 to 49 but i.e. starting from 1000 (just for having more digits). Anyway unless someone will complain, I think it's a nice to have.

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
