### PR TITLE
Updated fabric8 client dependency

### PR DESCRIPTION
**Pull request by stanlyDoge**
### Type of change
- Refactoring

### Description
There is a new version of kubernetes client (https://github.com/fabric8io/kubernetes-client/releases).

### Checklist

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests 
testcase=ConnectST#ConnectST,KafkaST#testNodePortTls,KafkaST#testSendMessagesPlainAnonymous,KafkaST#testKafkaAndZookeeperScaleUpScaleDown,KafkaST#testLoadBalancerTls,RecoveryST#RecoveryST,AllNamespaceST#testKafkaInDifferentNsThanClusterOperator,ConnectS2IST#ConnectS2IST,MirrorMakerST#testMirrorMakerTlsAuthenticated,SecurityST#testAutoRenewCaCertsTriggeredByAnno,UserST#UserST

**Comment by scholzj** [comment]
@strimzi-ci run tests
testcase=KafkaST#testNodePortTls,KafkaST#testSendMessagesPlainAnonymous,KafkaST#testKafkaAndZookeeperScaleUpScaleDown,KafkaST#testLoadBalancerTls,AllNamespaceST#testKafkaInDifferentNsThanClusterOperator,MirrorMakerST#testMirrorMakerTlsAuthenticated,SecurityST#testAutoRenewCaCertsTriggeredByAnno

**Comment by scholzj** [comment]
@strimzi-ci run tests
testcase=KafkaST#testNodePortTls,KafkaST#testSendMessagesPlainAnonymous,KafkaST#testKafkaAndZookeeperScaleUpScaleDown,KafkaST#testLoadBalancerTls,AllNamespaceST#testKafkaInDifferentNsThanClusterOperator,MirrorMakerST#testMirrorMakerTlsAuthenticated,SecurityST#testAutoRenewCaCertsTriggeredByAnno

**Comment by scholzj** [comment]
@stanlyDoge I wonder if you broker something to cause these tests to fail. I do not think all of them are flaky tests.

**Comment by stanlyDoge** [comment]
You wonder is competent. I have tried the tests locally and they are failing as well. There is some problem with websocket connection. I spent some time looking at that, but I was not able to find a reason of this behaviour.

**Comment by stanlyDoge** [comment]
The ST failures are caused by https://github.com/fabric8io/kubernetes-client/issues/1708

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests
testcase=KafkaST#testNodePortTls,KafkaST#testSendMessagesPlainAnonymous,KafkaST#testKafkaAndZookeeperScaleUpScaleDown,KafkaST#testLoadBalancerTls,AllNamespaceST#testKafkaInDifferentNsThanClusterOperator,MirrorMakerST#testMirrorMakerTlsAuthenticated,SecurityST#testAutoRenewCaCertsTriggeredByAnno

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests
testcase=ConnectS2IST#testDeployS2IWithMongoDBPlugin

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests
testcase=ConnectS2IST#testDeployS2IWithMongoDBPlugin

**Comment by stanlyDoge** [comment]
@strimzi-ci run tests
testcase=ConnectS2IST#testDeployS2IWithMongoDBPlugin

**Comment by scholzj** [comment]
@stanlyDoge I think this test is flaky. I restarted Travis and the other Jenkins test to see if they will be still passing since it is quite some time sicne we oepned this. If they do,m we should merge it.

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by stanlyDoge** [comment]
Yeah, I think it is jenkins side issue. On the local machine I am able to get this test green.

**Pull request merged**
