### PR TITLE
[ST] Unspecified namespace removal

### PR DESCRIPTION
**Pull request by jankalinic**
### Type of change

- Refactoring

### Description

This PR consists of removing and refactoring methods that work with namespace but the namespace is unspecified in parameters. Also refactoring usage of  MESSAGE_COUNT constant to be used as  testStorage.getMessageCount().

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass

### CODE REVIEW

**Review by see-quick — APPROVED** [review]
Looks good :). Just one nit...

**Review by im-konge — APPROVED** [review]
Great work! Thanks :)

**Comment by tombentley** [comment]
What's the status of this PR?

**Comment by im-konge** [comment]
@jankalinic is out this week, he will take a look at it when he get back

**Pull request merged**
