### PR TITLE
Fix CruiseControlConfigurationST.testDeployAndUnDeployCruiseControl ST

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

It looks like the PR #3997 broke the CruiseControlConfigurationST.testDeployAndUnDeployCruiseControl system test. This PR tries to fix it.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by tomncooper** [comment]
That is strange, the changes I made didn't change the access level on the `name` field so it must have been like this for a while? 

Thanks for fixing this @scholzj!

**Review by tomncooper — APPROVED** [review]

**Comment by scholzj** [comment]
@tomncooper The `name()` method works fine, but it does not return the right thing. For example `CruiseControlConfigurationParameters.METRICS_TOPIC_NAME.name()` returns the Enum name `METRICS_TOPIC_NAME` and not `cruise.control.metrics.topic` as `getName()` does.

**Comment by scholzj** [comment]
Maybe this is something what @michalxo messed up when he used the `name` variable for the value? It seems to create lot of mess by confusing `CruiseControlConfigurationParameters.name` with `Enum.name`.

Maybe it would be better to rewrtie the whole CruiseControlConfigurationParameters class? WDYT @tombentley?

**Review by ppatierno — APPROVED** [review]

**Comment by tombentley** [comment]
> Maybe this is something what @michalxo messed up when he used the `name` variable for the value? It seems to create lot of mess by confusing `CruiseControlConfigurationParameters.name` with `Enum.name`.
> 
> Maybe it would be better to rewrtie the whole CruiseControlConfigurationParameters class? WDYT @tombentley?

`name()` is inherited from `Enum`, so you can't get rid of it without changing `CruiseControlConfigurationParameters` to not be an enum. There's nothing forcing it's use as an `enum` AFAICS. You could just as easily have a non-`enum` class with a private constructor and a bunch of constants for the instances. Same for `CruiseControlGoals`, for example.

**Comment by scholzj** [comment]
@tombentley What I had in mind was not necessarily change it from being Enum but change the private field `name` in our class to for example `value` as we have it in other Enums. That way we avoid the weird and hard to read situation that `name()` returns something else then `getName()` because we have two different `name` fields with two different values.

But you are right that this does not seem to need to be Enum at all. Having just a class with `private final static String` fields would do equally well.

Or is the Enum actually needed for anything @tomncooper @michalxo?

**Comment by tomncooper** [comment]
Just my default for replacing a load of hard coded values. I'm happy to rename `name` to `value` and associated getters.

**Review by tomncooper — APPROVED** [review]

**Pull request merged**
