### PR TITLE
Fix Crds.kafkaTopic to include status subresource

### LINKED ISSUE #10905: Crds.kafkaTopic does not set status subresource
The Crds.kafkaTopic method does not create and set the status subresource for KafkaTopic definition as is done for the other types. If this is not intended, I'll open a PR to add it.

https://github.com/strimzi/strimzi-kafka-operator/blob/5de77261ebc6a8869f46594f5e9277e63f618bcb/api/src/main/java/io/strimzi/api/kafka/Crds.java#L93-L100

### PR DESCRIPTION
**Pull request by MikeEdgar**
### Type of change

Bugfix
Fixes #10905 

### Description

Update Crds.crd for KafkaTopic to create the `status` subresource

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by MikeEdgar** [comment]
Adding a test for this seemed like overkill and there doesn't seem to be a place to add without creating something new. I'm not sure this merits an entry in the CHANGELOG either (unless it's for every change). Let me know and I'll do it if needed.

**Review by scholzj — APPROVED** [review]
Thanks.

**Comment by MikeEdgar** [comment]
So I see some tests failing in `TopicControllerIT`, but I don't see a connection to the change. Is this known to be flaky at times?

```
[ERROR] Failures: 
[ERROR] io.strimzi.operator.topic.TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube
[ERROR]   Run 1: TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube:880->shouldUpdateTopicInKafkaWhenConfigChangedInKube:871 expected: <{compression.type=snappy, cleanup.policy=compact, flush.ms=1234, index.interval.bytes=1234, min.cleanable.dirty.ratio=0.6, unclean.leader.election.enable=true}> but was: <{compression.type=producer, cleanup.policy=compact, flush.ms=1234, min.cleanable.dirty.ratio=0.6, index.interval.bytes=1234, unclean.leader.election.enable=true}>
[ERROR]   Run 2: TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube:880->shouldUpdateTopicInKafkaWhenConfigChangedInKube:871 expected: <{compression.type=snappy, cleanup.policy=compact, flush.ms=1234, index.interval.bytes=1234, min.cleanable.dirty.ratio=0.6, unclean.leader.election.enable=true}> but was: <{compression.type=producer, cleanup.policy=compact, flush.ms=1234, min.cleanable.dirty.ratio=0.6, index.interval.bytes=1234, unclean.leader.election.enable=true}>
[ERROR]   Run 3: TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube:880->shouldUpdateTopicInKafkaWhenConfigChangedInKube:871 expected: <{compression.type=snappy, cleanup.policy=compact, flush.ms=1234, index.interval.bytes=1234, min.cleanable.dirty.ratio=0.6, unclean.leader.election.enable=true}> but was: <{compression.type=producer, cleanup.policy=compact, flush.ms=1234, min.cleanable.dirty.ratio=0.6, index.interval.bytes=1234, unclean.leader.election.enable=true}>

```

**Review by ppatierno — APPROVED** [review]

**Comment by see-quick** [comment]
> So I see some tests failing in `TopicControllerIT`, but I don't see a connection to the change. Is this known to be flaky at times?
> 
> ```
> [ERROR] Failures: 
> [ERROR] io.strimzi.operator.topic.TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube
> [ERROR]   Run 1: TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube:880->shouldUpdateTopicInKafkaWhenConfigChangedInKube:871 expected: <{compression.type=snappy, cleanup.policy=compact, flush.ms=1234, index.interval.bytes=1234, min.cleanable.dirty.ratio=0.6, unclean.leader.election.enable=true}> but was: <{compression.type=producer, cleanup.policy=compact, flush.ms=1234, min.cleanable.dirty.ratio=0.6, index.interval.bytes=1234, unclean.leader.election.enable=true}>
> [ERROR]   Run 2: TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube:880->shouldUpdateTopicInKafkaWhenConfigChangedInKube:871 expected: <{compression.type=snappy, cleanup.policy=compact, flush.ms=1234, index.interval.bytes=1234, min.cleanable.dirty.ratio=0.6, unclean.leader.election.enable=true}> but was: <{compression.type=producer, cleanup.policy=compact, flush.ms=1234, min.cleanable.dirty.ratio=0.6, index.interval.bytes=1234, unclean.leader.election.enable=true}>
> [ERROR]   Run 3: TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube:880->shouldUpdateTopicInKafkaWhenConfigChangedInKube:871 expected: <{compression.type=snappy, cleanup.policy=compact, flush.ms=1234, index.interval.bytes=1234, min.cleanable.dirty.ratio=0.6, unclean.leader.election.enable=true}> but was: <{compression.type=producer, cleanup.policy=compact, flush.ms=1234, min.cleanable.dirty.ratio=0.6, index.interval.bytes=1234, unclean.leader.election.enable=true}>
> ```

Yeah, this test case is currently flaky.

**Comment by fvaleri** [comment]
> > So I see some tests failing in `TopicControllerIT`, but I don't see a connection to the change. Is this known to be flaky at times?
> > ```
> > [ERROR] Failures: 
> > [ERROR] io.strimzi.operator.topic.TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube
> > [ERROR]   Run 1: TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube:880->shouldUpdateTopicInKafkaWhenConfigChangedInKube:871 expected: <{compression.type=snappy, cleanup.policy=compact, flush.ms=1234, index.interval.bytes=1234, min.cleanable.dirty.ratio=0.6, unclean.leader.election.enable=true}> but was: <{compression.type=producer, cleanup.policy=compact, flush.ms=1234, min.cleanable.dirty.ratio=0.6, index.interval.bytes=1234, unclean.leader.election.enable=true}>
> > [ERROR]   Run 2: TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube:880->shouldUpdateTopicInKafkaWhenConfigChangedInKube:871 expected: <{compression.type=snappy, cleanup.policy=compact, flush.ms=1234, index.interval.bytes=1234, min.cleanable.dirty.ratio=0.6, unclean.leader.election.enable=true}> but was: <{compression.type=producer, cleanup.policy=compact, flush.ms=1234, min.cleanable.dirty.ratio=0.6, index.interval.bytes=1234, unclean.leader.election.enable=true}>
> > [ERROR]   Run 3: TopicControllerIT.shouldUpdateTopicInKafkaWhenStringConfigChangedInKube:880->shouldUpdateTopicInKafkaWhenConfigChangedInKube:871 expected: <{compression.type=snappy, cleanup.policy=compact, flush.ms=1234, index.interval.bytes=1234, min.cleanable.dirty.ratio=0.6, unclean.leader.election.enable=true}> but was: <{compression.type=producer, cleanup.policy=compact, flush.ms=1234, min.cleanable.dirty.ratio=0.6, index.interval.bytes=1234, unclean.leader.election.enable=true}>
> > ```
> 
> Yeah, this test case is currently flaky.

Are we tracking this somewhere? I may look into it.

**Pull request merged**
