### PR TITLE
[systemtest] Add creation of /tmp/keycloak dir to the script

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Description

In #3621 I forgot that `/tmp/...` folder is not created on all devices (especially on the Azure), so in this PR I'm adding the creation to the script.

### CODE REVIEW

**Comment by scholzj** [comment]
So what is the plan for fixing it?

**Comment by im-konge** [comment]
@scholzj I guess there is some problem on Azure, because on our pipelines it passes all time. So I will disable it here and then fix it.

**Review by Frawless — APPROVED** [review]
Maybe put there a comment why it's needed?

**Comment by scholzj** [comment]
This is not Azure only issue ... it doesn't work for me locally either. The problem is in Keycloak and in the Red Hat registry it is pulling from. So I think we need to have an idea how to fix it and not just disable it.

**Comment by im-konge** [comment]
@scholzj okay, working on fix. Converting to draft.

**Review by Frawless — APPROVED** [review]

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=acceptance testcase=OauthTlsST test_only

**Review by scholzj — APPROVED** [review]

**Pull request merged**
