### PR TITLE
[MO] - [system test] -> eliminate un-necessary CO creation and deletion

### PR DESCRIPTION
**Pull request by see-quick**
Signed-off-by: morsak <xorsak02@stud.fit.vutbr.cz>

### Type of change

_Select the type of your PR_

- Bugfix
- Enhancement / new feature

### Description

This PR fixes unnecessary creation ∧ deletion of ClusterOperator, where one can execute only one test case in `@IsolatedSuite`. This means that CO will delete itself (because @IsolatedSuite has a different configuration). 

#### Problem 1 (`@BeforeSuite, @BeforeAll`)

When we are in @IsolatedSuite the current process is:
1. Shared ClusterOperator is deployed (with default configuration)  <- unnecessary
2. Shared ClusterOperator is deleted (with default configuration). <- unnecessary
3. Shared ClusterOperator (with specific configuration)

Now, this is resolved by checking extension context where we have information about test suite annotation and if that test suite has `@ParallelSuite` annotation we deploy shared Cluster Operator (because ∀ these suites have the same CO configuration and no one will change that). If we invoke @IsolatedSuite from the start the un-installation part is skipped because we are gonna deploy Shared ClusterOperator with a specific configuration. 

#### Problem 2  (`@AfterSuite, @AfterAll`)

When we are in @IsolatedSuite and this suite is also last the current process is:
1. Shared ClusterOperator is deleted (with specific configuration) 
2. Shared ClusterOperator is created (with default configuration) <- unnecessary
3. Shared ClusterOperator deleted (with default configuration). <- unnecessary

This is solved by the additional predicate isLastSuite() in `ExecutionListener`, which we call `@AfterAll`. With such change when one invokes @IsolatedSuite and we know that this @IsolatedSuite is last to be executed then it will not create Shared Cluster Operator with default configuration (which is unnecessary). For @ParallelSuite this is implicit because condition [1] will not be true (configurations are the same :))

Condition [1] -
```java
if (clusterOperator != null &&
!clusterOperator.defaultInstallation().createInstallation().equals(clusterOperator) &&
!ExecutionListener.isLastSuite(extensionContext))
```
#### Optimalization (Chaining of @IsolatedSuites)
Resolved by `io.strimzi.systemtest.listeners.ExecutionListener.isNextSuiteIsolated(...)` method
image

----
Lastly, I have modified `testRecoveryFromImpossibleMemoryRequest` test case, because it was using its own Kafka cluster, which was redundant instead of using a shared Kafka cluster in that suite :) 

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only test_count_running_in_parallel=4

**Review by Frawless — APPROVED** [review]

**Review by im-konge — APPROVED** [review]

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only test_count_running_in_parallel=4

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only test_count_running_in_parallel=4

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only test_count_running_in_parallel=4

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only test_count_running_in_parallel=4

**Pull request merged**
