### PR TITLE
Refactoring listing the artifacts map

### PR DESCRIPTION
**Pull request by ppatierno**
Trivial PR to refactor how going through the artifacts map.

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
Not sure what value does this add. But I guess why not.

**Comment by ppatierno** [comment]
I see it as more readable and in the end also fixes an IDE warning about listing the map this way.

**Review by im-konge — APPROVED** [review]

**Comment by ppatierno** [comment]
Going to merge because the regression failures are not related to these changes. See https://github.com/strimzi/strimzi-kafka-operator/pull/7623

**Pull request merged**
