### PR TITLE
[systemtest] Use Jaeger files from local ST's resources

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Enhancement

### Description

To prevent issues with downloading yaml files from GH, we should use local ones in `resources` folder of `systemtest` package. This PR adds this files for Jaeger operator.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by Frawless — APPROVED** [review]

**Comment by Frawless** [comment]
is this something that we should cherry-pick into `release-0.22.x`?

**Comment by im-konge** [comment]
Well I guess we can cherry-pick it, but it's just a little enhancement. I'll leave it up to you

**Review by scholzj — APPROVED** [review]

**Pull request merged**
