### PR TITLE
feat: Clean the /tmp directory when the kafka container restarts

### PR DESCRIPTION
**Pull request by karolcienkosz**
### Type of change

_Select the type of your PR_

- Bugfix
**- Enhancement / new feature**
- Refactoring
- Documentation

### Description

clean /tmp directory when kafka container restarts

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
LGTM. Thanks for the PR.

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks for the PR!

**Review by see-quick — APPROVED** [review]
👍

**Pull request merged**
