### PR TITLE
added values for tolerations, affinity and nodeselector

### PR DESCRIPTION
**Pull request by zivi-dodis**
### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

Added empty values to define nodeSelector, affinity and tolerations

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [n/a] Update/write design documentation in `./design`
- [n/a] Write tests
- [n/a] Make sure all tests pass
- [x] Update documentation
- [n/a] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [n/a] Reference relevant issue(s) and close them after merging
- [?] Update CHANGELOG.md

### CODE REVIEW

**Comment by zivi-dodis** [comment]
related, though not completely covering my issue: #2095

**Comment by scholzj** [comment]
Travis seems to be a bit confused - this passed the tests in this build: https://travis-ci.org/strimzi/strimzi-kafka-operator/builds/598607168

**Comment by scholzj** [comment]
@zivi-dodis You marked it as `WIP:` in the PR name ... do you plan to do something more? Or can I merge it?

**Comment by scholzj** [comment]
Ok, great. I will merge it then. Thanks for the PR.

**Pull request merged**
