### PR TITLE
[ST] Fix bridge client network policies creation

### PR DESCRIPTION
**Pull request by jankalinic**
### Type of change

- Refactoring

### Description

This pull request addresses the system test failure for Kafka bridge clients caused by the enabled default denial of network accessibility. The fix introduces network policy creation methods specific to the bridge client which is being deployed, enabling communication required for system testing.

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by im-konge — APPROVED** [review]

**Comment by jankalinic** [comment]
@strimzi-ci run tests --cluster-type=ocp --cluster-version=4.14  --install-type=bundle --testcase=HttpBridgeST,HttpBridgeScramShaST,HttpBridgeTlsST,HttpBridgeKafkaExternalListenersST --env=STRIMZI_KRAFT_ENABLED=true

**Comment by jankalinic** [comment]
@strimzi-ci run tests --cluster-type=ocp --cluster-version=4.14 --install-type=bundle --testcase=MetricsST,OauthTlsST,OauthPlainST,OauthPasswordGrantsST --env=STRIMZI_KRAFT_ENABLED=true

**Review by henryZrncik — APPROVED** [review]

**Comment by jankalinic** [comment]
re-requesting reviews due to changes being made for metrics ST, where scraper could not access bridge

**Comment by jankalinic** [comment]
@strimzi-ci run tests --cluster-type=ocp --cluster-version=4.14 --install-type=bundle --testcase=MetricsST,OauthTlsST,OauthPlainST,OauthPasswordGrantsST --env=STRIMZI_KRAFT_ENABLED=true

**Comment by jankalinic** [comment]
3 failing tests - all because of keycloak setup - not related to this PR

**Review by henryZrncik — APPROVED** [review]

**Pull request merged**
