### PR TITLE
Remove generateBuilderPackage

### PR DESCRIPTION
**Pull request by stanlyDoge**
Signed-off-by: Stanislav Knot <sknot@redhat.com>

### Type of change
- Refactoring

### Description
Fixes https://github.com/strimzi/strimzi-kafka-operator/issues/2714

### Checklist
- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by samuel-hawker** [comment]
This might be overkill, but might it be worth contributing a test to ensure that no newly added classes have this annotation field set?

**Comment by stanlyDoge** [comment]
Maybe I named the PR wrong. It is not about definitely getting rid of this field. Its default value is `false` so setting it to `false` was redundant. That is why it can be removed from model classes.

**Comment by samuel-hawker** [comment]
Thanks for the clarification!

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
