### PR TITLE
Switch for cluster-scoped resources

### PR DESCRIPTION
**Pull request by weargoggles**
### Type of change

- Enhancement / new feature

### Description

This is intended for a multi-tenant setup where the roles and crds are
provisioned by a cluster owner but the operator is installed by an
unprivileged tenant. In such a setup all the roles are granted as
namespace-scoped RoleBindings which reduces the privileges granted to
the Strimzi-owning tenant.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by scholzj** [comment]
@weargoggles I realised only too late that some of these files (the CRDs) are autogenerated. I pushed in a change which will generate them if the conditional. Now the CI should pass.

**Comment by scholzj** [comment]
@tombentley As I did some of the changes, could you please review this?

**Comment by tombentley** [comment]
@scholzj I'm a bit concerned that `CrdGenerator`, which started out as being simply about generating a CRD, is gaining more knowledge of Helm stuff. I wonder if really the solution here is not to change the `CrdGenerator`, but simply how we drive it from the `pom.xml`. What if we use the exec plugin to run a script which `cat`s together the header the YAML and footer?

**Comment by scholzj** [comment]
@tombentley Using the `exec` plugin was my first thought. But what would you use to keep it multi-platform? Does `cat` exist on Windows? I don't think so, or?

**Comment by tombentley** [comment]
`type` [apparently](https://superuser.com/questions/434870/what-is-the-windows-equivalent-of-the-unix-command-cat).

**Comment by scholzj** [comment]
@tombentley Well, I can give it a try if you want. But AFAIK we will need someone to test it on Windows and we will end up needing to detect the operating system and run different commands on different operating systems. Even through `type` seems to be universal, I'm not sure you can do the whole chain including temporary files etc as universal.

**Comment by scholzj** [comment]
@tombentley Ok, should be now handled by make and ready for another review ;-)

**Comment by scholzj** [comment]
@strimzi-ci run tests tags=acceptance

**Comment by scholzj** [comment]
@tombentley It still does and we use it to add the `app:strimzi` label. But we do not generate the CRDs for Helm anymore through the CRD Generator. The CRD Generator now only generates the CRDs in `install/cluster-operator`. Therefore we need to add the Helm labels in `make` when copying the files.

**Comment by tombentley** [comment]
Ah, OK if we're still using it that's fine.

**Comment by scholzj** [comment]
@weargoggles Thanks for the PR. I'm going to merge it.

**Pull request merged**
