### PR TITLE
[ST] Upgrade tests methodsource + generated test name

### PR DESCRIPTION
**Pull request by kornys**
Signed-off-by: David Kornel <kornys@outlook.com>

### Type of change

- Refactoring

### Description

1. Set up surefire/failsafe to use displayname in xunit files
2. Using  junit jupiter methodsource for parametrized upgrade tests instead of 3rd party lib
3. Generating names for upgrade parametrized test

### CODE REVIEW

**Review by scholzj — APPROVED** [review]

**Comment by kornys** [comment]
@strimzi-ci run tests profile=upgrade test_only

**Review by Frawless — APPROVED** [review]

**Comment by kornys** [comment]
Issues are not caused by this PR but jenkins env issues.

**Comment by kornys** [comment]
Also there is parf of xunit file generated by failsafe and tests are correctly named so we can easily identify upgrade test failure for specific version from testname
```
<testcase name="testUpgradeStrimziVersion-0.12.1-0.13.0" classname="io.strimzi.systemtest.upgrade.StrimziUpgradeST" time="2,715.949"/>
  <testcase name="testUpgradeStrimziVersion-0.13.0-0.14.0" classname="io.strimzi.systemtest.upgrade.StrimziUpgradeST" time="1,242.575"/>
  <testcase name="testUpgradeStrimziVersion-0.14.0-0.15.0" classname="io.strimzi.systemtest.upgrade.StrimziUpgradeST" time="1,629.396"/>
  <testcase name="testUpgradeStrimziVersion-0.15.0-0.16.2" classname="io.strimzi.systemtest.upgrade.StrimziUpgradeST" time="2,485.258">
```

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
