### PR TITLE
[DOC] Upgrade procedure for cooperative rebalancing in Kafka 2.4.0

### PR DESCRIPTION
**Pull request by laidan6000**
### Type of change

- Documentation

### Description

Adds a new procedure for "Upgrading consumers and Kafka Streams applications to cooperative rebalancing" to the "Upgrading Kafka" assembly.

Upgrading consumers and Streams apps to the new _incremental cooperative rebalance_ protocol is an optional step in upgrades to Kafka 2.4.0, which is supported in Strimzi 0.17.0.

Once merged, this PR should be cherry-picked to Strimzi 0.17.0.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [X] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [X] Reference relevant issue(s) and close them after merging // NO ISSUES FOUND
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by Frawless** [comment]
I didn't find any issues.

**Comment by laidan6000** [comment]
Ready for merging and cherry-picking. The Travis build is orange but I think it has actually passed.

**Comment by scholzj** [comment]
Thanks for the PR @laidan6000

**Comment by laidan6000** [comment]
@scholzj - Please can you cherry-pick this change to the 0.17.0 release?

**Comment by scholzj** [comment]
@laidan6000 I did that already yesterday, just forgot to push it. Should be done now. Thanks for reminding me.

**Comment by laidan6000** [comment]
Thank you. I should be doing it myself really.

**Pull request merged**
