### PR TITLE
Enabling all Vert.x JVM related metrics through options

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Refactoring

In order to enable all the JVM related metrics exported by Vert.x, it's just needed calling `.setJvmMetricsEnabled(true)` on the Vert.x options.
The current used `setupMetrics()` method with the related content is not needed.
When that flag is enabled in the Vert.x options, the code which Vert.x runs is the following:

```java
if (options.isJvmMetricsEnabled()) {
      new ClassLoaderMetrics().bindTo(backendRegistry.getMeterRegistry());
      new JvmMemoryMetrics().bindTo(backendRegistry.getMeterRegistry());
      new JvmGcMetrics().bindTo(backendRegistry.getMeterRegistry());
      new ProcessorMetrics().bindTo(backendRegistry.getMeterRegistry());
      new JvmThreadMetrics().bindTo(backendRegistry.getMeterRegistry());
}
```

which is actually the same of the `setupMetrics()`.
This PR does this refactoring.

_Please describe your pull request_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.MetricsST

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.MetricsST

**Comment by ppatierno** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.MetricsST

**Comment by ppatierno** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.MetricsST

**Comment by ppatierno** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.metrics.MetricsST

**Comment by ppatierno** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.metrics.MetricsST

**Comment by ppatierno** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.metrics.MetricsST

**Comment by ppatierno** [comment]
@strimzi-ci run tests profile=regression testcase=io.strimzi.systemtest.metrics.MetricsST

**Pull request merged**
