### PR TITLE
Add support for node pools to the report script

### PR DESCRIPTION
**Pull request by fvaleri**
Tested on bash 5 and bash 4 (the older is what we document).
I also ran the script with and without NodePools and also the experimental KRaft mode.
Added a check on bash version.

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
LGTM. And seems to work fine on MacOS. Thanks for the PR @fvaleri!

**Comment by ppatierno** [comment]
Not related with these changes, but should we remove the `statefulsets` from the list of resources? As per 0.35.0 release we don't have support for them anymore.

**Comment by ppatierno** [comment]
Still not related to these changes but if I try with a not existing namespace, this code seems not working:

```shell
if [[ $($KUBE_CLIENT get ns "$NAMESPACE" &>/dev/null) == "1" ]]; then
  error "Namespace $NAMESPACE not found! Exiting"
fi
```

Good namespace but wrong cluster name works as expected instead.

**Comment by scholzj** [comment]
> Not related with these changes, but should we remove the statefulsets from the list of resources? As per 0.35.0 release we don't have support for them anymore.

We do not version this script. So it will be used wth older versions as well. So I would keep the StatefulSets for few more releases.

> Still not related to these changes but if I try with a not existing namespace, this code seems not working

This seems to be in the original code as well. So not sure we want to fix it in this PR. But I also get errors about a non-existent Kafka cluster and not about a non-existing namespace.

**Review by ppatierno — APPROVED** [review]
LGTM.

**Comment by ppatierno** [comment]
> @ppatierno this is an easy fix, let me push it. Thanks for raising.

Thanks! Tried and works ;-)

**Pull request merged**
