### PR TITLE
docs(metrics): Use the same name as used in ConfigMap for name/key in configMapKeyRef

### PR DESCRIPTION
**Pull request by tgib23**
### Type of change

- Documentation

### Description

The sample yaml in metrics doc uses different name/key for ConfigMap and Kafka configuration.
It's better to use the same name/key.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. The change makes sense. But can you please fix the DCO signoff? The instructions can be found under the _Details_ link next to the DCO status in the status section of the PR.

**Comment by tgib23** [comment]
@scholzj thanks! just fix the DCO.

**Review by scholzj — APPROVED** [review]
Great, thanks.

**Review by PaulRMellor — APPROVED** [review]
Thanks for the update. :+1:

**Pull request merged**
