### PR TITLE
Fix for broken link to TESTING.md

### PR DESCRIPTION
**Pull request by STEPHINRACHEL**
### Type of change

- Documentation

### Description

Fix for a broken link in the documentation

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by STEPHINRACHEL** [comment]
ping @Frawless

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
@STEPHINRACHEL Could you please fix the DCO signoff? The instructions should be under the _Details_ link next to the DCO in the status section. It should be something like:

```
git commit --amend --signoff
git push --force-with-lease origin Update-Doc
```

**Review by ppatierno — APPROVED** [review]

**Comment by STEPHINRACHEL** [comment]
@scholzj  Is the merging has to be done manually or automation would do that after all the checks have passed?

**Review by Frawless — APPROVED** [review]

**Comment by Frawless** [comment]
@STEPHINRACHEL Someone from the maintainers group will merge it when all checks will pass and PR will have label `ready for merge`. Thanks for the pr.

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
