### PR TITLE
Refactoring: add STRIMZI_DNS_CACHE_TTL to ClusterOperatorConfig

### PR DESCRIPTION
**Pull request by fvaleri**
No change in behavior.

### CODE REVIEW

**Review by scholzj — CHANGES_REQUESTED** [review]
Why are you changing it in a backwards incompatible way?

**Comment by fvaleri** [comment]
> Why are you changing it in a backwards incompatible way?

Do you mean seconds vs millis right?

**Comment by scholzj** [comment]
> Do you mean seconds vs millis or variable name?

Well, it is both really. I'm not sure if this option needs to be formalized - I do not remember using or needing it for a long time. But if we do it, we might want to do it in a backwards compatible fashion and keek the old name and format.

**Comment by scholzj** [comment]
Apart from that, an explanation when to use it wld be good for the docs I guess.

**Comment by fvaleri** [comment]
Sure let me fix that, thanks.

**Review by scholzj — APPROVED** [review]
Thanks for the PR. LGTM

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
