### PR TITLE
Remove the unused Entity Operator TLS sidecar configuration from the installation files, Helm Chart and docs

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

#9840 added a warning message when the EO TLS sidecar image is configured. But unfortunately did not remove the actual configuration. This PR finishes the work and removes the environment variable from the configuration.

This needs to be cherry-picked into the 0.41 release branch.

### Checklist

- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Update documentation

### CODE REVIEW

**Review by see-quick — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Review by fvaleri — APPROVED** [review]

**Review by PaulRMellor — APPROVED** [review]
Thanks. Looks good.

**Pull request merged**
