### PR TITLE
Push images into minikube internal registry in case of images are built during PR job

### PR DESCRIPTION
**Pull request by Frawless**
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

### Type of change

- Bugfix

### Description

When we started using minikube internal registry, we kinda forgot to enhance the image build for PR job. This PR does it.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke

**Review by scholzj — APPROVED** [review]

**Review by im-konge — APPROVED** [review]

**Pull request merged**
