### PR TITLE
Tests - rename cert with expired prefix

### PR DESCRIPTION
**Pull request by michalxo**
Simple rename of static expired certificates, which are used in tests

### CODE REVIEW

**Comment by michalxo** [comment]
@strimzi-ci run tests true profile=regression testcase=io.strimzi.systemtest.security.SecurityST#testAutoRenewCaCertsTriggerByExpiredCertificate,io.strimzi.systemtest.security.SecurityST#testCaRenewalBreakInMiddle,io.strimzi.systemtest.connectConnectS2IST#testChangeConnectS2IConfig

**Comment by michalxo** [comment]
@see-quick do you think there are some other security related tests that might use these expired certificates? I haven't found any other tests.
Could anyone please fire up azure pipelines? 
Thanks

**Review by scholzj — COMMENTED** [review]
Shouldn't the expired cert be generated as well? Or is that not possible?

**Comment by michalxo** [comment]
> Shouldn't the expired cert be generated as well? Or is that not possible?

IMO it does not give any benefit to currently used tests, to generate dynamically invalid certificate. (But I might be wrong for some specific use cases..)
I also seen similar story with `operator-common/src/test/java/io/strimzi/operator/common/operator/MockCertManager.java` but it's stored as a string instead of file.

**Review by scholzj — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Review by see-quick — APPROVED** [review]

**Pull request merged**
