### PR TITLE
docs: change using guide to configuring guide

### PR DESCRIPTION
**Pull request by PaulRMellor**
Signed-off-by: prmellor <pmellor@redhat.com>

**Documentation**

Changes _Using Strimzi_ guide to _Configuring Strimzi_ guide

**Using guide changes**
Changes name to _Configuring Strimzi_
Updates to the _Overview_ section:
- Title: Configuration overview
- introduction updated
- new Configuring custom resources section section to introduce config concepts
- new additional resources section that links to Overview and Deploying guides
- removes Kafka capabilities and Kafka use cases (con-key-features-kafka.adoc) – described in Overview
- removes How Strimzi supports Kafka (con-key-features-product.adoc) – described in Overview
- removes Strimzi Operators (assembly-overview-components.adoc and modules) – described in Overview
- removes Strimzi custom resources and  Strimzi custom resource example (assembly-deploy-intro-custom-resources.adoc) – described in Deploying

**Deploying guide changes**
Updates to the  _Deployment overview_  section:
- introduction updated
- new additional resources section that links to Overview and Configuring guides
- removes How Strimzi supports Kafka (con-key-features-product.adoc) – described in Overview
- removes Strimzi Operators (assembly-overview-components.adoc and modules) – described in Overview

**General changes**
updates references to _Strimzi Using guide_

**Out of scope**
- change {BookURLUsing} to {BookURLConfig} (for separate PR)
- Spin off api reference into a separate guide

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
I guess it looks good for what it says it does. I wonder if we thought properly through how the documentation should look like. I have a feeling that we will be renaming it soon again because we are missing a clearer plan how should the documentation look like. But I guess I'm fine if we want to merge it.

A sidenote for the out-of-scope points => this doesn't change much really because on the website, this still appears as Using Strimzi.

**Comment by PaulRMellor** [comment]
> I guess it looks good for what it says it does. I wonder if we thought properly through how the documentation should look like. I have a feeling that we will be renaming it soon again because we are missing a clearer plan how should the documentation look like. But I guess I'm fine if we want to merge it.
> 
> A sidenote for the out-of-scope points => this doesn't change much really because on the website, this still appears as Using Strimzi.

_Using_ didn't mean much. Most of the content in this guide relates to configuration. I think _Configuring_ is a more appropriate title. And I don't think that will change. The only change might be content related to, say, _monitoring_ or _client development_ moving out.

**Review by tombentley — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
@PaulRMellor Looks like the build is failing. I don't think it can be merged as it is. You will need to either:
* Update the CI and the website
* Rename only the titled but leave the old name of all files

**Comment by PaulRMellor** [comment]
@scholzj  I updated the makefile for this PR
For the web pages, I opened this WIP PR https://github.com/strimzi/strimzi.github.io/pull/276

**Pull request merged**
