### PR TITLE
[MO] - [refactor] -> junit tags

### PR DESCRIPTION
**Pull request by see-quick**
Signed-off-by: morsak <xorsak02@stud.fit.vutbr.cz>

### Type of change

- Enhancement / new feature
- Refactoring

### Description

This PR changing the way how we define `@Tag` in your test suites. All are replaced by wrapper `@Tags`. More info here https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Tags.html

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only profile=oauth

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only profile=oauth

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only

**Comment by scholzj** [comment]
Out of curiosity ... what is the advantage of this?

**Pull request closed without merging**
