### PR TITLE
Promote StableConnectIdentities feature gate to GA

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Task

### Description

That `stableConnectIdenttiies` feature gate should be promoted to GA in Strimzi 0.39.0. This is done in this PR. It removes the feature gate and support for the Deployments in Connect and MM2. It also updates all the tests => removed the Deployment based tests but makes sure the originally covered features are covered also with PodSets.

It does also some basic updates to System tests:
* Removes the on-off test in FeatureGatesST
* Upgrades other tests to work with the feature gate being GA

Other ST improvements might be possible in the future in separate PR. Documentation will be updated in a separate PR as well.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by ppatierno — APPROVED** [review]
LGTM

**Review by im-konge — APPROVED** [review]
LGTM, thanks for the changes in STs :)

**Pull request merged**
