### PR TITLE
Add support for Kafka 2.3 and update Kafka dependency to 2.3

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

This PR adds support for Kafka 2.3.0 and updates our own Kafka dependencies to 2.3.0.

### Checklist

- [x] Make sure all tests pass
- [x] Update documentation
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by scholzj** [comment]
@strimzi-ci run tests testcase=KafkaST#testSendMessagesPlainAnonymous,KafkaST#testLoadBalancerTls,KafkaST#testSendMessagesPlainScramSha,UserST#testUpdateUser,AllNamespaceST#testKafkaInDifferentNsThanClusterOperator

**Comment by scholzj** [comment]
@ppatierno I was thinking about it. But I decided to leave it out. I still think we should have some plan on when and how to do it - so we should discuss it next week. For example - should we remove 2.1.x and keep both 2.2.x? Or should we keep 2.1.1 and 2.2.1 and remove the _.0_ versions? Or should we remove 2.1.x and 2.2.0? So it was not completely clear to me what to do and wanted to avoid long discussion here. Doing that in separate PR should be trivial.

**Comment by ppatierno** [comment]
@scholzj good point. I didn't think in this way, so yeah let's discuss it in the coming days.

**Comment by scholzj** [comment]
@strimzi-ci run tests testcase=KafkaST#testSendMessagesPlainAnonymous,KafkaST#testSendMessagesPlainScramSha,UserST#testUpdateUser

**Comment by scholzj** [comment]
@strimzi-ci run tests testcase=KafkaST#testSendMessagesPlainAnonymous,KafkaST#testSendMessagesPlainScramSha

**Comment by scholzj** [comment]
@strimzi-ci run tests testcase=KafkaST#testSendMessagesPlainAnonymous,KafkaST#testSendMessagesPlainScramSha

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by scholzj** [comment]
@strimzi-ci run tests testcase=RecoveryST#testRecoveryFromKafkaStatefulSetDeletion,RecoveryST#testRecoveryFromZookeeperStatefulSetDeletion,AllNamespaceST#testKafkaInDifferentNsThanClusterOperator

**Comment by scholzj** [comment]
@strimzi-ci run tests testcase=RecoveryST#testRecoveryFromKafkaStatefulSetDeletion,RecoveryST#testRecoveryFromZookeeperStatefulSetDeletion

**Pull request merged**
