### PR TITLE
[systemtests] Fix failed tests from nightly job - FileSink

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lkral@redhat.com>

### Type of change
- Bugfix

### Description

Fix failed tests from nightly job

Add missing converters for FileSink.
Edit message count.

### Checklist
- [x] Write tests
- [x] Make sure all tests pass

### CODE REVIEW

**Comment by im-konge** [comment]
@strimzi-ci run tests profile=regression testcase=ConnectST#testKafkaConnectWithPlainAndScramShaAuthentication+testKafkaConnectWithFileSinkPlugin+testSecretsWithKafkaConnectWithTlsAndTlsClientAuthentication+testSecretsWithKafkaConnectWithTlsAndScramShaAuthentication

**Comment by im-konge** [comment]
@strimzi-ci run tests profile=regression testcase=ConnectST#testKafkaConnectWithPlainAndScramShaAuthentication+testKafkaConnectWithFileSinkPlugin+testSecretsWithKafkaConnectWithTlsAndTlsClientAuthentication+testSecretsWithKafkaConnectWithTlsAndScramShaAuthentication test_only

**Comment by im-konge** [comment]
@strimzi-ci run tests profile=regression testcase=TracingST#testConnectS2IService test_only

**Comment by im-konge** [comment]
@strimzi-ci run tests profile=regression testcase=ConnectS2IST#testSecretsWithKafkaConnectS2IWithTlsAndScramShaAuthentication test_only

**Comment by Frawless** [comment]
Cherry-pick to `release-0.17.x` please

**Pull request merged**
