### PR TITLE
Update example for kafka and kafka-connect metric rules

### PR DESCRIPTION
**Pull request by VladimirYushkevich**
### Type of change

- Refactoring

### Description

Examples for kafka and kafka-connect metrics rules are not up to date.
In this PR updated prometheus rules according to recent changes: https://github.com/prometheus/jmx_exporter/pull/464
https://github.com/prometheus/jmx_exporter/pull/473

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by scholzj** [comment]
@VladimirYushkevich Thanks for the PR. How does thi simpact the Grafana dashboards?

**Comment by VladimirYushkevich** [comment]
@scholzj It shouldn't affect Zookeeper 's grafana dashboard since the type is only added. 
I think it shouldn't affect kafka-connect's dashboard too but this I can check.

**Comment by VladimirYushkevich** [comment]
@scholzj I checked and updated kafka-connect dashboard accordingly.

**Comment by VladimirYushkevich** [comment]
@ppatierno Thanks for your comment. Yes. I updated `mirror-maker` grafana dashboards too.

**Comment by scholzj** [comment]
Thanks a lot for the PR @VladimirYushkevich

**Comment by VladimirYushkevich** [comment]
You are welcome.

**Pull request merged**
