### PR TITLE
Updated bridge to 0.29.0

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Task

### Description

This PR updates the Bridge version to 0.29.0

### Checklist

- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Comment by ppatierno** [comment]
Using this PR for an early regression STs run against the bridge 0.29.0 release candidates.

**Review by scholzj — CHANGES_REQUESTED** [review]
You should update the version in `attributes.adoc` as well.

**Comment by ppatierno** [comment]
> You should update the version in attributes.adoc as well.

Updated + CHANGELOG as well.

**Review by scholzj — APPROVED** [review]

**Review by im-konge — APPROVED** [review]

**Review by see-quick — APPROVED** [review]

**Pull request merged**
