### PR TITLE
Updated bridge to 0.30.0

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Task

### Description

This PR updates the bridge version to 0.30.0 and the test-clients to 0.9.1.

### Checklist

- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by ppatierno** [comment]
The PR is now ready to review with the latest bridge release 0.30.0.

**Review by scholzj — APPROVED** [review]
LGTM assuming the tests pass.

**Review by im-konge — APPROVED** [review]
Could you please also mention that you updated the version of test-clients to 0.9.1 in the description? Thanks!

**Pull request merged**
