### PR TITLE
Added a way to retrieve node config by Kafka Agent and exposing via HTTP

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Enhancement / new feature

### Description

This PR is about proposal PR [#82](https://github.com/strimzi/proposals/pull/82)

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
I don't follow this. Why are we exposing a file we have in a config map as a HTTP endpoint?

**Comment by ppatierno** [comment]
> I don't follow this. Why are we exposing a file we have in a config map as a HTTP endpoint?

This is actually a good point Jakub. I don't know the Kafka Roller code in details which already interacts with the Kafka Agent for the broker state. As stated in the proposal, this is going to be a temporary solution so I am not sure this is better to be replaced by the final one (using the Kafka Admin client) or it would be the same just loading info from the ConfigMap. Maybe the effort is just the same.
One difference I see is that in the ConfigMap we have some env vars defined (i.e. `${CERTS_STORE_PASSWORD}`) so not the actual configuration as we are getting from the file system (as used by the node). Is it possible that this can happen for other parameters?

Anyway, I thought that we all agreed together doing this way in our offline call together with @tombentley. It was also described in the corresponding proposal, maybe you should have raised the question there?

**Comment by scholzj** [comment]
> One difference I see is that in the ConfigMap we have some env vars defined (i.e. ${CERTS_STORE_PASSWORD}) so not the actual configuration as we are getting from the file system (as used by the node). Is it possible that this can happen for other parameters?

Well, one thing to keep in mind, the config you will be diffing it against will have the `${CERTS_STORE_PASSWORD}` placeholders as well.

> Anyway, I thought that we all agreed together doing this way in our offline call together with @tombentley. It was also described in the corresponding proposal, maybe you should have raised the question there?

To be honest, my understanding was that it would get the current configuration somehow from Kafka directly (e.g. JMX or some internal APIs). By reading the file, you might also miss the cluster-wide config changes updated internally etc.

**Comment by ppatierno** [comment]
> To be honest, my understanding was that it would get the current configuration somehow from Kafka directly (e.g. JMX or some internal APIs). By reading the file, you might also miss the cluster-wide config changes updated internally etc.

No, the idea was just about reading the file, and I think it was clear. Again as stated in the proposal.
It was accepted that as a temporary solution any dynamic changes would not be reflected to the file, so in general not necessary rollings could happen.

**Pull request closed without merging**
