### PR TITLE
Changed Strimzi description in the Helm charts files

### PR DESCRIPTION
**Pull request by ppatierno**
Signed-off-by: Paolo Patierno <ppatierno@live.com>

### Type of change

_Select the type of your PR_

- Documentation

### Description

Change the Strimzi description to reflect the current one.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ppatierno** [comment]
@scholzj how it's related to updating the web site as well?

**Comment by ppatierno** [comment]
Ok agree on the first point I will revert the description for previous version than 0.14.0.
Regarding the website it means that I have to do that there as well.

**Comment by scholzj** [comment]
Well, not really. The website has only the index.yaml. So if we do not change it retroactively, you do not need to touch it. And in 0.15.0 should be generated into the index.yaml from the Chart.yaml.

**Comment by ppatierno** [comment]
So I am going to close this one if we need to do the change only on future 0.15.0

**Comment by scholzj** [comment]
@ppatierno I think you should reopen this: as I said above, the change in `helm-charts/strimzi-kafka-operator/Chart.yaml` IMHO defines how the 0.15.0 will be rendered there. So we need to update it there.

**Comment by ppatierno** [comment]
@scholzj I opened #2043

**Pull request closed without merging**
