### PR TITLE
Freeze ST kafka version in testing-farm to 3.4.0

### PR DESCRIPTION
**Pull request by kornys**
### Type of change

- Bugfix

### Description

Freeze kafka version in testing-farm due to zookeeper issue

### CODE REVIEW

**Review by im-konge — APPROVED** [review]

**Review by scholzj — CHANGES_REQUESTED** [review]
@ppatierno just opened #8702 to fix that.

**Comment by kornys** [comment]
> @ppatierno just opened #8702 to fix that.

perfect so I can close it :)

**Comment by kornys** [comment]
@scholzj seems Paolo's fix does not work :)

**Comment by ppatierno** [comment]
@kornys I am investigating again, anyway I think that fixing Kafka 3.4.0 version doesn't work at all. It will be out in a few from the operator and we'll be screwed up again.

**Pull request closed without merging**
