### PR TITLE
Adding afterBeforeLoadConfigMap fiels to the Kafka Rebalance Status 

### PR DESCRIPTION
**Pull request by ShubhamRwt**
Signed-off-by: ShubhamRwt <srawat@redhat.com>

### Type of change

_Select the type of your PR_

- Enhancement 

### Description

This PR adds afterBeforeLoadConfigMap fields to the Kafka Rebalance Status so that the user can get to know after/before load CM is being generated.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by ShubhamRwt** [comment]
I have yet to change the description

**Comment by ShubhamRwt** [comment]
@tomncooper @scholzj @ppatierno Hello,  After making these changes I am able to get the newly added field in the KR status if I run `KafkaRebalanceAssemblyOperatorTest#testRebalanceStatusInProposalReadyState()` and print the KR status. But when I deploy the operator, cruise control resource and Kr resource, I didn't get the newly added field in the status when I use ` kubectl describe kafkarebalance my-rebalance`

**Comment by scholzj** [comment]
You should run `make crd_install` to get the CRD copied out.

Not sure why it doesn't show in `kubectl describe` does it show in `kuebctl get kr ... -o yaml`?

**Comment by ShubhamRwt** [comment]
> You should run `make crd_install` to get the CRD copied out.
> 
> Not sure why it doesn't show in `kubectl describe` does it show in `kuebctl get kr ... -o yaml`?

No, I tried both but still didn't got it there.

**Comment by ShubhamRwt** [comment]
Iam trying to figure out what is missing

**Comment by ShubhamRwt** [comment]
@scholzj I have putted the `afterBeforeLoadConfigMap` field under `optimizationResult` now. 
```status:
  conditions:
  - lastTransitionTime: "2021-07-07T20:17:46.247787Z"
    status: "True"
    type: ProposalReady
  observedGeneration: 1
  optimizationResult:
    afterBeforeLoadConfigMap: my-rebalance
    dataToMoveMB: 0
    excludedBrokersForLeadership: []
    excludedBrokersForReplicaMove: []
    excludedTopics: []
    intraBrokerDataToMoveMB: 0
    monitoredPartitionsPercentage: 100
    numIntraBrokerReplicaMovements: 0
    numLeaderMovements: 19
    numReplicaMovements: 31
    onDemandBalancednessScoreAfter: 87.27903875724745
    onDemandBalancednessScoreBefore: 80.87946050436929
    provisionRecommendation: ""
    provisionStatus: RIGHT_SIZED
    recentWindows: 1
  sessionId: 4d6b55f2-b3e1-4235-8570-458a7```

**Comment by kyguy** [comment]
Hey @ShubhamRwt the changes work for me when I deploy locally to minikube:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
   ...
  resourceVersion: "150018"
  uid: 03e41c09-743c-4382-a6e1-2bfaf4a9008e
spec: {}
status:
  conditions:
  - lastTransitionTime: "2021-07-09T14:37:43.464392Z"
    status: "True"
    type: ProposalReady
  observedGeneration: 1
  optimizationResult:
    afterBeforeLoadConfigMap: my-rebalance
    dataToMoveMB: 0
    excludedBrokersForLeadership: []
    excludedBrokersForReplicaMove: []
    excludedTopics: []
    intraBrokerDataToMoveMB: 0
    monitoredPartitionsPercentage: 100
    numIntraBrokerReplicaMovements: 0
    numLeaderMovements: 5
    numReplicaMovements: 3
    onDemandBalancednessScoreAfter: 86.5211909515508
    onDemandBalancednessScoreBefore: 83.16903091432891
    provisionRecommendation: ""
    provisionStatus: RIGHT_SIZED
    recentWindows: 1
  sessionId: de871663-2604-4df9-853d-5ea02c95338c
```
Does the Image ID of the container used for the Cluster Operator deployment match the Image ID of the Cluster Operator image you have built locally?

**Review by kyguy — APPROVED** [review]

**Comment by ShubhamRwt** [comment]
Is it working fine now @kyguy ?

**Comment by kyguy** [comment]
Yes, works great for me!

**Comment by scholzj** [comment]
@ppatierno Can you please have a look at this as one of the Cruise Control SMEs?

**Review by tomncooper — APPROVED** [review]
LGTM

**Review by scholzj — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
