### PR TITLE
Add support for Kafka 3.8.0

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

This PR adds support for Kafka 3.8.0 and removes support for Kafka 3.6.x. It also updates several dependencies needed for Kafka 3.8.0 - Cruise Control and the Kroxylicious test stuff (that was still not replaced with our own Test Container 🙄).

This is currently a draft used to run system tests.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by im-konge — APPROVED** [review]
LGTM, thanks :)

**Review by see-quick — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
