### PR TITLE
Improve PR builds info report

### PR DESCRIPTION
**Pull request by Frawless**
### Type of change

- Enhancement / new feature

### Description

Improve script, which collects information for each PR build. From now, jenkins will post information about each build every time it finish. In case of failed build, it post notification, that build failed. For more examples, see the following comments.

### CODE REVIEW

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=travis test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=travis test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=travis test_only

**Comment by Frawless** [comment]
### Test Summary
**Test Profile:**
**Test Case:**
**Tests Executed:** 1
**Test Passed:** 1
**Test Failed:** 0
**Test Skipped:** 0

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=travis test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=travis test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=travis test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=acceptance test_only

**Comment by scholzj** [comment]
Very nice @Frawless! 👍

**Comment by kornys** [comment]
@Frawless 👍

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=travis test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=travis test_only

**Comment by ppatierno** [comment]
@Frawless it's not ready for merge, there is just one committer approval.

**Pull request merged**
