### PR TITLE
Set WARN log level for healthy and ready OpenAPI operations

### LINKED ISSUE #1845: [Bug] Fix default logging configuration for the Kafka Bridge
Due to the logging change in the Kafka Bridge, in order to shut down the heavy logging of liveness and readiness probes, it's needed to set the default logging level for `healthy` and `ready` operations to WARN.
It has to be updated in the `kafkaBridgeDefaultLoggingProperties` file.

### PR DESCRIPTION
**Pull request by ppatierno**
### Type of change

- Bugfix

### Description

This PR fixes #1845 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ppatierno** [comment]
As before all the HTTP OpenAPI operations with method, path and response code but not for the liveness and readiness probes.

**Comment by scholzj** [comment]
Thanks for waiting for my approval :-). Didn't we already in the past discussed that logging every request is too much? We had similar issue with the TO in the past.

**Comment by ppatierno** [comment]
I didn't get you were against it but just asking. I merged after got two committers approvals. I think that we need to test the impact it has under load because having logs about requests can bel useful.

**Comment by scholzj** [comment]
I think if someone comments it is nice to give him time to react. And not merge it just because someone else has approved it.

It can be useful, but it can be also totally useless if you get several GBs of logs for 2 minutes of traffic. That is why I asked what is it logging by default with these settings.

**Comment by scholzj** [comment]
Anyway, let's see how it works.

**Comment by ppatierno** [comment]
It's not written into the stone, we can continue to discuss with the others as well and opening a new PR for a future release.

**Pull request merged**
