### PR TITLE
Remove gRPC dependency.

### PR DESCRIPTION
**Pull request by alesj**
### Type of change

- Bugfix

### Description

The Topic Operator is designed to run always only in a single instance. It has no way to run in multiple replicas because it cannot partitions the KafkaTopic CRs or Kafka topics. We should therefore remove the distributed topic store from it since it is never used and removing it reduces the dependency footprint.

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
The code looks good to me. Can you update the PR description?

**Review by sknot-rh — APPROVED** [review]

**Comment by ppatierno** [comment]
Out of curiosity, why we are removing the gRPC based implemantation of the store?

**Comment by scholzj** [comment]
@ppatierno Because it is not needed. The TO anyway doesn't know how to run in multiple instances for many other reasons then the Topic Store.

**Review by ppatierno — APPROVED** [review]

**Comment by ppatierno** [comment]
I had doubts since the beginning why we had this, so was curious why removing now. Thanks.

**Review by scholzj — COMMENTED** [review]
Ok, I updated the description my self.

**Pull request merged**
