### PR TITLE
NEW(Tests) Loggers settings with variables #4340

### PR DESCRIPTION
**Pull request by michalxo**
LoggingChangeST#testUseLoggingVarsBeforeDefinition

This is a follow-up for PR #4340 which contains SystemTest, with logger variables defined later in file, as used.
See PR for more details.

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging

UPD: I have removed original - new test, and updated existing one instead.

### CODE REVIEW

**Comment by michalxo** [comment]
@strimzi-ci run tests test_only profile=regression testcase=LoggingChangeST

**Comment by michalxo** [comment]
@strimzi-ci run tests test_only profile=regression testcase=LoggingChangeST

**Comment by michalxo** [comment]
@strimzi-ci run tests test_only profile=regression testcase=LoggingChangeST

**Comment by michalxo** [comment]
@strimzi-ci run tests test_only profile=regression testcase=LoggingChangeST

**Comment by michalxo** [comment]
@strimzi-ci run tests true profile=regression testcase=io.strimzi.systemtest.log.LoggingChangeST#testDynamicallySetKafkaExternalLogging,io.strimzi.systemtest.log.LoggingChangeST#testJSONFormatLoggingDeprecated

**Comment by michalxo** [comment]
@strimzi-ci run tests false profile=regression testcase=io.strimzi.systemtest.log.LoggingChangeST#testDynamicallySetKafkaExternalLogging

**Review by sknot-rh — APPROVED** [review]

**Review by im-konge — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Review by scholzj — APPROVED** [review]

**Pull request merged**
