### PR TITLE
Topic operator improvements

### LINKED ISSUE #1157: Attempt to delete topic is reversed by Topic Operator
Strimzi Version: `0.9.0-rc1`

I want to delete a topic, but cannot seem to do so using the CLI tools nor deleting the `KafkaTopic` CRD. The topic operator insists on recreating it. 

When deleting `KafkaTopic` CRD for topic in question: 

`[2018-12-12 12:48:13,612] INFO  <opicOperator:559> [oop-thread-0] All three topics are identical
[2018-12-12 12:48:13,613] INFO  <TopicWatcher:40> [oop-thread-0] Success processing KafkaTopic watch event ADDED on resource nutmeg-sit with labels {strimzi.io/cluster=c}
[2018-12-12 12:48:15,831] INFO  <TopicWatcher:37> [ault.svc/...] KafkaTopic watch received event DELETED on resource nutmeg-sit with labels {strimzi.io/cluster=c}
[2018-12-12 12:48:15,842] INFO  <opicOperator:419> [oop-thread-0] Reconciling topic nutmeg-sit, k8sTopic:null, kafkaTopic:nonnull, privateTopic:nonnull
[2018-12-12 12:48:15,842] INFO  <opicOperator:319> [oop-thread-0] Deleting topic 'nutmeg-sit'
[2018-12-12 12:48:15,863] INFO  <TopicWatcher:40> [oop-thread-0] Success processing KafkaTopic watch event DELETED on resource nutmeg-sit with labels {strimzi.io/cluster=c}
[2018-12-12 12:48:15,891] INFO  <opicsWatcher:79> [oop-thread-1] Deleted topics: [nutmeg-sit]
[2018-12-12 12:48:15,898] INFO  <opicOperator:419> [oop-thread-0] Reconciling topic null, k8sTopic:null, kafkaTopic:null, privateTopic:null
[2018-12-12 12:48:15,965] INFO  <opicsWatcher:94> [oop-thread-1] Created topics: [nutmeg-sit]
[2018-12-12 12:48:16,186] INFO  <opicOperator:419> [oop-thread-0] Reconciling topic nutmeg-sit, k8sTopic:null, kafkaTopic:nonnull, privateTopic:null
[2018-12-12 12:48:16,194] INFO  <TopicWatcher:37> [ault.svc/...] KafkaTopic watch received event ADDED on resource nutmeg-sit with labels {strimzi.io/cluster=c}
[2018-12-12 12:48:16,207] INFO  <opicOperator:419> [oop-thread-1] Reconciling topic nutmeg-sit, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
[2018-12-12 12:48:16,207] INFO  <opicOperator:559> [oop-thread-1] All three topics are identical
[2018-12-12 12:48:16,207] INFO  <TopicWatcher:40> [oop-thread-1] Success processing KafkaTopic watch event ADDED on resource nutmeg-sit with labels {strimzi.io/cluster=c}`

When I use the `kafka-topics.sh` CLI:
`[2018-12-12 12:49:40,902] INFO  <TopicWatcher:37> [ault.svc/...] KafkaTopic watch received event DELETED on resource nutmeg-sit with labels {strimzi.io/cluster=c}
[2018-12-12 12:49:40,907] INFO  <TopicWatcher:40> [oop-thread-1] Success processing KafkaTopic watch event MODIFIED on resource nutmeg-sit with labels {strimzi.io/cluster=c}
[2018-12-12 12:49:40,909] INFO  <opicOperator:419> [oop-thread-1] Reconciling topic null, k8sTopic:null, kafkaTopic:null, privateTopic:null
[2018-12-12 12:49:40,909] INFO  <TopicWatcher:40> [oop-thread-1] Success processing KafkaTopic watch event DELETED on resource nutmeg-sit with labels {strimzi.io/cluster=c}
[2018-12-12 12:49:41,327] INFO  <opicsWatcher:94> [oop-thread-0] Created topics: [nutmeg-sit]
[2018-12-12 12:49:41,371] INFO  <opicOperator:955> [oop-thread-1] Starting periodic reconciliation
[2018-12-12 12:49:41,387] INFO  <opicOperator:419> [oop-thread-1] Reconciling topic _schemas, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
[2018-12-12 12:49:41,388] INFO  <opicOperator:559> [oop-thread-1] All three topics are identical
[2018-12-12 12:49:41,388] INFO  <opicOperator:365> [oop-thread-1] Success reconciling KafkaTopic strimzi/schemas---251ea2dcbbf0dc3858aa5637c32a54d26159edc1
[2018-12-12 12:49:41,397] INFO  <opicOperator:419> [oop-thread-0] Reconciling topic _schemas, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
[2018-12-12 12:49:41,397] INFO  <opicOperator:559> [oop-thread-0] All three topics are identical
[2018-12-12 12:49:41,397] INFO  <opicOperator:365> [oop-thread-0] Success reconciling KafkaTopic strimzi/schemas---251ea2dcbbf0dc3858aa5637c32a54d26159edc1
[2018-12-12 12:49:41,546] INFO  <opicOperator:419> [oop-thread-1] Reconciling topic nutmeg-sit, k8sTopic:null, kafkaTopic:nonnull, privateTopic:null
[2018-12-12 12:49:41,558] INFO  <TopicWatcher:37> [ault.svc/...] KafkaTopic watch received event ADDED on resource nutmeg-sit with labels {strimzi.io/cluster=c}
[2018-12-12 12:49:41,565] INFO  <opicOperator:419> [oop-thread-0] Reconciling topic nutmeg-sit, k8sTopic:null, kafkaTopic:nonnull, privateTopic:nonnull
[2018-12-12 12:49:41,565] INFO  <opicOperator:319> [oop-thread-0] Deleting topic 'nutmeg-sit'
[2018-12-12 12:49:41,586] INFO  <opicOperator:365> [oop-thread-0] Success reconciling KafkaTopic null
[2018-12-12 12:49:41,592] INFO  <opicOperator:419> [oop-thread-0] Reconciling topic nutmeg-sit, k8sTopic:nonnull, kafkaTopic:null, privateTopic:null
[2018-12-12 12:49:41,599] ERROR <TopicWatcher:49> [oop-thread-0] Failure processing KafkaTopic watch event ADDED on resource nutmeg-sit with labels {strimzi.io/cluster=c}: Topic 'nutmeg-sit' already exists.
org.apache.kafka.common.errors.TopicExistsException: Topic 'nutmeg-sit' already exists.
[2018-12-12 12:49:41,602] WARN  <opicOperator:96> [oop-thread-0] Failure processing KafkaTopic watch event ADDED on resource nutmeg-sit with labels {strimzi.io/cluster=c}: Topic 'nutmeg-sit' already exists.
[2018-12-12 12:49:41,609] INFO  <opicsWatcher:79> [oop-thread-0] Deleted topics: [nutmeg-sit]
[2018-12-12 12:49:41,616] INFO  <opicOperator:419> [oop-thread-1] Reconciling topic nutmeg-sit, k8sTopic:nonnull, kafkaTopic:null, privateTopic:null
[2018-12-12 12:49:41,628] INFO  <opicsWatcher:94> [oop-thread-0] Created topics: [nutmeg-sit]
[2018-12-12 12:49:41,637] INFO  <opicOperator:192> [oop-thread-1] Created topic 'nutmeg-sit' for KafkaTopic 'nutmeg-sit'
[2018-12-12 12:49:41,651] INFO  <opicOperator:419> [oop-thread-0] Reconciling topic nutmeg-sit, k8sTopic:nonnull, kafkaTopic:nonnull, privateTopic:nonnull
[2018-12-12 12:49:41,651] INFO  <opicOperator:559> [oop-thread-0] All three topics are identical`

The topic in question is `nutmeg-sit` - both attempting to delete topic using CLI and CRD fails. Doing both at the same time also fails.

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Bugfix

### Description

Try to fix #1157 by using both checks suggested in the issue, namely:

1. We should be prepared to wait longer for the the Kafka controller to delete a topic, since deleting a large number of topics is known to basically lock up the controller for a time. So we bump the timeout for that from 2 to 5 minutes.
2. When we observe the deletion of a topic via ZK don't assume the topic deletion has propagated to observations of the topic via the Admin client. Instead wait for the Admin client to confirm that the topic doesn't exist before proceeding with the reconciliation. 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by sknot-rh** [comment]
Do you plan to add some tests?

**Review by sknot-rh — APPROVED** [review]
LGTM

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
@tombentley Should this be merged? Or are you still working on this?

**Pull request merged**
