### PR TITLE
[systemtest] Make exec log less verbose

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Type of change

- Enhancement

### Description

After #4595 the log of STs become too verbose -> on every exec the whole files were printed (which is not good in case of applying/creating CRDs).
This PR changes log level to `debug` for printing extra info, so the log of ST can be cleaner and also shorter.

Before:
https://gist.github.com/im-konge/9e0efc1f5e363f8fbddc549fc84fb3e9

After - STs:
```
2021-03-23 13:05:14 [main] INFO  [KubeClusterResource:160] Using Namespace listeners
2021-03-23 13:05:14 [main] INFO  [KubeClusterResource:80] Changing to listeners namespace
2021-03-23 13:05:14 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/010-ServiceAccount-strimzi-cluster-operator.yaml
2021-03-23 13:05:15 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/020-ClusterRole-strimzi-cluster-operator-role.yaml
2021-03-23 13:05:16 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/021-ClusterRole-strimzi-cluster-operator-role.yaml
2021-03-23 13:05:16 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/030-ClusterRole-strimzi-kafka-broker.yaml
2021-03-23 13:05:17 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/031-ClusterRole-strimzi-entity-operator.yaml
2021-03-23 13:05:18 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/032-ClusterRole-strimzi-topic-operator.yaml
2021-03-23 13:05:18 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/033-ClusterRole-strimzi-kafka-client.yaml
2021-03-23 13:05:19 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/040-Crd-kafka.yaml
2021-03-23 13:05:20 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/041-Crd-kafkaconnect.yaml
2021-03-23 13:05:21 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/042-Crd-kafkaconnects2i.yaml
2021-03-23 13:05:23 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/043-Crd-kafkatopic.yaml
2021-03-23 13:05:23 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/044-Crd-kafkauser.yaml
2021-03-23 13:05:24 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/045-Crd-kafkamirrormaker.yaml
2021-03-23 13:05:25 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/046-Crd-kafkabridge.yaml
2021-03-23 13:05:26 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/047-Crd-kafkaconnector.yaml
2021-03-23 13:05:27 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/048-Crd-kafkamirrormaker2.yaml
2021-03-23 13:05:28 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/049-Crd-kafkarebalance.yaml
2021-03-23 13:05:29 [main] INFO  [AbstractST:191] Creating configuration file: /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/050-ConfigMap-strimzi-cluster-operator.yaml
2021-03-23 13:05:30 [main] INFO  [NetworkPolicyResource:212] NetworkPolicy successfully set to: true for namespace: listeners
2021-03-23 13:05:30 [main] INFO  [ClusterRoleBindingResource:43] Creating ClusterRoleBinding in test case ListenersST from /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/021-ClusterRoleBinding-strimzi-cluster-operator.yaml in namespace listeners
2021-03-23 13:05:30 [main] INFO  [ResourceManager:145] Create/Update of ClusterRoleBinding strimzi-cluster-operator in namespace (not set)
2021-03-23 13:05:30 [main] INFO  [ResourceManager:197] Resource strimzi-cluster-operator in namespace null is io.strimzi.systemtest.resources.ResourceManager$$Lambda$490/0x00000008403cb840@77bbadc!
2021-03-23 13:05:30 [main] INFO  [ClusterRoleBindingResource:43] Creating ClusterRoleBinding in test case ListenersST from /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/030-ClusterRoleBinding-strimzi-cluster-operator-kafka-broker-delegation.yaml in namespace listeners
2021-03-23 13:05:30 [main] INFO  [ResourceManager:145] Create/Update of ClusterRoleBinding strimzi-cluster-operator-kafka-broker-delegation in namespace (not set)
2021-03-23 13:05:31 [main] INFO  [ResourceManager:197] Resource strimzi-cluster-operator-kafka-broker-delegation in namespace null is io.strimzi.systemtest.resources.ResourceManager$$Lambda$490/0x00000008403cb840@25ad4f71!
2021-03-23 13:05:31 [main] INFO  [ClusterRoleBindingResource:43] Creating ClusterRoleBinding in test case ListenersST from /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/033-ClusterRoleBinding-strimzi-cluster-operator-kafka-client-delegation.yaml in namespace listeners
2021-03-23 13:05:31 [main] INFO  [ResourceManager:145] Create/Update of ClusterRoleBinding strimzi-cluster-operator-kafka-client-delegation in namespace (not set)
2021-03-23 13:05:31 [main] INFO  [ResourceManager:197] Resource strimzi-cluster-operator-kafka-client-delegation in namespace null is io.strimzi.systemtest.resources.ResourceManager$$Lambda$490/0x00000008403cb840@455c1d8c!
2021-03-23 13:05:31 [main] INFO  [RoleBindingResource:44] Creating RoleBinding from /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/020-RoleBinding-strimzi-cluster-operator.yaml in namespace listeners
2021-03-23 13:05:31 [main] INFO  [RoleBindingResource:44] Creating RoleBinding from /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml in namespace listeners
2021-03-23 13:05:31 [main] INFO  [RoleBindingResource:44] Creating RoleBinding from /home/lkral/work/streams/strimzi-kafka-operator/systemtest/../packaging/install/cluster-operator/032-RoleBinding-strimzi-cluster-operator-topic-operator-delegation.yaml in namespace listeners
2021-03-23 13:05:32 [main] INFO  [ResourceManager:145] Create/Update of Deployment strimzi-cluster-operator in namespace listeners
2021-03-23 13:05:33 [main] INFO  [DeploymentUtils:151] Wait for Deployment: strimzi-cluster-operator will be ready
2021-03-23 13:05:49 [main] INFO  [DeploymentUtils:158] Deployment: strimzi-cluster-operator is ready
2021-03-23 13:05:49 [main] INFO  [DeploymentUtils:170] Waiting for 1 Pod(s) of Deployment strimzi-cluster-operator to be ready
2021-03-23 13:06:00 [main] INFO  [DeploymentUtils:173] Deployment strimzi-cluster-operator is ready
2021-03-23 13:06:00 [main] INFO  [ResourceManager:197] Resource strimzi-cluster-operator in namespace listeners is io.strimzi.systemtest.resources.ResourceManager$$Lambda$490/0x00000008403cb840@df921b1!
```

After - ITs:
```
2021-03-23 12:55:31 INFO [Exec:168] Failed to exec command: minikube status
2021-03-23 12:55:31 INFO [Exec:172] RETURN code: 85
2021-03-23 12:55:31 INFO [Exec:174] ======STDOUT START=======
2021-03-23 12:55:31 INFO [Exec:175] * Profile "minikube" not found. Run "minikube profile list" to view all profiles.
  - To start a cluster, run: "minikube start"
2021-03-23 12:55:31 INFO [Exec:176] ======STDOUT END======
2021-03-23 12:55:31 WARN [KubeCluster:80] Cluster minikube is not running!
2021-03-23 12:55:33 WARN [KubeCluster:80] Cluster kubectl is not running!
2021-03-23 12:55:33 WARN [KubeCluster:83] Cluster minishift is not installed!
2021-03-23 12:55:36 INFO [KubeCluster:90] Using cluster: oc
2021-03-23 12:55:36 INFO [KubeClusterResource:52] Cluster default namespace is default
2021-03-23 12:55:36 INFO [KubeClusterResource:53] Cluster command line client default namespace is default
2021-03-23 12:55:37 INFO [KubeClusterResource:154] Creating Namespace kafkabridge-crd-it
2021-03-23 12:55:38 INFO [KubeClusterResource:160] Using Namespace kafkabridge-crd-it
2021-03-23 12:55:38 INFO [KubeClusterResource:80] Changing to kafkabridge-crd-it namespace
2021-03-23 12:55:38 INFO [KubeClusterResource:210] Creating resources /home/lkral/work/streams/strimzi-kafka-operator/api/../packaging/install/cluster-operator/046-Crd-kafkabridge.yaml in Namespace kafkabridge-crd-it
2021-03-23 12:55:39 INFO [TimeMeasuringSystem:70] ============ ADDING RECORD ========
2021-03-23 12:55:39 INFO [TimeMeasuringSystem:96] Start time of operation TEST_EXECUTION is correctly stored
2021-03-23 12:55:39 INFO [TestSeparator:29] ############################################################################
2021-03-23 12:55:39 INFO [TestSeparator:30] io.strimzi.api.kafka.model.KafkaBridgeCrdIT.testKafkaBridgeWithMissingRequired-STARTED
2021-03-23 12:55:51 INFO [Exec:168] Failed to exec command: oc --namespace kafkabridge-crd-it create -f /home/lkral/work/streams/strimzi-kafka-operator/api/target/test-classes/io/strimzi/api/kafka/model/KafkaBridge-with-missing-required-property.yaml
2021-03-23 12:55:51 INFO [Exec:172] RETURN code: 1
2021-03-23 12:55:51 INFO [Exec:179] ======STDERR START=======
2021-03-23 12:55:51 INFO [Exec:180] The KafkaBridge "test-kafka-bridge" is invalid: spec.bootstrapServers: Required value
2021-03-23 12:55:51 INFO [Exec:181] ======STDERR END======
2021-03-23 12:55:52 INFO [Exec:168] Failed to exec command: oc --namespace kafkabridge-crd-it delete -f /home/lkral/work/streams/strimzi-kafka-operator/api/target/test-classes/io/strimzi/api/kafka/model/KafkaBridge-with-missing-required-property.yaml
2021-03-23 12:55:52 INFO [Exec:172] RETURN code: 1
2021-03-23 12:55:52 INFO [Exec:179] ======STDERR START=======
2021-03-23 12:55:52 INFO [Exec:180] Error from server (NotFound): error when deleting "/home/lkral/work/streams/strimzi-kafka-operator/api/target/test-classes/io/strimzi/api/kafka/model/KafkaBridge-with-missing-required-property.yaml": kafkabridges.kafka.strimzi.io "test-kafka-bridge" not found
2021-03-23 12:55:52 INFO [Exec:181] ======STDERR END======
2021-03-23 12:55:52 WARN [BaseCmdKubeClient:158] Failed to delete /home/lkral/work/streams/strimzi-kafka-operator/api/target/test-classes/io/strimzi/api/kafka/model/KafkaBridge-with-missing-required-property.yaml!
2021-03-23 12:55:52 WARN [TimeMeasuringSystem:125] End time of operation TEST_EXECUTION is not set due to exception: java.lang.NullPointerException
2021-03-23 12:55:52 INFO [TestSeparator:36] io.strimzi.api.kafka.model.KafkaBridgeCrdIT.testKafkaBridgeWithMissingRequired-FINISHED
2021-03-23 12:55:52 INFO [TestSeparator:37] ############################################################################
2021-03-23 12:55:52 INFO [KubeClusterResource:222] Deleting resources /home/lkral/work/streams/strimzi-kafka-operator/api/../packaging/install/cluster-operator/046-Crd-kafkabridge.yaml
2021-03-23 12:55:53 INFO [KubeClusterResource:179] Deleting Namespace kafkabridge-crd-it
2021-03-23 12:56:00 INFO [Exec:168] Failed to exec command: oc --namespace kafkabridge-crd-it get Namespace kafkabridge-crd-it -o yaml
2021-03-23 12:56:00 INFO [Exec:172] RETURN code: 1
2021-03-23 12:56:00 INFO [Exec:179] ======STDERR START=======
2021-03-23 12:56:00 INFO [Exec:180] Error from server (NotFound): namespaces "kafkabridge-crd-it" not found
2021-03-23 12:56:00 INFO [Exec:181] ======STDERR END======
2021-03-23 12:56:00 INFO [KubeClusterResource:185] Using Namespace kafkabridge-crd-it
2021-03-23 12:56:00 INFO [KubeClusterResource:80] Changing to kafkabridge-crd-it namespace
```
### Checklist

- [ ] Make sure all tests pass

### CODE REVIEW

**Comment by scholzj** [comment]
Some before and after examples would be nice to demonstrate what does the change mean.

**Comment by im-konge** [comment]
@scholzj sure, I wanted to add it, thanks!

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=acceptance

**Review by Frawless — CHANGES_REQUESTED** [review]
I don't say I am strictly against it, but as I mentioned offline, this is useful for ITs in case you are trying to debug them. Maybe a better option is to log this info on DEBUG lvl and maybe also skip CRD aplication?

**Comment by scholzj** [comment]
So, how do we control the which log level is used where? I can easily agree that dumping 1000s of CRD lines into log is useless at any log level.

**Comment by im-konge** [comment]
We discussed this:

- the `input` should be in debug
- other information should be in info (like `stderr` and `stdout`)
- IT's should have some information about what we are executing and where
- for CRDs - we should just log what we are creating and where, no other logs are necessary

Is that right @Frawless ?

**Comment by Frawless** [comment]
There is `STRIMZI_TEST_LOG_LEVEL` env var with default value `INFO` for set the log level. Also we by default log `DEBUG` level into file alongside the logs

@im-konge sounds good to me

**Review by scholzj — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Pull request merged**
