### PR TITLE
Add truststore support for Kafka MSK

### PR DESCRIPTION
**Pull request by nhjiejan**
### Type of change

_Select the type of your PR_
- Enhancement / new feature

### Description
In order to support the use of Amazon MSK, Strimzi needs to allow importing chained certificates into its truststore (whereby only importing the root certificate is allowed).

in addition, generating a brand new truststore using the keytool utility is not supported for MSK due to the requirement of of some standard Certificate Authorities. these can be found in the default JVM cacerts which is then copied over in the base image.

### CODE REVIEW

**Comment by scholzj** [comment]
@nhjiejan Can you please start by properly explaining your problem and describing your scenario? From the 5 files you change, at least 3 have IMHO nothing to do with Amazon MSK. Also, Amazon MSK AFAIK uses signed keys so you do not need to pass any keys for it. So I think it is important to understand why is this change really needed.

**Comment by nhjiejan** [comment]
> @nhjiejan Can you please start by properly explaining your problem and describing your scenario? From the 5 files you change, at least 3 have IMHO nothing to do with Amazon MSK. Also, Amazon MSK AFAIK uses signed keys so you do not need to pass any keys for it. So I think it is important to understand why is this change really needed.

so the initial problem is using mirrormaker to connect to our MSK cluster. it requires TLS auth and connection. correct it uses a signed certificate, and when it is signed, it is returned as a chained certificate which includes both a CA cert and a root cert.

in order for the truststore to trust the Amazon MSK Private certificate authority, it needs to import the root certificate of the chained cert

**Comment by nhjiejan** [comment]
You're right, in fact i only need to change the MirrorMaker tls prep and kafka connect tls prep files. the others need remain the same

**Comment by scholzj** [comment]
So if you want to work on this, we can work on this. But have you just tried to specify this?

```
tls:
  trustedCertificates: []
```

to use the default certificates from Java? That normally works fine with things like Amazon MSK (https://strimzi.io/docs/operators/master/full/using.html#con-common-configuration-trusted-certificates-reference)

If that is not enough for some reason, we can work through this PR if you want.

**Comment by nhjiejan** [comment]
> So if you want to work on this, we can work on this. But have you just tried to specify this?
> 
> ```
> tls:
>   trustedCertificates: []
> ```
> 
> to use the default certificates from Java? That normally works fine with things like Amazon MSK (https://strimzi.io/docs/operators/master/full/using.html#con-common-configuration-trusted-certificates-reference)
> 
> If that is not enough for some reason, we can work through this PR if you want.

i managed to figure out the issue thanks to your advice. for some reason i also have to add the `starfield certificate authority` public certs as `trustedCertificates` secrets when configuring kafkaConnect for an Amazon MSK cluster. that saves a lot of hacking. this PR can now be closed

**Comment by ppatierno** [comment]
Sorry to jump late but the same was with using Azure Eveng Hub with MM and MM2 so what @scholzj is right and working.
You can see here:

https://strimzi.io/blog/2020/05/14/mirror-kafka-eventhub/
https://strimzi.io/blog/2020/06/09/mirror-maker-2-eventhub/

it's just enough:

```yaml
tls:
  trustedCertificates: []
```

**Pull request closed without merging**
