### PR TITLE
using single ZK node as well, like on Kafka

### PR DESCRIPTION
**Pull request by matzew**
Signed-off-by: Matthias Wessendorf <mwessend@redhat.com>

### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

like the `kafka`, I think the Zookeeper should be also single, in the single example.

### CODE REVIEW

**Comment by scholzj** [comment]
As mentioned on Slack. The ephemeral storage is just an `emptyDir` and can get easily lost for example when pod restarts, when you do a rolling update etc. This kinda kills Kafka, because it looses all the information stored there. With 3 Zoo nodes, they can recover from each other. So the probability of thi happening is much smaller. Changing the node count here to 1 would probably make this much worse experience for many users using it.

If you want just one Zoo node, why not use the persistent example? That is using persistent volume to store the data is is safe even with single Zoo node.

**Comment by matzew** [comment]
ok :-)

**Pull request closed without merging**
