### PR TITLE
Adapt tests to recent kubectl versions

### PR DESCRIPTION
**Pull request by OuesFa**
Signed-off-by: fares.oueslati <fares.oueslati@blablacar.com>

### Type of change

- Bugfix

### Description

Adapt tests to recent kubectl versions, here is [the discussion ](https://github.com/strimzi/strimzi-kafka-operator/pull/7414/files#r987093614)that led me to open this PR.
### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [x] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by scholzj** [comment]
> Weird I don't have these errors locally 🤔

I think this is some flakiness. The `api` module passed, so I think that might be fine. I restarted the CI.

**Review by scholzj — APPROVED** [review]
Thanks for the PR.

**Comment by scholzj** [comment]
@ppatierno Can you please have a look at this as well?

**Review by ppatierno — APPROVED** [review]

**Comment by OuesFa** [comment]
Perfect, I'm rebasing the [other branch](https://github.com/strimzi/strimzi-kafka-operator/pull/7414) and moving forward with the PR 🚀

**Pull request merged**
