### PR TITLE
[MO] - [Parallel Namespace tests] -> LoggingChangeST

### PR DESCRIPTION
**Pull request by see-quick**
### Type of change

- Enhancement / new feature
- Refactoring

### Description

This PR adding support of parallel namespace execution of `LoggingChangeST`.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by see-quick** [comment]
I will rebase https://github.com/strimzi/strimzi-kafka-operator/pull/4726 after it's merged.

**Review by Frawless — APPROVED** [review]
LGTM in case regression will be green

**Review by scholzj — APPROVED** [review]

**Pull request merged**
