### PR TITLE
[ST] Fix testRecoveryDuringKafkaRollingUpdate

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Bugfix

### Description

In #9197 I accidentally broke the `testRecoveryDuringKafkaRollingUpdate` for BTO because of number of replicas that I'm creating.

This PR reverts those changes and applies different solution for the issue -> creating one consumer before we shut down one node (so the `__consumer_offsets` topic will be successfully created), and then creates another one (with different consumer group), after one of the Kafka Pods is in the `Pending` state.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
LGTM assuming the tests pass.

**Review by Frawless — APPROVED** [review]

**Pull request merged**
