### PR TITLE
WIP Generate doc

### PR DESCRIPTION
**Pull request by tombentley**
This has taken a bit longer than I expected (thanks to maven weirdness wrt annotation processing), but it seems to work and I wanted to get your thoughts. It still needs configuring into a documentation build process (which perhaps shouldn't involve maven).

The basic idea is to use an annotation processor as a way of generating documentation from the source code at compile time (or documentation-compilation time). This has a number of benefits:

* The documentation is maintained alongside the code.
* Using an annotation processor means the annotations won't bloat the `.class` files, since you can use `SOURCE` retention.
* How the documentation is rendered (both format and layout) is separated from the documentation content. I've implemented  renderers for asciidoc tables and labelled lists, but other documentation formats would be trivial to add.
* The generated files can be included into the user documentation via asciidoc `include::FILENAME[]` directive.
* The annotation processor and meta-annotation (defined in the `docgen` directory) are actually very general, and could be reused in other projects. It should be possible to generate pretty much any tabular data whose elements can be defined as Java literals.

The new `common` module just defines two annotations: `CmKey` and `EnvVar`. Each of these corresponds to a kind of table (basically defining the columns the table has). Here's `CmKey` as an example:

```java
@Table
@Retention(RetentionPolicy.SOURCE)
@Target({ElementType.METHOD, ElementType.FIELD})
@Documented
public @interface CmKey {
    @Table.Column(heading = "ConfigMap key")
    String name();

    @Table.Column(heading = "Description")
    String doc();

    @Table.Column(heading = "Default")
    String defaultValue() default "";

    @Table.Column(heading = "Mandatory")
    boolean required() default false;
}
```

Those annotations are then applied to program elements in the source code (I have partially done this in the cluster controller, but it's a WIP). The point of all this is that we end up just needing to write stuff like:

```java
    @CmKey(name = "kafka-image",
            doc = "The image to use for Kafka pods.",
            defaultValue = DEFAULT_IMAGE,
            required = true)
    public static final String KEY_IMAGE = "kafka-image";

    @CmKey(name = "kafka-nodes",
            doc = "The number of Kafka broker nodes.",
            defaultValue = DEFAULT_IMAGE,
            required = true)
    public static final String KEY_REPLICAS = "kafka-nodes";
```

And a `CmKey.KafkaCluster.adoc` file pops out as a result of annotation processing, ready for `include::CmKey.KafkaCluster.adoc[]`

Still to do:

* [ ] Let the `@Table` annotation define the `Render` and an optional title for the table. 
* [ ] More tests!
* [ ] Sort the table rows
* [ ] Fit into a documentation preparation process, so the generated `.adoc` end up in the right place for within the `documentation` directory.
* [ ] Document the resources managed by the cluster controller using another annotation.
* [ ] Env vars for the topic-controller
* [ ] ConfigMap keys for the topic controller.

### CODE REVIEW

**Comment by scholzj** [comment]
Seems like quite a lot of work for something what we might not need that much :-)

Some questions:
- How do you annotate the inner classes such as `Storage`?
- How does it deal with structured settings such as with CRDs?
- What is the workflow you expect? Generate it in CI only (and copy to the website)? Generate it in CI and commit back into it self? Generate it locally and commit manually?

**Comment by tombentley** [comment]
> Seems like quite a lot of work for something what we might not need that much :-)

Yeah, I'm sorry about that. It turned out to take longer than I expected, partly because of maven. But I think this is something that could be readily used in other projects (maybe Kafka upstream and/or Enmasse etc.) I think it is worth it if other projected used it. If it would be just us then it starts to look like a sledgehammer to crack a nut 😭 

> * How do you annotate the inner classes such as `Storage`?

In the same way, which would get you a separate table. I don't think nested tables are a good idea (in the sense that they make the documentation harder to read), if that's what you were driving at. 

The way it works currently is you annotate members of your class/interface using your custom annotation and the containing class/interface defines the "scope" for collecting all the members together, for that kind of table). You could generate two tables from the same class, but not two tables of the same kind. I have thoughts about making it more flexible, so you could annotate members in different classes and by giving them a common "key" you could generate a single table. Likewise that would let you generate two tables of the same kind from a single class.

> * How does it deal with structured settings such as with CRDs?

It can generate any kind of table, more or less. So if you were happy to document a tree-like structure using a table(s), for example by documenting the paths in the tree then it should be able to do that, or by using multiple tables for different subtrees. How else would you want to document a tree-like thing, anyway?

Right now your custom annotations have to hang off members of a class, but it should also be possible to use a sequenced annotation and hang them directly off a class too. 

> * What is the workflow you expect? Generate it in CI only (and copy to the website)? Generate it in CI and commit back into it self? Generate it locally and commit manually?

I hadn't thought too hard about it, TBH. The nicest, from an authoring PoV, would be to arrange for the generated files to be in the right place at the point you're writing the doc that includes them. That way any IDE/editor preview tooling will 'just work'. But I'm very open to better ideas.

**Comment by tombentley** [comment]
> It seems to be a lot of work and tbh I don't like all these annotations around fields and declarations but if this is the way to go.

It's _a_ way to go. We need to decide whether it's really _the_ way to go. I guess it's my job to persuade you...

I believe docs people would prefer content like this to be auto-generated where possible, as it reduces the maintenance burden each release of checking that each config is documented, and the documentation is correct. If you accept that argument, then the doc necessarily ends up in the code _somewhere_, and then it's purely about the best way of representing the documentation in the code.

An alternative to using an annotation is to write classes like the config stuff in the topic controller. It's natural enough to include documentation alongside defaults and type used to parse/validate the config, and then have a main method somewhere which dumps that doc to some format. This is the approach taken current in Kafka. 

There are pros and cons on each side, of course. The pros of the approach illustrated by this work are:

* it's pretty light weight: It's just an annotation pretty much anywhere in your code. The annotation you define don't need to end up in the `.class` files. Making the documentation generateable by a normal `main` method mean all the doc ends up as strings in the constant pool and you're carrying around the code for generating doc in your jar file.
* it's really reusable for different configurable things. Compare that generating doc from a config class: You end up needing separate `main` methods for generating env var doc, config map doc etc. That's code that has to be written, tested, maintained separately in multiple places.
* You can (mostly) factor out details of whatever markup language you're using.

**Comment by scholzj** [comment]
I think the annotations are the right way to go. They give us more flexibility than the Kafka style approach.

**Comment by scholzj** [comment]
@tombentley @ppatierno Shouldn't we do something with this? Something such as keeping the branch but closing the PR? Or do we still think it is worth finishing?

**Comment by scholzj** [comment]
@tombentley Ok, no problem. I was just wondering what to do with it. If you plan to get back to it in the future, we can of course keep it open.

**Pull request closed without merging**
