### PR TITLE
[system test] Fix testAutoKafkaRebalanceScaleUpScaleDown and make it …

### PR DESCRIPTION
**Pull request by see-quick**
…work also for ZK

### Type of change

- Bugfix

### Description

This PR fixes problem with `testAutoKafkaRebalanceScaleUpScaleDown` to make it work also for ZK-based clusters.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass

### CODE REVIEW

**Review by ppatierno — APPROVED** [review]

**Review by im-konge — APPROVED** [review]
LGTM, assuming it works :)

**Pull request merged**
