### PR TITLE
Docs: Fix modules in Rack Awareness

### PR DESCRIPTION
**Pull request by ncbaratta**
### Type of change

- Documentation

### Description

Remove unnecessary ref module and add an additional procedure to rack awareness

### CODE REVIEW

**Comment by ncbaratta** [comment]
@scholzj @tombentley I'm wondering if the Travis errors on this PR are code errors and not docs errors:

```
2018-08-20 21:22:19 ERROR RackWriter:52 - Error writing the rackid
2018-08-20 21:22:19 ERROR RackWriter:39 - Node localhost doesn't have the label failure-domain.beta.kubernetes.io/zone for getting the rackid
# Build Docker image ...
```

Am I mistaken?

**Comment by ncbaratta** [comment]
@scholzj If it's one procedure, can we put the step about Configuring init container image into the configuring the rack awareness? Would it happen before or after that step?

I'm trying to turn the files you labeled as reference into introductions to the procedures so that we have fewer headings, fewer files, and more importantly so that if someone wants to reuse a module it has the conceptual info at the top.

**Comment by scholzj** [comment]
99% of users will never use the `brokerRackInitImage` option. It is just for the rare cases when the user needs to override it. so I think we can hide it into the other procedure.

**Comment by scholzj** [comment]
FYI: The Travis error here is some issue with heading levels:

```
asciidoctor -v --failure-level WARN -t -dbook -a ProductVersion=latest documentation/book/master.adoc -o documentation/html/index.html
asciidoctor: WARNING: proc-configuring-init-container-image.adoc: line 6: section title out of sequence: expected level 4, got level 5
Input file: documentation/book/master.adoc
  Time to read and parse source: 0.21453
  Time to convert document: 0.13122
  Total time (read, parse and convert): 0.34575
make: *** [docu_html] Error 1
```

**Comment by ncbaratta** [comment]
I started to put the brokerRackInitImage stuff into the other procedure, but then we lose the warning and other relevant information.  What if we title it: 'Overriding container images' and leave it there for those who are troubleshooting?

**Comment by scholzj** [comment]
@ncbaratta BTW: We have a whole chapter for it ... so maybe we can just reference it: http://strimzi.io/docs/master/full.html#assembly-configuring-container-images-deployment-configuration-kafka

**Comment by ncbaratta** [comment]
Awesome! I just can't keep up with it all :)

**Pull request merged**
