### PR TITLE
update the statement about NFS storage

### PR DESCRIPTION
**Pull request by chenzhiwei**
### Type of change

- Documentation

### Description

This PR is used to change the statement about NFS storage support.

Kafka does not officially state it can't work with NFS storage, so I think it is better to not state that NFS storage does not work with Kafka.

I have a talk with Kate Stanley on Slack, Strimzi project does not run Kafka tests against NFS storage, but this does not mean Kafka does not work with NFS storage.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

N/A, since this PR is used to change the document.

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. But as far as I know, NFS does not work well with Kafka. So I think we want to keep what we have today in the docs.

**Comment by chenzhiwei** [comment]
@scholzj Thank you for your quick review.

I know that Kafka does not support NFS(especially NFSv3) in early days, but the related bugs were all fixed by Kafka team.

* https://issues.apache.org/jira/browse/KAFKA-4844
* https://issues.apache.org/jira/browse/KAFKA-6322
* https://issues.apache.org/jira/browse/KAFKA-6188

Is it really a good idea to state that **Kafka does not work with NFS storage** ?

https://issues.apache.org/jira/browse/KAFKA-13995

**Comment by scholzj** [comment]
PS: Even half of the issues you linked is still open.

**Comment by ppatierno** [comment]
On the community call, December 15th, we thought that the actual wording is too strong. We agree that saying something like "block storage is highly recommended" is much better than "block storage is required". @PaulRMellor will help us to find the right middle ground wording for this.

**Review by PaulRMellor — COMMENTED** [review]
I've suggested something less strong than the current text, but still recommending block storage as the way to go.

**Comment by chenzhiwei** [comment]
Thank you @ppatierno @PaulRMellor @scholzj , the suggested change from @PaulRMellor seems good to me and I committed the change.

**Review by ppatierno — APPROVED** [review]
LGTM.Thanks!

**Review by katheris — APPROVED** [review]
This wording makes sense to me

**Comment by scholzj** [comment]
@PaulRMellor @ppatierno What is your plan for this PR?

**Comment by PaulRMellor** [comment]
> @PaulRMellor @ppatierno What is your plan for this PR?

@scholzj - I assumed it could be merged

**Comment by ppatierno** [comment]
@scholzj we can merge this imho.

**Pull request merged**
