### PR TITLE
Deprecate ZooKeeper-based cluster fields in the API

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Task

### Description

This PR deprecates the API fields related to ZooKeeper-based clusters:
* Deprecated `.spec.zookeeper` section
* Deprecated `.spec.kafka.replicas` section
* Deprecated `.spec.kafka.storage` section
* Unused ZooKeeper-related methods from `KafkaResources` were removed
* The tests related to the Kafka CR were cleaned up to focus on Kraft-based clusters and maintain just one legacy ZooKeeper-based Kafka CR YAML to make sure we still support it in the CRDs
* As we now have the automatic deprecation warnings, the warnings generated from `KRaftUtils` were removed as they are not needed anymore
* In System Tests, some of these deprecated fields are still used and this will be cleaned only when ZooKeeper is cleaned-up from the STs. So for the time being, the deprecation warnings are suppressed
* The replicas are also still used in the `KafkaClusterCreator` -> this piece was missed in #10964. As this will likely have a larger refactoring, for the time being I just suppressed the deprecation warning and will address it in a follow-up PR.
* The generated CRD reference in the docs has been updated, but the docs themself will be updated only in one of the follow up PRs.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Comment by scholzj** [comment]
_(The OPA STs failure is not related to this PR but to #10980)_

**Review by ppatierno — APPROVED** [review]
LGTM.

**Pull request merged**
