### PR TITLE
[ST] fixing unnecessary error logs when cleaning resources

### PR DESCRIPTION
**Pull request by henryZrncik**
### Type of change

- Refactoring

### Description
all changes made in order to avoid error logs (mostly null pointers) when removing Kafka resources and namespaces. 

- added one check to make sure kafka is present when cleaning Kafka resource. (solve problems with "Kafka" null pointers)
- added default value for "testMethodName" when setting up cluster Operator namespaces and Logs Collecting, this is expected by the way we are creating them e.g. causing unexpected behaviour when trying to remove namespace.

additionally removal of several explicit kafka deletions in the end of the test as they are not necessary there (and are commonly no longer used as we have cleaning set up).

### CODE REVIEW

**Comment by henryZrncik** [comment]
the fail of the test in Azure has nothing to do with changes. The test is actually flaky and fails on both this and main branch as well (approx 40% of time) will be fixed in separe from this PR.

**Comment by see-quick** [comment]
Well but for sure you should resolve problem with spotbugs i.e., 
```java
[INFO] BugInstance size is 1
[INFO] Error size is 0
[INFO] Total bugs: 1
[ERROR] Medium: Do not catch NullPointerException like in io.strimzi.systemtest.resources.ResourceManager.deleteResource(HasMetadata[]) [io.strimzi.systemtest.resources.ResourceManager] At ResourceManager.java:[line 349] DCN_NULLPOINTER_EXCEPTION
[INFO] 
```

**Comment by henryZrncik** [comment]
1. (@see-quick) yeah, spotbugs problem should be removed 
2. (@im-konge) Also I will cover similar cases when waiting for resources in other PR as well.

**Review by see-quick — APPROVED** [review]

**Pull request merged**
