### PR TITLE
#2779 CrdGenerator validate `@JsonPropertyOrder`

### PR DESCRIPTION
**Pull request by steffen-karlsson**
### Type of change

- Enhancement / new feature: https://github.com/strimzi/strimzi-kafka-operator/issues/2779
- Refactoring

### Description
Validating existence of `@JsonPropertyOrder` and that all relevant fields in class are present in the `@JsonPropertyOrder`

### Checklist

- [X] Write tests
- [X] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [X] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by steffen-karlsson** [comment]
Still not ready for review, in progress 😄

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. I think this looks good - I didn't realized we were missing it on so many classes. I will run the regression tests on this as well.

**Comment by steffen-karlsson** [comment]
> Thanks for the PR. I think this looks good - I didn't realized we were missing it on so many classes. I will run the regression tests on this as well.

Was also surprised when I started adjusting the classes :D

**Review by scholzj — APPROVED** [review]
LGTM. Thanks for the PR.

**Review by ppatierno — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
