### PR TITLE
[systemtest] Add checks to deprecated MetricsST tests

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Type of change

- Adding checks to metrics tests

### Description

This PR add some additional checks to "deprecated" metrics tests in MetricsST. We are now parsing the metrics configuration from original metrics yaml and then setting it to `metrics` field.

I had to change indentation in two metrics yamls, so I could parse it without exceptions.

_Thanks for help_ @sknot-rh 

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by sknot-rh — APPROVED** [review]

**Review by scholzj — APPROVED** [review]
The old YAMLs seem to be valid. So I'm not what problems did you had with reading them. That said, I do not care about the alignment, so if it helps.

**Comment by im-konge** [comment]
@scholz TBH I tried many solutions, but seems that mapper have some problem with it.. this was the best solution we found.

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=regression testcase=MetricsST

**Review by Frawless — APPROVED** [review]

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=metrics

**Pull request merged**
