### PR TITLE
docs(build fix): Format fix for annotations used to highlight and describe deprecated properties

### PR DESCRIPTION
**Pull request by PaulRMellor**
Signed-off-by: prmellor <pmellor@redhat.com>

**Documentation**

The [AclRule schema properties](https://strimzi.io/docs/operators/in-development/configuring.html#type-AclRule-schema-reference) and [AclRuleTopicResource schema reference](https://strimzi.io/docs/operators/in-development/configuring.html#type-AclRuleTopicResource-reference) are not presenting correctly in the api reference.

This PR introduces a format fix so that the sections are generated correctly. 

_Please describe your pull request_

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
The change is fine. But it looks like the `documentation/modules/appendix_crds.adoc` file is not properly generated. So I think you will need to regenerate it.

**Comment by PaulRMellor** [comment]
@scholzj  - I've tried to rebuild, but I get the old and updated line when I do. 

> |operation   1.2+<.<a|*The `operation` property has been deprecated, and should now be configured using `spec.authorization.acls[*].operations`.* **The `operation` property has been deprecated, and should now be configured using `spec.authorization.acls[*].

I tried changing the Java description to something different, but still the old line is reinserted. Even removed the `. m2`. Any ideas?

**Comment by scholzj** [comment]
Well, the first part is generated by the annotations. So that will be always there. The second part is what you added whcih should not be there. That is driven by the annotation.

**Comment by PaulRMellor** [comment]
> Well, the first part is generated by the annotations. So that will be always there. The second part is what you added whcih should not be there. That is driven by the annotation.

Ah, right. Thanks!

**Comment by scholzj** [comment]
@PaulRMellor I guess this would be the place to fix it if there should be `**` instead of `*`: https://github.com/strimzi/strimzi-kafka-operator/blob/f6255b4394afeceacbd5e9bce2779e4bb8c1badf/crd-generator/src/main/java/io/strimzi/crdgenerator/DocGenerator.java#L295-L310

**Comment by scholzj** [comment]
You would need to change it on line 296 and 304 I guess.

**Review by scholzj — APPROVED** [review]
Maybe you can rename the PR to better match what it does now? It might help in the future when we need to dig through some history.

**Pull request merged**
