### PR TITLE
Remove support for legacy metrics configuration from the CO code

### PR DESCRIPTION
**Pull request by ShubhamRwt**
Signed-off-by: ShubhamRwt <shubhamrwt02@gmail.com>

### Type of change

- Refactoring

### Description

This PR removes the support for legacy metrics configuration like this :- 

```
metrics:
  # ...  
```
### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Can you please update the description and describe what the PR does?

Also, some things I think should be done with this PR:
* The `metricsConfig` in `AbstractModel` class should not be used anymore after this. So you can remove it and all its uses.

**Comment by ShubhamRwt** [comment]
@scholzj - Hello, Are we talking about removing ``` protected Iterable<Map.Entry<String, Object>> metricsConfig; ``` this form the `AbstractModel` class ?

**Comment by scholzj** [comment]
@ShubhamRwt Yeah, I would expect that it should not be needed anymore.

**Comment by ShubhamRwt** [comment]
@scholzj - Hello, I have applied the suggestions

**Review by scholzj — APPROVED** [review]

**Review by sknot-rh — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
@ShubhamRwt @see-quick Can you please look at the conflicts? I think it should be easy to resolve -> GitHub is not exactly smart in this :-/

**Comment by ShubhamRwt** [comment]
@scholzj - Hello, I have rebased the PR and pushed the changes.

**Pull request merged**
