### PR TITLE
[systemtest] Fix for the upgrade AZP profiles in pom.xml and remove all leftovers after IsolatedSuite removal

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Bugfix

### Description

This PR fixes bug that was added in #8860, where the `Isolated` suites were removed -> this affected naming of the classes and because we are using the names of the STs in AZP profiles, it broke the upgrade pipeline.

-----------------------------------------------------------------------

Also, this PR removes leftovers after the aforementioned PR - `IsolatedSuite`, mentions in Javadoc.
 
### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
If you search the code, there seem to be some more places where `IsolatedST` is still used. E.g. some Javadoc or the testing README. That should be probably fixed as well. There seem to be also some `IsolatedSuite` annotation which is not used and seems to be a left over as well?

**Comment by im-konge** [comment]
Ah yes, I thought that `IsolatedSuite` is used in UTs/ITs also, gonna remove it.
Thanks

**Review by see-quick — APPROVED** [review]

**Review by scholzj — APPROVED** [review]

**Comment by scholzj** [comment]
(Sorry, I wanted to run upgrade tests but started regression by mistake)

**Pull request merged**
