### PR TITLE
Update to yq version 4

### PR DESCRIPTION
**Pull request by tomncooper**
### Type of change

Refactoring

### Description

This PR deals with the fact that Mike Farah has [completely changed](https://mikefarah.gitbook.io/yq/v/v4.x/upgrading-from-v3) the API of his `yq` tool in version 4:

```
Version 4 of yq is a major upgrade that now fully supports complex expressions for powerful filtering, 
slicing and dicing yaml documents. This new version uses syntax very similar to jq and works very 
similarly, so if you've used jq before this should be a low learning curve - however it is quite different 
from previous versions of yq. Take a look at the upgrade guide for help.

Support for v3 will cease August 2021, until then, critical bug and security fixes will still get applied if 
required.
```

As a result of these changes our `kafka-versions` scripts and helm install make targets no longer work. This PR updates all the required `yq` commands to the new version 4 format.

I have also moved the `prerequisites` and `multi-platform-support` scripts into the `tools` directory as it tidies up the root.

### Checklist

- [X] Make sure all tests pass
- [X] Update documentation

### CODE REVIEW

**Comment by tomncooper** [comment]
So I have got the `yq` upgrade working, however the only issue is that I cannot get the helm 2 crd install to substitute `'{{ template "strimzi.chart" . }}'` into the chart. `yq` is swallowing the double quotes and nothing I try will retain them.

As this only effects helm2 chart generation, and helm2 support is being dropped after 0.21, I will park this PR until helm 2 is removed.

**Comment by tomncooper** [comment]
This PR will depend on #4227 being merged.

**Review by scholzj — APPROVED** [review]
LGTM assuming the tests pass.

**Comment by Frawless** [comment]
@strimzi-ci run tests test_only profile=smoke

**Review by Frawless — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
Sorry @tomncooper for not merging this yet ... hope to do this right after the 0.21.1 bugfix release to make my life easier. I did not forgot about it.

**Comment by tomncooper** [comment]
No worries, it makes sense to wait until after the release.

**Pull request merged**
