### PR TITLE
Added arm64 for TINI and Kafka Exporter in Dockerfile for base and Kafka

### PR DESCRIPTION
**Pull request by bitvijays**
### Type of change

- Enhancement / new feature

### Description

Added TINI and Kafka exporter in DockerFile of `base` and `kafka` for `arm64`

### Help Needed

Currently this has been tested like the below (which might not be correct)

Amd64, which compiles perfectly
```
ubuntu@soo-cheri:~/Documents/strimzi-kafka-operator$ echo $DOCKER_BUILD_ARGS 
--platform linux/amd64
ubuntu@soo-cheri:~/Documents/strimzi-kafka-operator$ echo $DOCKER_BUILDX 
buildx
ubuntu@soo-cheri:~/Documents/strimzi-kafka-operator$ MVN_ARGS="-Dmaven.javadoc.skip=true -DskipITs -DskipTests" make docker_build
```

and for `arm64`, I do get the below error, any help to resolve this is appreciated

```
# Build Docker image ...
docker build --platform linux/arm64 --build-arg JAVA_VERSION=11  --build-arg strimzi_version=0.20.0 -t strimzi/operator:latest ./
Sending build context to Docker daemon  54.93MB
Step 1/10 : FROM strimzi/base:latest
 ---> a34ad7c39bd5
Step 2/10 : RUN useradd -r -m -u 1001 -g 0 strimzi
 ---> Using cache
 ---> 9103bae38841
Step 3/10 : ARG strimzi_version=1.0-SNAPSHOT
 ---> Using cache
 ---> 07255d44155d
Step 4/10 : ENV STRIMZI_VERSION ${strimzi_version}
 ---> Using cache
 ---> e626b5e6b2cd
Step 5/10 : ENV STRIMZI_HOME=/opt/strimzi
 ---> Using cache
 ---> eed736739fb4
Step 6/10 : RUN mkdir -p ${STRIMZI_HOME}/bin
 ---> Using cache
 ---> 3b5db1985912
Step 7/10 : WORKDIR ${STRIMZI_HOME}
 ---> Using cache
 ---> 24ef35790c90
Step 8/10 : COPY scripts/ tmp/bin/ bin/
 ---> Using cache
 ---> b268dc3e343d
Step 9/10 : COPY tmp/lib/ lib/
failed to get destination image "sha256:b268dc3e343dcb363a8aa218dc80f4eb75b966420cc4338a8932601814e8a9a1": image with reference sha256:b268dc3e343dcb363a8aa218dc80f4eb75b966420cc4338a8932601814e8a9a1 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
make[2]: *** [../../Makefile.docker:21: docker_build_default] Error 1
make[2]: Leaving directory '/home/bitvijays/Documents/strimzi-kafka-operator/docker-images/operator'
make[1]: *** [Makefile:12: docker_build] Error 2
make[1]: Leaving directory '/home/bitvijays/Documents/strimzi-kafka-operator/docker-images'
make: *** [Makefile:167: docker-images] Error 2
```
### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by scholzj** [comment]
Have you tried this?

```
export DOCKER_BUILDX=buildx
export DOCKER_BUILD_ARGS="--platform linux/amd64 --load"
```

As I described [here](https://github.com/strimzi/strimzi-kafka-operator/blob/master/development-docs/DEV_GUIDE.md#building-container-images-for-other-platforms-with-docker-buildx)?

I think the `--load` option will push the image into the regular local registry and that is needed for the next build to find it.

**Comment by scholzj** [comment]
You also have to fix the DCO sign-off ... the instructions should be under the _Details_ link next to the DCO in the PR status.

**Comment by bitvijays** [comment]
> Have you tried this?
> 
> ```
> export DOCKER_BUILDX=buildx
> export DOCKER_BUILD_ARGS="--platform linux/amd64 --load"
> ```
> 
> As I described [here](https://github.com/strimzi/strimzi-kafka-operator/blob/master/development-docs/DEV_GUIDE.md#building-container-images-for-other-platforms-with-docker-buildx)?
> 
> I think the `--load` option will push the image into the regular local registry and that is needed for the next build to find it. It seems to work fine for me with it.

@scholzj `--platform linux/amd64 --load` works fine. 

On the other hand, when executed with `--platform linux/arm64 --load`, we do get the below error

```
make[1]: Leaving directory '/home/bitvijays/Downloads/strimzi-kafka-operator/kafka-init'
make -C docker-images docker_build
make[1]: Entering directory '/home/bitvijays/Downloads/strimzi-kafka-operator/docker-images'
./build.sh docker_build
make[2]: Entering directory '/home/bitvijays/Downloads/strimzi-kafka-operator/docker-images/base'
# Build Docker image ...
docker buildx build --platform linux/arm64 --load --build-arg JAVA_VERSION=11  --build-arg strimzi_version=0.22.0-SNAPSHOT -t strimzi/base:latest ./
[+] Building 1.8s (5/6)                                                                                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                                                                          0.0s
 => => transferring dockerfile: 942B                                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                                                               0.0s
 => [internal] load metadata for docker.io/library/centos:7                                                                                                                                                   1.0s
 => CACHED [1/3] FROM docker.io/library/centos:7@sha256:0f4ec88e21daf75124b8a9e5ca03c37a5e937e0e108a255d890492430789b60e                                                                                      0.0s
 => ERROR [2/3] RUN yum -y update     && yum -y install java-11-openjdk-headless openssl bind-utils     && yum -y clean all                                                                                   0.7s
------                                                                                                                                                                                                             
 > [2/3] RUN yum -y update     && yum -y install java-11-openjdk-headless openssl bind-utils     && yum -y clean all:
#5 0.297 standard_init_linux.go:219: exec user process caused: exec format error
------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c yum -y update     && yum -y install java-${JAVA_VERSION}-openjdk-headless openssl bind-utils     && yum -y clean all]: exit code: 1
make[2]: *** [../../Makefile.docker:21: docker_build_default] Error 1
make[2]: Leaving directory '/home/bitvijays/Downloads/strimzi-kafka-operator/docker-images/base'
make[1]: *** [Makefile:12: docker_build] Error 2
make[1]: Leaving directory '/home/bitvijays/Downloads/strimzi-kafka-operator/docker-images'
make: *** [Makefile:176: docker-images] Error 2
```

**Comment by scholzj** [comment]
Yeah, I copied it with `linux/amd64`, sorry. But builds fine for me with `linux/arm64` as well. To be clear - I do not have any Arm64 env right now around ... so I did just the build, did not tried how it works in reality. But for you it fails in build already. My environment is MacOS + Docker Desktop 3.0.3 (51017, Engine version 20.10.00).

**Comment by bitvijays** [comment]
@scholzj Unfortunately, I do not have the build environment. My build is failing because, my docker buildx doesn't show `linux/arm64`
```
docker buildx ls
NAME/NODE DRIVER/ENDPOINT STATUS  PLATFORMS
default * docker                  
  default default         running linux/amd64, linux/386
```

If the build for `arm64` is working fine on `Docker Desktop`, please go forward with this PR. Let me know if anything else is required from my side.

**Comment by scholzj** [comment]
Ok, that would make the difference I guess. Mine shows this:
```
NAME/NODE        DRIVER/ENDPOINT             STATUS   PLATFORMS
busy_shaw        docker-container
  busy_shaw0     unix:///var/run/docker.sock stopped
jolly_swirles    docker-container
  jolly_swirles0 unix:///var/run/docker.sock inactive
default *        docker
  default        default                     running  linux/amd64, linux/arm64, linux/riscv64, linux/ppc64le, linux/s390x, linux/386, linux/arm/v7, linux/arm/v6
```

If I build the images into some tag and give you the address ... do you have some Arm64 environment to test them? I would feel better if I knew that it really works and not just builds and if you can test it somewhere it would save me the effort to spin up my own Arm environment for it.

**Comment by bitvijays** [comment]
Sure thing @scholzj Happy to do it 👍 . I have arm64 environment, Raspberry Pi 4 8GB/ 4GB machines.

**Comment by scholzj** [comment]
Ok, I did the build and pushed it into my repository. The installation YAMl for it is here: https://gist.github.com/scholzj/3143bfaaeb9f3c3785ec1b097b1f2513

**Comment by bitvijays** [comment]
@scholzj Just wanted to confirm the steps:

Setup:
- A `RPI 4 with 8 GB RAM` running `K3S` server.
- A `RPI 4 with 4 GB RAM` running `K3S` agent as a `Worker Node`

Should I 
- follow the [strimzi quick start guide](https://strimzi.io/docs/operators/master/quickstart.html) or
- directly perform `kubectl apply -f Installation_YAML`

**Comment by scholzj** [comment]
Hmm, I think you need to do the following:
1) Create the namespace
2) If the namespace is other than `myproject` do a search and replace for your namespace in the YAML file from the link above
3) Apply the YAML file to install the operator
4) Create the Kafka custom resource and see if it deployes

_Note: I build only the operator ... so for sure the Strimzi Bridge and the Kaniko build will not work. The rest should work._

**Comment by bitvijays** [comment]
@scholzj Hope you are doing well. My apologies, would it be possible for you to generate the images once again? Unfortunately, forgot to add `ARG TARGETPLATFORM`,  because of which it by default install `tini` for `amd64`. My apologies.

**Comment by scholzj** [comment]
I rebuilt them and pushed them to the same repo. So you can pull them. But don't we also need to set the `TARGETPLATFORM`? Or will Docker set it automatically?

**Comment by bitvijays** [comment]
@scholzj Yea, docker set it automatically.

The container starts `running` and goes to `CrashLoopBackOff`.

Log present at https://p.fr33tux.org/9acc77

It might be
```
{"log":"2021-01-18 21:06:23 WARN  WatchConnectionManager:198 - Exec Failure: HTTP 403, Status: 403 - kafkas.kafka.strimzi.io is forbidden: User \"system:serviceaccount:default:strimzi-cluster-operator\" cannot watch resource \"kafkas\" in API group \"kafka.strimzi.io\" in the namespace \"default\"\n","stream":"stdout","time":"2021-01-18T21:06:23.134507602Z"}
{"log":"java.net.ProtocolException: Expected HTTP 101 response but was '403 Forbidden'\n","stream":"stdout","time":"2021-01-18T21:06:23.134602143Z"}
```

**Comment by scholzj** [comment]
That looks like RBAC issue -> it looks like you use the `default` namespace. Did you do _search / replace_ before applying the YAML to change the `myproject` namespace to `default`?

**Comment by bitvijays** [comment]
Instead of replacing `myproject` to `default`, I did created a namespace `myproject`

```
ubuntu@node-0001:~$ kubectl get namespace
NAME              STATUS   AGE
default           Active   23d
kube-system       Active   23d
kube-public       Active   23d
kube-node-lease   Active   23d
myproject         Active   4h16m
kafka             Active   43m
```

That should be fine right?

**Comment by scholzj** [comment]
Yeah, that should work as well ... if you deploy it into the `myproject` namespace ou do not need to replace anything, just apply the file with `kubectl apply -n myproject ....yaml`.

**Comment by bitvijays** [comment]
@scholzj Works fine now

```
ubuntu@node-0001:~$ kubectl get pods -o wide -n myproject
NAME                                        READY   STATUS    RESTARTS   AGE   IP           NODE        NOMINATED NODE   READINESS GATES
strimzi-cluster-operator-7cb4d965b7-w6n2r   1/1     Running   0          65s   10.42.0.33   node-0001   <none>           <none>
```

**Comment by scholzj** [comment]
Ok, great. Thanks for checking. Lets proceed with this then.

**Review by scholzj — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Pull request merged**
