### PR TITLE
Update proc-generating-reassignment-json-files.adoc

### PR DESCRIPTION
**Pull request by jacobball11**
Signed-off-by: Jacob Ball <jacobball40@gmail.com>

### Type of change

_Select the type of your PR_

- Updated docs with changes per [discussion](https://github.com/strimzi/strimzi-kafka-operator/discussions/7401).

### Description

Updated docs.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. I do not think we want to use `All` here. We should really give the exact rights which are needed.

@ShubhamRwt You wrote the blog post about reassignment - do you know what rights might be missing here or what exactly is needed?

**Comment by ShubhamRwt** [comment]
@scholzj Yes, Let me have a look

**Comment by ShubhamRwt** [comment]
Hi @jacobball11, I ran the step from the documentation and all the things worked fine for me. Looking at the Kafka User resource which you have sent on the discussion, it seems you are missing this ACL  
      
```- resource:
          type: cluster
          name: my-cluster
          patternType: literal
        operation: Alter
        host: "*"
```

**Comment by ShubhamRwt** [comment]
```apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  namespace: develop-namespace
  name: partition-reassignment-tool
  labels:
    strimzi.io/cluster: kafka-cluster-name
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # access to topic-1
      - resource:
          type: topic
          name: topic-1
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: topic-1
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: topic-1
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: topic-1
          patternType: literal
        operation: Alter
        host: "*"
      # access to topic-2
      - resource:
          type: topic
          name: topic-2
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: topic-2
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: topic-2
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: topic-2
          patternType: literal
        operation: Alter
        host: "*"
      # access to topic-3
      - resource:
          type: topic
          name: topic-3
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: topic-3
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: topic-3
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: topic-3
          patternType: literal
        operation: Alter
        host: "*"
```
In your User resource you can see that you have use ALTER with type and name as `topic` and `topic-3`

```     - resource:
          type: topic
          name: topic-3
          patternType: literal
        operation: Alter
        host: "*"
```

While the correct format was to use ALTER for type and name as `cluster` and `<cluster-name>`

**Comment by ShubhamRwt** [comment]
So what I would suggest that maybe you can add these two extra ACLs to the user resource in documentation

**Comment by ShubhamRwt** [comment]
Hi @jacobball11, the PR requires some changes, also the build seems to be failing, Can you address them?

**Comment by scholzj** [comment]
Superseeded by #7482. Thanks for raising this issue.

**Pull request closed without merging**
