### PR TITLE
Add optional creation for rbac related resources

### PR DESCRIPTION
**Pull request by stgrace**
Signed-off-by: Stef Graces <stefgraces@hotmail.com>

### Type of change

- Enhancement / new feature

### Description

Added some values to opt out of creating rbac resources. 
In some usecases, such as GitOps, you might not want the controller to create roles, but create the manually.

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — APPROVED** [review]

**Comment by stgrace** [comment]
Changed my commits to be conform with the DCO

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
@stgrace I don't think the failure in the tests is related to your PR. We will investigate it.

**Comment by scholzj** [comment]
Thanks for the PR.

**Comment by stgrace** [comment]
Thanks for the merge 😄

**Pull request merged**
