### PR TITLE
Docs: Clean up modules for Authentication & Authorization

### PR DESCRIPTION
**Pull request by ncbaratta**
### Type of change

- Documentation

### Description

Remove unnecessary reference modules & clean up Authorization & Authentication sections.

### CODE REVIEW

**Comment by ncbaratta** [comment]
@scholzj @tombentley I'm wondering if these test errors are actually related to the docs ... 

```
2018-08-20 21:04:49 ERROR RackWriter:52 - Error writing the rackid
2018-08-20 21:04:49 ERROR RackWriter:39 - Node localhost doesn't have the label failure-domain.beta.kubernetes.io/zone for getting the rackid
# Build Docker image ...
```

**Comment by scholzj** [comment]
>  I'm wondering if these test errors are actually related to the docs ...

@ncbaratta Sorry for late answer ... I was too busy to read the GitHub emails (sometimes asking on Slack might get you faster answer ;-)). If the question was about why did the Travis build failed, it was because of your changes:

```
asciidoctor -v --failure-level WARN -t -dbook -a ProductVersion=latest documentation/book/master.adoc -o documentation/html/index.html
asciidoctor: WARNING: invalid reference: ref-kafka-authentication-deployment-configuration-kafka
asciidoctor: WARNING: invalid reference: ref-kafka-authorization-deployment-configuration-kafka
Input file: documentation/book/master.adoc
  Time to read and parse source: 0.24463
  Time to convert document: 0.14737
  Total time (read, parse and convert): 0.39200
make: *** [docu_html] Error 1
```

It seems you broke some links.

**Comment by scholzj** [comment]
> In the reference files you had you were basically showing the same thing that was in the procedure in an example and it also seemed unnecessary.

Well, yes. Because there is no procedure to speak about. 99% of the procedures are _Use `kubectl apply`_

If reference should be really just a table with options without any real explanation, then I agree its not reference. But In my opinion its not procedure either. It is just explanation of what the configuration option does.

I do not think the users care about the procedure because they know that to change the resource they need to use `kubectl apply` - so they will tend to ignore these. And I'm afraid that if you _hide_ the explanation into the procedure they will have problem finding it. Maybe if the reference is not the right type should it be concept? Or should it be in the assembly introduction?

**Comment by ncbaratta** [comment]
> It seems you broke some links.

Thank you!! I knew I had to be missing the real error. I always search for the keyword error to figure out what I did wrong.  I'll fix this.

**Comment by ncbaratta** [comment]
> I do not think the users care about the procedure because they know that to change the resource they need to use kubectl apply - so they will tend to ignore these. And I'm afraid that if you hide the explanation into the procedure they will have problem finding it. Maybe if the reference is not the right type should it be concept? Or should it be in the assembly introduction?

It should either be a concept or an introduction - I think an introduction to the assembly works, but I still don't really understand why combining the information is worrisome.  I'm not adding a procedure, I'm just moving what appears to be an introduction into the procedure and scrapping the reference files.  It's less to read because before they had the reference to read and then the procedure and it was basically repeated information.

I think I have an idea of how to solve this.  What if we have a reference section or an 'advanced user' type section with all of these examples so folks who don't want to see all the steps can just browse through examples to find what they're looking for?  

We can talk about this instead of going back and forth here if you think that will be easier :)

**Comment by ncbaratta** [comment]
@scholzj this time I searched the raw log for asciidoctor and I didn't see anything related to the docs that looked like an error.  How's the best way to find what the problem is?

**Comment by ncbaratta** [comment]
Closing based on our meeting.  I think that it makes sense to revisit this after the next release because we might be able to put all the procedures related to editing the YAML file into one procedure on how to edit the YAML file and then have concepts for all the different things you can do in the YAML file.

**Pull request closed without merging**
