### PR TITLE
Add option to skip surefire tests via -Dskip.surefire.tests

### PR DESCRIPTION
**Pull request by Frawless**
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

### Type of change

- Enhancement / new feature

### Description

This PR adds option to skip surefire tests. This is useful for example when execute system tests without active docker on local environment. Example:
```mvn verify -pl systemtest -Dskip.surefire.tests -pl acceptance```

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by Frawless** [comment]
@strimzi-ci run tests test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests test_only

**Comment by Frawless** [comment]
@strimzi-ci run tests test_only

**Comment by scholzj** [comment]
* What is docker used for during the surefire tests?
* Which tests does it actually skip and how does it match with the existing `skipTests` and `skipITs` flags?

**Comment by Frawless** [comment]
@scholzj it's used in `BasicExternalKafkaClientTest` which uses testcontainers to validate our clients implementation (basically unit test). These tests are running during build I think. The idea of this is to skip them when you execute failsafe tests (ITs and STs). For example when you run `mvn verify -pl systemtest -Dit.test=KafkaST`, it will execute `BasicExternalKafkaClientTest` as well when surefire looking for tests. With this change, when you specify `-Dskip.surefire.tests` all surefire tests will be skipped or when you specify `-DskipTests`all tests (even failsafe) will be skipped. Anyway, this PR shouldn't affect the current behaviour of `-DskipTests`or `-DskipITs`.

**Comment by scholzj** [comment]
Ok, thanks for the explanation!

**Comment by Frawless** [comment]
@scholzj I added short note to `TESTING.md`

**Pull request merged**
