### PR TITLE
Add metrics to topic operator

### PR DESCRIPTION
**Pull request by OchiengEd**
### Type of change
- Enhancement / new feature

### Description
Add metrics to the topic-operator

### Checklist

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [x] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by OchiengEd** [comment]
Tests failed. I will be looking further into this.

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by scholzj** [comment]
This looks a bit like the similar issue we had in the Cluster Operator. Maybe you should try to do the Vert.x initialization only once per class and not per test. That was causing issue last time.

**Comment by OchiengEd** [comment]
I will give that a try; the interesting thing I noticed is the test seems to run multiple times before finally erring out.

**Comment by scholzj** [comment]
@strimzi-ci run tests

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.RollingUpdateST#testKafkaAndZookeeperScaleUpScaleDown,io.strimzi.systemtest.MirrorMakerST#testMirrorMakerTlsAuthenticated,io.strimzi.systemtest.ConnectST#testKafkaConnectWithFileSinkPlugin

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.RollingUpdateST#testKafkaAndZookeeperScaleUpScaleDown,io.strimzi.systemtest.MirrorMakerST#testMirrorMakerTlsAuthenticated,io.strimzi.systemtest.ConnectST#testKafkaConnectWithFileSinkPlugin

**Comment by scholzj** [comment]
Thanks a lot for the PR.

**Pull request merged**
