### PR TITLE
[MO] - [1st step paralelism] - random names for all resources

### PR DESCRIPTION
**Pull request by see-quick**
Signed-off-by: morsak <xorsak02@stud.fit.vutbr.cz>

### Type of change

- Enhancement / new feature
- Refactoring

### Description

This PR changing how we create resources. Now all resources have a random name by every test. Exceptions are shared resources, which are normally in @BeforeAll methods and needs to pass the constant name.

#### Why?

It is needed when we switch to the parallel execution of tests and we will avoid conflicts, for instance, Kafka clusters with same name etc.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by see-quick** [comment]
@strimzi-ci run tests profile=regression

**Comment by see-quick** [comment]
@strimzi-ci run tests profile=regression

**Comment by see-quick** [comment]
@strimzi-ci run tests  test_only profile=regression

**Comment by Frawless** [comment]
@strimzi-ci run tests test_only profile=regression testcase=MetricsST,UserST,LoggingChangeST,HttpBridgeST,HttpBridgeTlsST

**Comment by Frawless** [comment]
@strimzi-ci run tests test_only profile=regression testcase=MetricsST,UserST,LoggingChangeST,HttpBridgeST,HttpBridgeTlsST

**Comment by Frawless** [comment]
@strimzi-ci run tests test_only profile=regression testcase=MetricsST,UserST,LoggingChangeST,HttpBridgeST,HttpBridgeTlsST

**Review by Frawless — APPROVED** [review]

**Comment by Frawless** [comment]
The failure on Jenkins is not related to changes in this PR. I think it's a problem with logging in kube cluster on our infra as we face for quite a long time.

**Review by scholzj — APPROVED** [review]

**Pull request merged**
