### PR TITLE
NEW(Tests) OAuth2 with SASL plain test

### PR DESCRIPTION
**Pull request by michalxo**
This is a test for https://github.com/strimzi/strimzi-kafka-operator/pull/3961/ Integration of OAuth over PLAIN
Test passes fine with my changes to kafka example clients. Changes are in PR https://github.com/strimzi/client-examples/pull/54

Currently I have used junit 5 annotation `@Disabled` which does not seem to work for me when I am executing single test from IDEA UI.

- [x] Write tests
- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Comment by michalxo** [comment]
@strimzi-ci run tests false profile=oauth

**Comment by michalxo** [comment]
@strimzi-ci run tests false profile=oauth

**Comment by michalxo** [comment]
@strimzi-ci run tests false profile=oauth

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=oauth

**Review by im-konge — APPROVED** [review]

**Review by Frawless — CHANGES_REQUESTED** [review]
The PR for example-clients was merged so I guess you can enable it?

**Comment by michalxo** [comment]
@strimzi-ci run tests false profile=oauth

**Comment by michalxo** [comment]
@strimzi-ci run tests false profile=oauth

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=oauth

**Review by Frawless — APPROVED** [review]

**Review by scholzj — APPROVED** [review]

**Pull request merged**
