### PR TITLE
Move reconcilers from a Date supplier to Clock

### LINKED ISSUE #6603: Moving from a `Date` supplier to a `Clock` supplier
The `KafkaAssemblyOperator` is currently using a `Date` supplier to provide a `Date` instance where it's needed and allowing more easily the corresponding testing.
It's mostly used to check maintenance window time (related to the cron expression) and when stamping the time on CR conditions.
As discussed on #6580 it would be better (for consistency) to move to use a `Clock` instead of a `Date`.
Reporting the reason after that discussion.

I see the Date supplier used in two places ...

The first one is when writing the time in the CR conditions by using the StatusUtils.iso8601 [method](https://github.com/strimzi/strimzi-kafka-operator/blob/main/operator-common/src/main/java/io/strimzi/operator/common/operator/resource/StatusUtils.java#L38) which takes the Date instance and write the time in UTC starting from it.

The second place is about the maintenance window in the Util.isMaintenanceTimeWindowsSatisfied [method](https://github.com/strimzi/strimzi-kafka-operator/blob/main/operator-common/src/main/java/io/strimzi/operator/common/Util.java#L725) where it sets the timezone on the cron expression as UTC and then uses the isSatisfiedBy(date). Taking a look at the code inside this [method](https://github.com/quartz-scheduler/quartz/blob/master/quartz-core/src/main/java/org/quartz/CronExpression.java#L312) it seems that anyway when we pass our Date instance, it's getting the timezone of the cron expression (that we set to UTC) and compares dates in UTC anyway (even if our Date instance is referring to the local time).

So I was wondering ... because these are the only two places where we use the Date supplier and it's always handled in UTC, why not having "something" (Clock?) already taking the time in UTC by default?

### PR DESCRIPTION
**Pull request by devguyio**
### Type of change

- Refactoring

### Description

A followup PR after #7286 to move the rest of the reconcilers from a Date Supplier to a Clock.

Fixes #6603 

### Changes
- Refactor all reconcilers in the CO to use a Clock for providing time.
- Refactor the user operator to use a Clock for providing time.
- Refactor all related tests to reflect the above changes.
- Remove the overloaded ` Util.isMaintenanceTimeWindowsSatisfied` method which uses a date supplier.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [x] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
LGTM. Thanks.

**Comment by scholzj** [comment]
@devguyio Looks like there are some build errors to fix:
```
[ERROR] /home/vsts/work/1/s/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaReconciler.java:86:8: Unused import - java.util.Date. [UnusedImports]
[ERROR] /home/vsts/work/1/s/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaReconciler.java:95:8: Unused import - java.util.function.Supplier. [UnusedImports]
```

**Comment by devguyio** [comment]
> @devguyio Looks like there are some build errors to fix:
> 
> ```
> [ERROR] /home/vsts/work/1/s/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaReconciler.java:86:8: Unused import - java.util.Date. [UnusedImports]
> [ERROR] /home/vsts/work/1/s/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaReconciler.java:95:8: Unused import - java.util.function.Supplier. [UnusedImports]
> ```

Fixed

**Review by ppatierno — APPROVED** [review]

**Pull request merged**
