### PR TITLE
Update Fabric8 Kubernetes Client to 6.13 and the API specs derived from it

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Task

### Description

This PR updates Fabric8 to 6.13 and also updates the API specs derived from it to correspond to the new Kubernetes specifications (1.30).

### Checklist

- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Review by see-quick — APPROVED** [review]

**Comment by see-quick** [comment]
Should we at least run an acceptance profile? Or running integration tests is enough?

**Comment by scholzj** [comment]
> Should we at least run an acceptance profile? Or running integration tests is enough?

It needs to first pass the unit / integration tests before any system tests should be started.

**Review by im-konge — APPROVED** [review]

**Comment by ppatierno** [comment]
can you provide a little bit of more context around this new `appArmorProfile` stuff to people who are not familiar with it (me, maybe others) please?

**Comment by scholzj** [comment]
> can you provide a little bit of more context around this new `appArmorProfile` stuff to people who are not familiar with it (me, maybe others) please?

In some parts of the Strimzi CRDs, we reference the Kubernetes APIs and include them as a subset of our API (e.g. we use the Kubernetes definition inside our own CRDs instead of modeling the same API in our code). That means that when the Kubernetes API is updated, these changes appear in our CRD definitions as well. So in this case, the Kubernetes 1.30 API added the `appArmorProfile` field (I guess its part of the security context). And Fabric8 6.13 updated its Kubernetes APi model to include this change. So with update to Fabric8 6.13, this change bubbled through into the Strimzi CRDs as well.

AppArmor is some security tooling - to be honest I do not know much more about it. It is just part of the Kubernetes API now.

**Comment by ppatierno** [comment]
Thanks Jakub. I see it now. It was added as part of pod templating where we are using actual `Pod` Kubernetes resource so the CRD was updated as soon as you updated tge fabric8 version (related to the new Kube version).

**Review by ppatierno — APPROVED** [review]
LGTM

**Review by Frawless — APPROVED** [review]

**Pull request merged**
