### PR TITLE
Updates Dockerfile to support ppc64le architecture

### PR DESCRIPTION
**Pull request by krishvoor**
- Enhancement / new feature

### Description

This PR will allow building corresponding docker image
on ppc64le architecture as well.

Signed-off-by: Krishna Harsha Voora <krishvoor@in.ibm.com>

### Checklist
- [x] Make sure all tests pass - On Intel

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
What is the reason to bump it to 0.19? Does 0.18 not have an PPC64LE version?

**Review by sknot-rh — APPROVED** [review]

**Comment by krishvoor** [comment]
We do have an equivalent version of ppc64le ( identified as `ppc64el` in [0.18 tini](https://github.com/krallin/tini/releases/tag/v0.18.0) )
> What is the reason to bump it to 0.19? Does 0.18 not have an PPC64LE version?

The motivation is to keep this on par with the latest & greatest version of Tini.
And also to keep this on par with the tini versions found in strimzi-kafka-bridge.

Incase you want me change to 0.18, please let me know.

**Comment by scholzj** [comment]
I don't really have a strong opinion. I originally thought there is no 0.18 PPC64LE build but as you said, it is just named ppc64el. _Latest & greatest_ is just a one way to view the world. Another is _don't change what works_. :-o

@strimzi/maintainers do we wanna stick with 0.18 or move to 0.19?

**Review by Frawless — APPROVED** [review]
I don't have a strong opinion as well. We should run a regression to see if tini version didn't break anything.

**Pull request merged**
