### PR TITLE
Added cruise control metrics reporter dependency to Kafka 2.5.0

### PR DESCRIPTION
**Pull request by ppatierno**
Signed-off-by: Paolo Patierno <ppatierno@live.com>

### Type of change

- Bugfix

### Description

This PR adds the cruise control metrics reporter dependency to Kafka 2.5.0 pom file for third party libs. It also removes doubled dep in Kafka 2.4.0 pom file and fixes the Kafka with cruise control example.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by ppatierno** [comment]
@samuel-hawker why do you think that I dropped the support of cruise control for 2.4.x? I just removed a duplicate dependency from that pom file. cruise control metrics reporter dependency is till in 2.3.x, 2.4.x and now 2.5.x thirdlibs pom files.

**Comment by samuel-hawker** [comment]
You are absolutely correct, I misunderstood the dependency changes. Consider my questions answer :D

**Comment by ppatierno** [comment]
@strimzi-ci run tests profile=regression testcase=CruiseControlST

**Comment by ppatierno** [comment]
@strimzi-ci run tests profile=regression testcase=CruiseControlST

**Comment by ppatierno** [comment]
@strimzi-ci run tests

**Pull request merged**
