### PR TITLE
Add current raft state to grafana dashboard

### LINKED ISSUE #10538: Add the current Raft state to the KRaft Grafana dashboard
In #10533 we added the metrics with the current Raft state for the different nodes to the exported metrics. This might be something to also add to the KRaft Grafana dashboard. The metric shows what role does the broker currently play in KRaft - e.g. leader, follower, observer etc. It might ve shown for example as a table

The example of this metric can be seen in the attached screenshot.
Screenshot 2024-09-03 at 23 14 26

### PR DESCRIPTION
**Pull request by MichaelMorrisEst**
### Type of change

- Enhancement / new feature

### Description

Adds the current Raft state metric to the grafana dashboard as a table as per screenshot below

image

Closes #10538 

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [X] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [X] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. Could you please:
* Move the change to `packaging/examples/...`? The files in `examples/...` are the released files which change only with a new release.
* Once you do that, can you please run `make dashboard_install` to lso copy the change into the Helm Chart?

Thanks.

**Review by scholzj — COMMENTED** [review]
I tried it in my environment and it looks great.

The only thing I was wondering about is whether there issome way to sort the table? Right now it seems to have no soerting and with every update of the dashabord the lines reorder, so it is hard to read sometimes and acts a bit disruptively as it keeps changing.

**Comment by MichaelMorrisEst** [comment]
Sorted now by pod name:

image

**Review by scholzj — APPROVED** [review]
Great, thanks a lot.

**Review by ppatierno — APPROVED** [review]
LGTM. Thanks for the PR!

**Pull request merged**
