### PR TITLE
Create kafka-mirror-maker-2-sync-groups.yaml

### PR DESCRIPTION
**Pull request by stepan111**
https://github.com/strimzi/strimzi-kafka-operator/issues/4514

### Type of change

_Select the type of your PR_

- Documentation

### Description

Example how to configure idle consumer group synchronization with kafka MM2 replication

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
That is great, thanks!

**Comment by scholzj** [comment]
Can you fix the DCO sign-off? Something like this should fdo:

```
git commit --amend --no-edit --signoff
git push --force-with-lease origin master
```

More details can be found under the _Detais_ link in the status section.

**Review by sknot-rh — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Comment by scholzj** [comment]
@stepan111 The PR is not approved and passed all tests. Once you fix the DCO, I can merge it. Thanks.

**Comment by stepan111** [comment]
Thanks @scholzj , now commits are signed off.

**Comment by scholzj** [comment]
Thanks for the PR!

**Pull request merged**
