### PR TITLE
Add support for Kafka 3.1.0

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

This PR adds support for Kafka 3.1.0 and removes Kafka 2.8.0 and 2.8.1.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [x] Update documentation
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by laurovenancio** [comment]
Why to remove the kafka 2.8 support? It would be available just two versions (3.0.0 and 3.1.0) without minor versions fixes. It is risky to use them in a production environment. It would be great if strimzi could support images until the second minor version (2.8.2, 3.0.2, 3.1.2).

**Comment by scholzj** [comment]
@laurovenancio The Strimzi policy with regards to Kafka versions is to support the 2 latest minor versions => which right now will be 3.0 and 3.1. We do not have the resources to support and maintain the code for all the different Kafka versions. There is also no guarantee about the timing of the Kafka patch releases which makes it basically impossible to commit to anything like that.

**Comment by scholzj** [comment]
@strimzi/maintainers This should be now ready for review. The system test failures are not related to this PR.

**Review by ppatierno — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Pull request merged**
