### PR TITLE
renaming helm-chart artifact

### PR DESCRIPTION
**Pull request by matzew**
### Type of change

- Documentation

### Description

renaming the artifact - to be more 'readable' ?!?

### Checklist

- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by matzew** [comment]
@scholzj Ok, so ... perhaps `strimzi-helm-chart-cluster-operator-0.7.0-snapshot.tgz` is quite a mouth full, but IMO that pretty much discribes the bundle very well

**Comment by matzew** [comment]
relates to https://github.com/strimzi/strimzi-kafka-operator/issues/853

**Comment by scholzj** [comment]
@matzew I restarted the build ... it looks like either Travis or CentOS have a bad day. Was it needed to rename the Helm Chart just to have different name for the release artifact?

@seglo Is it OK to rename the Helm Chart?

**Comment by seglo** [comment]
@scholzj I chose `strimzi-kafka-operator` because it's the name of this repo that encompasses all the Strimzi bits: cluster, user, topic operators, etc.  IMO it's more descriptive to end users, whereas `strimzi-cluster-operator` is more ambiguous.  If we are to submit this chart to the central Helm repo then I think having Kafka in the name is important.

In my original PR I believe it was generated as `strimzi-kafka-operator-{VERSION}`, but I understand how that name could be confusing for end users just looking for the release archive which is a sibling file.  Since the actual artifact hosted by the Chart repository is `strimzi-kafka-operator-{VERSION}` I think we should stick to that name to avoid confusion.  Perhaps it could be put into a `charts/` dir in future github releases, if that's possible.

The preferred approach to installing the chart should be from the Strimzi Helm Chart Repository where it's referenced as `strimzi/strimzi-kafka-operator`.

**Comment by scholzj** [comment]
Thanks for the PR. I did there some additional changes to keep the original Chart name and rename only the release artifact.

**Pull request merged**
