### PR TITLE
[systemtest] Remove StatefulSet from tests

### PR DESCRIPTION
**Pull request by im-konge**
### Type of change

- Refactoring

### Description

This PR removes operations and checks around `StatefulSet` after graduation of the StrimziPodSet feature gate and removal of STS support.
I kept the `StatefulSetUtils` with few other things, because it is needed during the Keycloak installation in Oauth tests. 

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by scholzj — APPROVED** [review]
If it works 🤷

**Comment by im-konge** [comment]
The failure inside the KRaft regression pipeline are not related to this PR and will be resolved in one of the future PRs.

**Pull request merged**
