### PR TITLE
[ST] - Add support for multi-node kind cluster, update surefire and failsafe plugin version

### PR DESCRIPTION
**Pull request by see-quick**
### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

This PR introduces the capability to run on testing farm multi-node clusters using kind. Plus it updates a surefire and failsafe version.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by Frawless — APPROVED** [review]

**Review by im-konge — APPROVED** [review]

**Comment by see-quick** [comment]
Just for the context:

We have decided to let this issue be in terms of implementing some post-processing (i.e., modification of TEST XML), which from our POV is not good because in Kafka 3.7.0 probably such an issue will be resolved. Thus this pipeline will work without any problem. So I would merge it :)

**Pull request merged**
