### PR TITLE
ST: Add apender to loggers for components created by system tests

### PR DESCRIPTION
**Pull request by Frawless**
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

### Type of change

- Bugfix

### Description

This PR fixes component logging deployed by system tests. It should be changed again when https://github.com/strimzi/strimzi-kafka-operator/pull/3672 will be merged.

### Checklist

- [ ] Make sure all tests pass

### CODE REVIEW

**Comment by Frawless** [comment]
@strimzi-ci run tests profile=smoke test_only

**Review by stanlyDoge — APPROVED** [review]

**Comment by scholzj** [comment]
We need to make sure to this is all in sync with everything else. For example this is right now not what the docs recommend the customers to do.

**Comment by Frawless** [comment]
@scholzj I agree, I thought Marko will do all changes in doc as part of this "fix" PR. I can do it in the scope of this PR.

**Comment by stanlyDoge** [comment]
I did some improvements to Marko's PR. https://github.com/mstruk/strimzi-kafka-operator/pull/2/files
It should add an appender from the default logging configuration if needed. It would fix the doc as well (because it would work as it was before).

**Comment by Frawless** [comment]
@stanlyDoge  so this PR is maybe useless?

**Comment by stanlyDoge** [comment]
Hopefully yes. But it is harmless to have it set.

**Comment by scholzj** [comment]
> Hopefully yes. But it is harmless to have it set.

I do not know what are all the STs we have for logging. But unless we cover both, we should preferably follow the documented path to make sure whatever we tell the users to use works.

**Comment by Frawless** [comment]
Because those changes are not needed (master is fixed) I am closing this.

**Pull request closed without merging**
