### PR TITLE
Update supported Kubernetes version to 1.25+

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Task

### Description

This PR updates the supported Kubernetes versions to 1.25+ as planned. It updates the docs, the code and the various CI tooling.

### Checklist

- [x] Make sure all tests pass
- [x] Update documentation
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by ppatierno — APPROVED** [review]
LGTM

**Review by Frawless — APPROVED** [review]
TF errors are specific to TF itself, I am trying to debug it so I will propose a solution in different PR. It shouldn't block this one.

**Comment by scholzj** [comment]
Thanks for looking into it @Frawless

**Pull request merged**
