### PR TITLE
Bump up jupiter version

### PR DESCRIPTION
**Pull request by sknot-rh**
Signed-off-by: Stanislav Knot <sknot@redhat.com>

### Type of change
- Chores

### Description

Bump up Jupiter version to 5.7.0. It is mainly needed because of @Isolated annotation from Jupiter. 4.7.0. We need this annotation for a test case or test suite to run in isolation, no other test class or method can run concurrently. For instance, when we change the state of shared Kafka we need to run only that test case.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Might be worth to explain in the description why are you doing this. an you please add it?

**Comment by sknot-rh** [comment]
@see-quick ^

**Comment by see-quick** [comment]
It is mainly because of `@Isolated` annotation from Jupiter. 4.7.0. We need this annotation for a test case or test suite to run in isolation, no other test class or method can run concurrently. For instance, when we change the state of shared Kafka we need to run only that test case.

**Review by scholzj — APPROVED** [review]

**Review by Frawless — APPROVED** [review]
LGTM, just make sure the tests are green on azure

**Pull request merged**
