### PR TITLE
Drop Kaniko patch from Jenkins s390x scripts

### PR DESCRIPTION
**Pull request by kun-lu20**
Signed-off-by: Kun-Lu <kun.lu@ibm.com>

### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

_Please describe your pull request_

Since PR #6494 has upgraded Kaniko to v1.8.0 which has s390x support, this PR is to drop Kaniko patch from Jenkins s390x scripts.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [x] Make sure all tests pass
- [ ] Update documentation
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Comment by kun-lu20** [comment]
Hi @scholzj , could you please take a look at this PR? Thank you very much!

**Review by scholzj — APPROVED** [review]
Thanks for the PR.

**Comment by kun-lu20** [comment]
Hi @Frawless , could you please have a look at this PR? Thank you very much!

**Review by Frawless — APPROVED** [review]
LGTM

**Comment by kun-lu20** [comment]
Thanks @scholzj @Frawless

**Pull request merged**
