### PR TITLE
[systemtest][jenkins] Add new profiles - operators and components

### PR DESCRIPTION
**Pull request by im-konge**
Signed-off-by: Lukas Kral <lukywill16@gmail.com>

### Type of change

- Enhancement

### Description

This PR adds new two profiles to our `pom.xml` - `operators` and `components`. This will help us in our automation (Jenkins) - we can deal with tests, that should be run in each profile. Then, if the new package will be created and we'll want to exclude/include it in each profile, it will be much easier to maintain it -> no other extra PRs for Jenkins etc.

Also this PR adds these two new profiles to `TESTING.md` and changes the Jenkins PR jobs to be more configurable. 

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by im-konge** [comment]
FYI @strimzi/system-test-contributors

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=smoke

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=smoke

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=smoke

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=smoke

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=smoke

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only groups=connect

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only groups=connect

**Comment by im-konge** [comment]
@strimzi-ci run tests test_only profile=smoke

**Review by Frawless — APPROVED** [review]

**Review by see-quick — APPROVED** [review]

**Pull request merged**
