### PR TITLE
Fixed JMX KafkaCrdIT test for use on K8s 1.16+

### PR DESCRIPTION
**Pull request by tomncooper**
### Type of change

- Bugfix

### Description
Fixes the JMX test in the KafkaCrdIT so that it will pass on K8s 1.16 and above.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by tomncooper** [comment]
Sorry to be the bearer of bad news @tombentley but the recent PR I did to fix the other CrdITs for k8s 1.16 all look like this so this is consistent style ATM.

**Comment by tombentley** [comment]
Yes, but it's still not consistent with the overall Strimzi codebase. I don't know why I didn't point it out in that other PR (I did notice it), but the fact is that I didn't point it out at that point. I'd like to avoid spreading the inconsistency further.

**Comment by tomncooper** [comment]
Fair enough, would you like me to switch the other CrdITs over?

**Comment by scholzj** [comment]
I'm not sure I understand the problem. Are you suggesting @tombentley to have the string inlined into the assert?

**Comment by tombentley** [comment]
Yes

**Comment by scholzj** [comment]
Ok ... I'm actually fine both ways.

**Comment by tomncooper** [comment]
I will reformat them now

**Comment by tomncooper** [comment]
@tombentley hopefully the CrdITs are now consistent.

**Pull request merged**
