### PR TITLE
Improve the exception thrown with wrong image configuration

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

When users - for example after incorrect upgrade - ends up with CO deployment with missing or misconfigured environment variable for image configuration they currently get this cryptic exception:

```
Exception in thread "main" io.strimzi.operator.common.InvalidConfigurationException: io.strimzi.operator.cluster.model.NoImageException: No image for version 2.4.0
	at io.strimzi.operator.cluster.ClusterOperatorConfig.parseKafkaVersions(ClusterOperatorConfig.java:204)
	at io.strimzi.operator.cluster.ClusterOperatorConfig.fromMap(ClusterOperatorConfig.java:94)
	at io.strimzi.operator.cluster.Main.main(Main.java:59)
Caused by: io.strimzi.operator.cluster.model.NoImageException: No image for version 2.4.0
	at io.strimzi.operator.cluster.model.KafkaVersion$Lookup.image(KafkaVersion.java:163)
	at io.strimzi.operator.cluster.model.KafkaVersion$Lookup.validateKafkaMirrorMaker2Images(KafkaVersion.java:321)
	at io.strimzi.operator.cluster.ClusterOperatorConfig.parseKafkaVersions(ClusterOperatorConfig.java:202)
```

That doesn't really tell them much about the issue. Thsi PR improves the exception to make it more clear where the issue is:

```
Exception in thread "main" io.strimzi.operator.common.InvalidConfigurationException: Failed to parse default container image configuration for Kafka Mirror Maker 2 from environment variable STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
	at io.strimzi.operator.cluster.ClusterOperatorConfig.parseKafkaVersions(ClusterOperatorConfig.java:222)
	at io.strimzi.operator.cluster.ClusterOperatorConfig.fromMap(ClusterOperatorConfig.java:94)
	at io.strimzi.operator.cluster.Main.main(Main.java:59)
Caused by: io.strimzi.operator.cluster.model.NoImageException: No image for version 2.4.0
	at io.strimzi.operator.cluster.model.KafkaVersion$Lookup.image(KafkaVersion.java:163)
	at io.strimzi.operator.cluster.model.KafkaVersion$Lookup.validateKafkaMirrorMaker2Images(KafkaVersion.java:321)
	at io.strimzi.operator.cluster.ClusterOperatorConfig.parseKafkaVersions(ClusterOperatorConfig.java:220)
	... 2 more
```

This should help users better identify the problems.

### Checklist

- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=travis

**Comment by scholzj** [comment]
@tombentley I was thinking about it originally. It didn't seemed to fit so nicely inti single place. It is also technically not reading the environment variables. So refering to them there would be IMHO wrong.

**Comment by tombentley** [comment]
Valid point @scholzj. What made me think of it was that we have per-image methods in `Lookup` already, and having to make per-image calls to each of these methods from `Main` just means there's more places to have to update when images get added. But I can live with this.

**Comment by scholzj** [comment]
@samuel-hawker Fair point. I added a test for this. Please have a look. 

(I also fixed a typo in KafkaVersion.java which I randomly noticed and is related to this)

**Comment by samuel-hawker** [comment]
Great test, thanks for contributing! 👍

**Pull request merged**
