### PR TITLE
Add service account name to values

### PR DESCRIPTION
**Pull request by stgrace**
### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

This pull request allows for a different service account to be used for the operator.
We would like to use this chart in an environment that does not allow for a chart create roles and serviceaccounts. This change would be very helpful for us and wouldn't impact other users

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [x] Update documentation
- [x] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. I think this change should be fine in general. But can you please make it to `/packaging/helm-charts`? The files here in `/helm-charts` are the released files and they should not be changed outside of a new Strimzi release. Thanks.

**Comment by stgrace** [comment]
Sure, no problem

**Review by scholzj — COMMENTED** [review]
I think you are missing the change to the values file. That is why the build is failing with:

```
[ERROR] templates/: template: strimzi-kafka-operator/templates/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml:23:20: executing "strimzi-kafka-operator/templates/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml" at <.Values.serviceAccount>: can't evaluate field Values in type interface {}
```

**Comment by scholzj** [comment]
Hmm, it still seems to complain about the same ... 

```
helm lint --debug ../helm3/strimzi-kafka-operator/
==> Linting ../helm3/strimzi-kafka-operator/
[ERROR] templates/: template: strimzi-kafka-operator/templates/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml:23:20: executing "strimzi-kafka-operator/templates/031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml" at <.Values.serviceAccount>: can't evaluate field Values in type interface {}

Error: 1 chart(s) linted, 1 chart(s) failed
helm.go:84: [debug] 1 chart(s) linted, 1 chart(s) failed
main.newLintCmd.func1
	helm.sh/helm/v3/cmd/helm/lint.go:127
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.5.0/command.go:872
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.5.0/command.go:918
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:250
runtime.goexit
	runtime/asm_amd64.s:1571
make[1]: *** [Makefile:21: helm_lint] Error 1
make[1]: Leaving directory '/home/vsts/work/1/s/packaging/helm-charts/helm3'
make: *** [Makefile:191: packaging/helm-charts/helm3] Error 2
```

But no idea why :-/

**Comment by stgrace** [comment]
My mistake, I forgot to add the root context to some of the templates referencing .values

**Review by scholzj — APPROVED** [review]
Great, it looks like the build passed now. I started the system tests as well, but the code looks good. Thanks.

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
@stgrace I don't think the failure in the tests is related to your PR. We will investigate it.

**Comment by scholzj** [comment]
@stgrace I don't think the failure in the tests is related to your PR. We will investigate it.

**Comment by im-konge** [comment]
Hey @stgrace , tests failures seen in the AZP are not connected to your PR and will be fixed after #7647 will be merged.
Sorry for the issues :)

**Comment by stgrace** [comment]
Thanks for the quick response and merge guys, have a nice weekend

**Pull request merged**
