### PR TITLE
Add support for Kafka 3.1.1

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

This PR adds support for Kafka 3.1.1 to Strimzi.

### Checklist

- [x] Make sure all tests pass
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by ppatierno — APPROVED** [review]
LGTM. Just one question. Cannot we remove the support for 3.0.0 and 3.1.0 (leaving the patch releases) just to shrink to 3 supported versions and not 5?

**Comment by scholzj** [comment]
> LGTM. Just one question. Cannot we remove the support for 3.0.0 and 3.1.0 (leaving the patch releases) just to shrink to 3 supported versions and not 5?

That would make upgrades more complicated. We can remove 3.0.0 and 3.0.1 completely. But given the 0.29.0 release is imminent, it seems like something what not help users who want to keep using 3.0 and it would not help us much either. My plan was to remove 3.0.0 and 3.0.1 right after we do 0.29.0.

**Review by tomncooper — APPROVED** [review]

**Pull request merged**
