### PR TITLE
AC version

### PR DESCRIPTION
**Pull request by tombentley**
### Type of change

- Bugfix

### Description

Further to #2179, this PR changes the version of the AdminClient used by the CO and TO.

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Update/write design documentation in `./design`
- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md

### CODE REVIEW

**Comment by tombentley** [comment]
@strimzi-ci run tests

**Comment by tombentley** [comment]
I'm expecting the ST to fail (probably the upgrade test), but let's see...

**Comment by scholzj** [comment]
I'm not sure I agree with this. You do not have to use the old version to do that. Just read the docs and do your testing properly. And in some cases it might be desired to have new features available and use them only sometimes.

**Comment by tombentley** [comment]
Yeah, I didn't do it in #2179 because I thought this might be a little controversial.

> Just read the docs and do your testing properly.

That's easy to say, but in practice that's a very onerous testing burden because we must run every test on both versions (and in fact it requires that we write tests to be able to run on multiple versions). In comparison this is a very simple and cheap way of providing a fairly good guarantee against a subtle problem which was missed by both me (as developer) and at least one reviewer in 0.14.0.

> And in some cases it might be desired to have new features available and use them only sometimes.

That's true, but we don't actually need that _right now_. I would argue we should tackle that when we identify the need to make use of such features. Or can you already point to a feature you'd like to use today which isn't in 2.2.1?

You missed another criticism of this PR, which is that we're exposed to bugs in an old version which might be fixed in the new version. Perhaps a way to deal with that could be to compile against the old version, but use the new version at runtime. That would leave the door open allowing new features where we really need them (by calling those methods reflectively, though it would be complicated) while still providing a compile time guarantee against people using new APIs by mistake.

**Comment by tombentley** [comment]
@strimzi-ci run tests

**Pull request closed without merging**
