### PR TITLE
Update Kafka Bridge to 0.20.0

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Task

### Description

This PR updates the Strimzi Cluster Operator to use the Kafka Bridge version 0.20.0.

### Checklist

- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Update CHANGELOG.md

### CODE REVIEW

**Review by sknot-rh — APPROVED** [review]

**Comment by scholzj** [comment]
The ST failures are unrelated to this. This can be merged.

**Pull request merged**
