### PR TITLE
[MO] - [system test] -> obsolete deletion

### PR DESCRIPTION
**Pull request by see-quick**
Signed-off-by: morsak <xorsak02@stud.fit.vutbr.cz>

### Type of change

- Bugfix

### Description

In https://github.com/strimzi/strimzi-kafka-operator/pull/4137 I have made a copy-paste error. Instead of the `KafkaConnect` resource, I remove `KafkaMirrorMaker`. Moreover, in past, we delete every resource, which is created without waiting explicitly as can be seen below... Currently our `ResourceManager` is taking care of deletion after test case in completed.

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Review by Frawless — APPROVED** [review]
Just a question - did you find all occurrences of this issue?

**Comment by see-quick** [comment]
> Just a question - did you find all occurrences of this issue?

I wanted to create an issue for that because it could be huge...This is only for `SecurityST` test suite. But of course, I can do a scan of the whole module.

**Comment by Frawless** [comment]
Well, I guess it's up to you, I am fine with open separate PR if this is something urgent to merge.

**Comment by see-quick** [comment]
> Well, I guess it's up to you, I am fine with open separate PR if this is something urgent to merge.

I will do it in separate PR :)

**Pull request merged**
