### PR TITLE
Add support for CORS in HTTP KAfka Bridge

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Enhancement / new feature

### Description

The HTTP Bridge will add support for CORS in 0.16.0 release. This PR integrates this support into the Cluster Operator and the KafkaBridge PR.

### Checklist

- [x] Write tests
- [x] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by scholzj** [comment]
@ppatierno It is just draft since we don't have the Birdge released. But some quick feedback would be handy.

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=bridge

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=bridge

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=bridge testcase=io.strimzi.systemtest.bridge.HttpBridgeST#testReceiveSimpleMessage,io.strimzi.systemtest.bridge.HttpBridgeTlsST#testReceiveSimpleMessageTls,io.strimzi.systemtest.bridge.HttpBridgeTlsST#testTlsAuthWithWeirdNamedUser,io.strimzi.systemtest.bridge.HttpBridgeScramShaST#testScramShaAuthWithWeirdNamedUser,io.strimzi.systemtest.bridge.HttpBridgeScramShaST#testReceiveSimpleMessageTlsScramSha,io.strimzi.systemtest.LogSettingST#testJSONFormatLogging

**Comment by ppatierno** [comment]
@scholzj lgtm. I will approve when it's not a draft anymore

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=bridge

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=acceptance testcase=io.strimzi.systemtest.security.SecurityST#testAutoRenewAllCaCertsTriggeredByAnno

**Comment by scholzj** [comment]
@Frawless Why does it seem to run the `acceptance` profile when I asked it to run the `bridge` profile? That seemed to have worked two few days ago.

**Comment by Frawless** [comment]
@scholzj I can see in the logs that jenkins started by azure-piplines comment and previous one comment was just ignored by plugin I think.I will update the phrase to avoid this

**Comment by Frawless** [comment]
@scholzj I did some digging and it seems it's not a problem in our configuration, but it's a simple race condition. You triggered jenkins correctly, but right after your first comment you put there comment to trigger azure. Jenkins noticed comment with `strimzi-ci` but as an input it's parsed `/azp ...` which caused default configuration for the PR build. I don't think we can do something with it, because it's probably some race or wrong code in plugin which we use. I can try to investigate it more, but I am not sure if it's worth. You can easi;y avoid this situation by trigger azure at first and then jenkins

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=bridge

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=bridge

**Comment by scholzj** [comment]
Since the Bridge 0.16.0 is ready now, I changed this from Draft to regular PR.

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=bridge testcase=io.strimzi.systemtest.LogSettingST#testJSONFormatLogging

**Pull request merged**
