### PR TITLE
Add truststore configuration for HTTPS connections to OPA server

### PR DESCRIPTION
**Pull request by Eric84626**
Type of change
Enhancement / new feature
Description
Add truststore configuration for HTTPS connections to OPA server

Checklist
Related issue: https://github.com/strimzi/strimzi-kafka-operator/issues/8001

### CODE REVIEW

**Comment by Eric84626** [comment]
Thanks a lot for your comments in another PR https://github.com/strimzi/strimzi-kafka-operator/pull/8010, @scholzj .
As your mentioned, the old PR has some problem that seems to have some commits from other PRs.
I closed that, and created this new one. I have made code changes as your comments.

Please review it.

**Comment by scholzj** [comment]
It looks like there is some uncommitted change in the generated docs file:

```
ERROR: Uncommitted changes in derived resources:
M	documentation/modules/appendix_crds.adoc
Run the following to add up-to-date resources:
  mvn clean verify -DskipTests -DskipITs \
    && make crd_install \
    && make helm_install \
    && git add packaging/install/ packaging/helm-charts/ documentation/modules/appendix_crds.adoc cluster-operator/src/main/resources/cluster-roles \
    && git commit -s -m 'Update derived resources'
```

That is what failed in the CI.

**Comment by scholzj** [comment]
Committing the file was fine, but it seemed like it was not up to date with the changes to the `api` module.

**Comment by Eric84626** [comment]
> Committing the file was fine, but it seemed like it was not up to date with the changes to the `api` module.

Is this file auto-gernerated by script? I should not update it manually?
I reverted back my code changes for this file, but I still got this issue.

**Comment by Eric84626** [comment]
> If you run this command:
> 
> ```
> mvn clean verify -DskipTests -DskipITs \
>     && make crd_install \
>     && make helm_install
> ```
> 
> That should update the file. And then you have to commit the changes it creates to the PR.

Got it, thanks

**Review by scholzj — APPROVED** [review]
I will run the regression tests. But LGTM from the code. Thanks for the PR.

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR @Eric84626

**Pull request merged**
