### PR TITLE
Add metric for connector auto-restarts

### LINKED ISSUE #7900: Add metrics for connector auto-restarts
From Strimzi 0.33, we now have support for auto-restarting connectors. But right now, the information about the restarts is available only in the logs and in the status of the connector. But in the status, it might be available only for a limited time since the auto-restart status is reset if the connector is running again for some time. It would be useful to also have some metrics about the restarts. This would allow us to set up alerting or monitor it through dashboards. That would make it easier to notice if some connector is unstable for example.

Raised by https://github.com/strimzi/strimzi-kafka-operator/pull/7896#issuecomment-1380411407

### PR DESCRIPTION
**Pull request by haanhvu**
### Type of change

_Select the type of your PR_

- Enhancement / new feature

### Description

fixes #7900 

### Checklist

_Please go through this checklist and make sure all applicable tasks have been done_

- [ ] Write tests
- [ ] Make sure all tests pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [ ] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [ ] Reference relevant issue(s) and close them after merging
- [ ] Update CHANGELOG.md
- [ ] Supply screenshots for visual changes, such as Grafana dashboards

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Looks good to me. But a unit test would be nice. Arent't there already some metrics tests for Connect?

**Comment by ppatierno** [comment]
LGTM as well. Waiting for tests as suggested by Jakub.

**Comment by haanhvu** [comment]
@scholzj @ppatierno I need to add a test here right? https://github.com/strimzi/strimzi-kafka-operator/blob/main/operator-common/src/test/java/io/strimzi/operator/common/OperatorMetricsTest.java

**Comment by scholzj** [comment]
I think I would add a metric check to an existing tests. Looking at the original PR ... `cluster-operator/src/test/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectorIT.java` has tests `testConnectorIsAutoRestarted` and `testTaskIsAutoRestarted`. Can you add it as additional assert into these tests?

**Review by scholzj — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR.

**Pull request merged**
