### PR TITLE
Update the OAuth library to 0.6.1

### PR DESCRIPTION
**Pull request by scholzj**
### Type of change

- Bugfix

### Description

This PR updates the Strimzi OAuth library to 0.6.1 which contains some updated dependencies to address CVEs.

### CODE REVIEW

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=oauth

**Comment by scholzj** [comment]
@mstruk @Frawless @see-quick Any more tests to run on this than the acceptance suite on AZP + OAuth profile on Jenkins?

**Comment by scholzj** [comment]
@strimzi-ci run tests profile=oauth

**Comment by Frawless** [comment]
@scholzj no, it should be all

**Comment by scholzj** [comment]
@ppatierno Any chance to get a review on this?

**Review by mstruk — APPROVED** [review]
Things seem to work fine.

**Review by Frawless — APPROVED** [review]

**Pull request merged**
