### PR TITLE
Added 8 new charts to Kafka Connect Grafana dashboard

### PR DESCRIPTION
**Pull request by pantaoran**
### Type of change

- Enhancement / new feature

### Description

 * Added 5 new charts to Kafka Connect Grafana dashboard, 2 of them replaced existing less useful ones
dashboard-newer

### Checklist

- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by pantaoran** [comment]
Thank you for your input!

What you write sounds plausible at first, but then my observations do not match it. I believe that for example the "Consumer outgoing bytes per secod" are the rate at which it is writing to the external system.

For example I ran a performance test with an S3 backup sink connector: the consumer/sink incoming rate was several MB/s while the test was running, and the outgoing rate was around 60 KB/s. I then looked at the amount of data that arrived in the AWS S3 bucket and it roughly matched the outgoing rate as reported by the Grafana dashboard. My explanation for the ~100x size difference between incoming and outgoing is the gzip compression on the files written to AWS (I downloaded a file and extracted it to see the compression ratio and it was like ~97%).

**Comment by ppatierno** [comment]
Tbh I don't think it's the case. The `kafka_consumer_outgoing_byte_total` is a metric related to a Kafka consumer in general so not tied to Kafka Connect or any connector. If you just run a Kafka consumer (so no Kafka Connect in the picture) you have this metric exposed. As the Kafka documentation says it's "The average number of outgoing bytes sent per second to all servers." [1] so it's really about bytes flowing from the consumer to the brokers. These bytes are related to the low-level message protocol from consumer to broker, so for example "commit" messages.
I don't know the S3 connector but maybe it exposes some specific metrics about outgoing bytes which really are the ones pushed from the sink connector to the S3 bucket.

[1] https://kafka.apache.org/documentation.html#selector_monitoring

**Comment by pantaoran** [comment]
After further discussions with my colleagues I think you're probably right. I will change the PR to a new proposal next week.

**Comment by ppatierno** [comment]
Looking forward to it!

**Comment by pantaoran** [comment]
I have much reduced the amount of new charts to reflect the outcome of our previous discussion.

**Comment by ppatierno** [comment]
@pantaoran before we review this you should check what happened. There are 111 files changed and I don't think it's related to your changes, maybe a missing rebase against a new master. Please check that and provide a clean PR with just your changes, thanks!

**Comment by pantaoran** [comment]
That's weird, how is that possible? I only ever touched 2 files.
Just now I have merged upstream/master into my forked repo branch (`git merge -X theirs upstream/master`), but now I still see 4 changed files which I never touched...?

**Comment by scholzj** [comment]
I think you should just rebase to latest master instead of merging. That should also remove the commits from your PR

**Comment by pantaoran** [comment]
Apologies for the mess, apparently I'm incapable of understanding git -_-
I have created a new fork and a new PR from that, here: https://github.com/strimzi/strimzi-kafka-operator/pull/3322

Please decline/close this here and let's use the new PR.

**Comment by scholzj** [comment]
@pantaoran Don't worry ... I think all of us did that at least once in our life ... that is the solution which never fails :-).

**Pull request closed without merging**
