### PR TITLE
[MO] - [system test] -> parallelism + OLM fixes

### PR DESCRIPTION
**Pull request by see-quick**
### Type of change

- Bugfix
- Enhancement / new feature

### Description

This PR fixes a few things related to the OLM installation with namespace handling in the deletion or installation process. Moreover, it fixes one problem with class-wide parallelization related to bad annotation (which locks the entire execution and
 results in a deadlock situation). Also removing unnecessary invocation of method `set()` because AtomicInteger holds a reference to its value and thus do not need to assign it. Additionally, there is no need to annotate methods such as adding or removing test cases and test suites with synchronized because `incrementAndGet` is an atomic operation (more here -> https://docs.oracle.com/javase/specs/jls/se10/html/jls-8.html#jls-8.3.1.4). 

### Checklist

- [x] Make sure all tests pass

### CODE REVIEW

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only test_count_running_in_parallel=4

**Review by im-konge — APPROVED** [review]
LGTM, assuming it works.

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only test_count_running_in_parallel=4

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only test_count_running_in_parallel=3

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only test_count_running_in_parallel=3

**Review by Frawless — APPROVED** [review]
I assume all tests are working properly.

I think we should have a pipeline, which will try to install the latest released Strimzi via OLM to verify, that tests are working fine after all that crazy changes around test parallelism. Idea for next PR.

**Comment by see-quick** [comment]
@strimzi-ci run tests test_only test_count_running_in_parallel=2

**Pull request merged**
